import {agendaPriority,priorityColorsByDay} from '../lib/agenda-priority';
import {expandAgenda,eventStart,readRepeat,REPEATS} from '../lib/agenda-recurrence';
import {useAgendaMonth} from '../lib/use-agenda-month';
import {useAgendaView} from '../lib/agenda-view';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ScrollView,View,Text,Pressable,RefreshControl} from 'react-native';
import {SofiaApi} from '../lib/api';
import {useTheme} from '../lib/theme';
import {localDateKey} from '../lib/dashboard';
import {dayKey,errorText} from '../lib/chat-model';
import type {AgendaItem,Catalog,Entity} from '../lib/types';
import {Empty,ErrorBanner,IconButton,ScreenTitle} from '../components/UI';
import {MonthSwipe} from '../components/MonthSwipe';
import {EntityEditor,Choice} from './Workspace';
export function Agenda({api,target,active=true,onGestureLock}:{onGestureLock?:(locked:boolean)=>void;api:SofiaApi;target?:{date:string;id?:string;create?:boolean;nonce:number};active?:boolean}){
 const {month,setMonth,selected:selectedKey,setSelected:setSelectedKey,acceptTarget}=useAgendaView(api,'agenda',active),selected=new Date(selectedKey+'T12:00:00'),setSelected=(value:Date)=>setSelectedKey(localDateKey(value));
 const c=useTheme(),[refreshing,setRefreshing]=useState(false),[actionError,setError]=useState(''),[catalog,setCatalog]=useState<Catalog|null>(null),[editing,setEditing]=useState<Partial<Entity>|null>(null),[kind,setKind]=useState('commitment');
 const {items,loading,pending,error:loadError,refresh}=useAgendaMonth(api,month,active),error=actionError||(loadError?errorText(loadError):'');
 async function load(manual=false){if(manual)setRefreshing(true);try{await refresh();}finally{if(manual)setRefreshing(false);}}
 useEffect(()=>{let alive=true;if(active&&!catalog)api.catalog().then(cat=>{if(alive)setCatalog(cat);}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[api,active,catalog]);
 useEffect(()=>{if(!target?.date||!active||!catalog)return;if(!acceptTarget(target.date,target.nonce))return;if(target.create)create(new Date(target.date+'T12:00:00'));else if(target.id)api.entity(target.id).then(setEditing).catch(e=>setError(errorText(e)));},[target?.nonce,api,active,catalog]);
 const start=(item:AgendaItem)=>item.data.calendar_all_day?item.data.calendar_date_start||'':item.data.start_at||item.data.remind_at||item.data.due_at||'',activeItems=useMemo(()=>expandAgenda(items,month),[items,month.getTime()]);
 const priorityDays=useMemo(()=>priorityColorsByDay(activeItems.map(i=>({date:localDateKey(eventStart(i)),priority_level:i.data.priority_level})),c.accent),[activeItems,c.accent]);
 const chosen=activeItems.filter(i=>start(i)&&localDateKey(start(i))===dayKey(selected)).sort((a,b)=>Date.parse(start(a))-Date.parse(start(b)));
 const cells:(Date|null)[]=Array.from({length:month.getDay()},()=>null);for(let d=1;d<=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();d++)cells.push(new Date(month.getFullYear(),month.getMonth(),d));while(cells.length%7)cells.push(null);
 function create(day=selected){const d=new Date(day);d.setHours(9,0,0,0);setEditing({kind,title:'',data:{[kind==='reminder'?'remind_at':'start_at']:d.toISOString()}});}
 async function edit(item:AgendaItem){try{setEditing(await api.entity(item.id));}catch(e){setError(errorText(e));}}
 return <><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:25}} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={c.accent}/>}><ScreenTitle eyebrow="SEU TEMPO · SEUS COMPROMISSOS" title="Sua agenda" right={<IconButton name="plus" label="Criar item na data selecionada" filled disabled={!catalog} onPress={()=>create()}/>}/>{error?<ErrorBanner text={error} onRetry={()=>void load()}/>:null}
 <MonthSwipe onLock={onGestureLock} onMonth={delta=>setMonth(m=>new Date(m.getFullYear(),m.getMonth()+delta,1))}><View style={{marginHorizontal:20,padding:18,borderRadius:24,backgroundColor:c.surface,borderWidth:1,borderColor:c.line}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14}}><IconButton name="back" label="Mês anterior" onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}/><Pressable accessibilityLabel="Voltar para hoje" onPress={()=>{const d=new Date();setMonth(new Date(d.getFullYear(),d.getMonth(),1));setSelected(d);}}><Text style={{color:c.text,fontSize:17,fontWeight:'600',textTransform:'capitalize'}}>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</Text></Pressable><IconButton name="chevron" label="Próximo mês" onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}/></View>
 <View style={{flexDirection:'row'}}>{['D','S','T','Q','Q','S','S'].map((d,i)=><Text key={i} style={{width:'14.2857%',textAlign:'center',fontSize:11,color:c.muted,marginBottom:8}}>{d}</Text>)}</View><View style={{flexDirection:'row',flexWrap:'wrap'}}>{cells.map((day,index)=><View key={index} style={{width:'14.2857%',padding:2}}>{day?<Pressable testID={'agenda-day-'+dayKey(day)} accessibilityState={{selected:dayKey(day)===dayKey(selected)}} onPress={()=>setSelected(day)} onLongPress={()=>{setSelected(day);if(catalog)create(day);}} accessibilityRole="button" accessibilityLabel={day.toLocaleDateString('pt-BR')} style={{minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:13,backgroundColor:dayKey(day)===dayKey(selected)?c.accent:'transparent',gap:3}}><Text style={{fontSize:14,color:dayKey(day)===dayKey(selected)?'#FFFFFF':c.text,fontWeight:dayKey(day)===dayKey(new Date())?'700':'400'}}>{day.getDate()}</Text><View style={{height:3,flexDirection:'row',gap:3}}>{(priorityDays.get(dayKey(day))||[]).map(color=><View key={color} style={{height:3,width:3,borderRadius:2,backgroundColor:color===c.accent&&dayKey(day)===dayKey(selected)?'#FFFFFF':color}}/>)}</View></Pressable>:<View style={{height:44}}/>}</View>)}</View></View></MonthSwipe>
 <View style={{paddingHorizontal:22,paddingTop:24,gap:13}}><Text testID="agenda-selected-date" style={{fontSize:20,fontWeight:'600',color:c.text,textTransform:'capitalize'}}>{selected.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</Text><Choice label="Tipo do novo item" value={kind} options={[{value:'commitment',label:'Compromisso / evento'},{value:'reminder',label:'Lembrete'}]} onChange={setKind}/>
 {(loading||pending)?<Text accessibilityRole="progressbar" style={{color:c.muted,fontSize:12}}>{pending?'Atualizando compromissos do Google…':'Carregando compromissos…'}</Text>:null}{chosen.length?chosen.map(item=><Pressable key={item.id+eventStart(item)} onPress={()=>void edit(item)} style={{flexDirection:'row',gap:14,padding:18,borderRadius:20,backgroundColor:c.surface,borderWidth:1,borderColor:c.line}}><View style={{width:3,borderRadius:3,backgroundColor:agendaPriority(item).color||c.accent}}/><View style={{flex:1,gap:6}}><Text style={{fontSize:11,color:c.accent,fontWeight:'600'}}>{item.data.calendar_all_day?'Dia inteiro':new Date(start(item)).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · {item.kind==='reminder'?'Lembrete':'Compromisso'}</Text><Text style={{fontSize:16,lineHeight:22,color:c.text,fontWeight:'500'}}>{item.title}</Text>{agendaPriority(item).value!=='none'?<Text style={{fontSize:11,color:agendaPriority(item).color||c.accent}}>{agendaPriority(item).symbol} {agendaPriority(item).label}</Text>:null}{readRepeat(item).frequency!=='none'?<Text style={{fontSize:11,color:c.accent}}>↻ {REPEATS.find(p=>p.value===readRepeat(item).frequency)?.label}</Text>:null}{item.data.location?<Text style={{fontSize:12,color:c.muted}}>{item.data.location}</Text>:null}</View></Pressable>):loading||pending?null:<Pressable onPress={()=>{if(catalog)create();}}><Empty icon="calendar" title="Espaço no seu dia" body="Toque aqui ou no + para criar nesta data. Toque em um compromisso para editar."/></Pressable>}<Text style={{fontSize:11,lineHeight:18,color:c.muted}}>Agenda da Sofia · horários no fuso do celular. Toque e segure um dia para criar diretamente nele.</Text></View></ScrollView>
 {editing&&catalog?<EntityEditor api={api} item={editing} definition={catalog.catalog[editing.kind!]} areas={catalog.areas} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);void load();}}/>:null}</>;
}
