import {themeTimes,validThemeTime} from '../lib/theme-schedule';
import {ThemeScheduleSettings} from '../components/ThemeScheduleSettings';
import {AgendaNotificationSettings} from '../components/AgendaNotificationSettings';
import {ConnectionsSettings} from '../components/ConnectionsSettings';
import {MotionModal} from '../components/MotionModal';
import React,{useState} from 'react';
import {View,Text,ScrollView,TextInput,Switch,Pressable,Linking,Alert,Modal} from 'react-native';
import {SofiaApi,SITE} from '../lib/api';
import {useTheme} from '../lib/theme';
import {initials,errorText} from '../lib/chat-model';
import type {Bootstrap,Prefs,Profile as UserProfile,Appearance} from '../lib/types';
import {Brand,Button,ErrorBanner,ScreenTitle,IconButton,forms} from '../components/UI';
import {Icon} from '../components/Icon';
import {APP_VERSION} from '../lib/update';
import {GoogleCalendarSettings} from '../components/GoogleCalendarSettings';
export function Profile({api,bootstrap,prefs,onPrefs,onProfile,onLogout,onCheckUpdate,onChatHistoryCleared}:{api:SofiaApi;bootstrap:Bootstrap;prefs:Prefs;onPrefs:(p:Prefs)=>Promise<void>;onProfile:(p:UserProfile)=>void;onLogout:()=>Promise<void>;onCheckUpdate:()=>Promise<void>;onChatHistoryCleared:()=>void}){
 const c=useTheme(),[section,setSection]=useState<'app'|'profile'>('profile'),[name,setName]=useState(bootstrap.profile.name),[saving,setSaving]=useState(false),[error,setError]=useState(''),[passwordModal,setPasswordModal]=useState(false),[current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState('');
 async function save(){setSaving(true);try{const r=await api.profile(name.trim());onProfile(r.profile);setError('');}catch(e){setError(errorText(e));}finally{setSaving(false);}}
 async function preference(p:Prefs){try{await onPrefs(p);}catch(e){setError(errorText(e));}}
 async function changePassword(){if(saving)return;if(next.length<12||next!==confirm){setError('Use pelo menos 12 caracteres e repita a mesma senha.');return;}setSaving(true);try{await api.changePassword(current,next,confirm);setCurrent('');setNext('');setConfirm('');setPasswordModal(false);await onLogout();}catch(e){setError(errorText(e));}finally{setSaving(false);}}
 function logoutAll(){Alert.alert('Encerrar todas as sessões?','Será necessário entrar novamente no site e em todos os celulares.',[{text:'Cancelar',style:'cancel'},{text:'Encerrar',style:'destructive',onPress:()=>{api.logoutAll().then(onLogout).catch(e=>setError(errorText(e)));}}]);}
 function clearHistory(){Alert.alert('Apagar histórico do chat?','As conversas do app e da web serão apagadas. Memórias, tarefas e outros registros salvos separadamente continuam existindo.',[{text:'Cancelar',style:'cancel'},{text:'Apagar tudo',style:'destructive',onPress:()=>{setSaving(true);api.clearChatHistory().then(()=>{onChatHistoryCleared();Alert.alert('Histórico apagado','O histórico sincronizado do app e da web foi apagado.');}).catch(e=>setError(errorText(e))).finally(()=>setSaving(false));}}]);}
 return <><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingBottom:30}}><ScreenTitle title="Perfil" eyebrow="APLICATIVO · SUA CONTA" right={<Text accessibilityLabel={'Versão instalada '+APP_VERSION} style={{fontSize:12,color:c.muted}}>{APP_VERSION}</Text>}/><View style={{flexDirection:'row',gap:8,paddingHorizontal:22,marginBottom:18}}>{([{id:'profile',title:'Perfil do usuário'},{id:'app',title:'Configurações do aplicativo'}] as const).map(item=><Pressable key={item.id} onPress={()=>setSection(item.id)} accessibilityRole="tab" accessibilityState={{selected:section===item.id}} style={{flex:1,padding:13,borderRadius:12,backgroundColor:section===item.id?c.accentSoft:c.input}}><Text style={{color:section===item.id?c.accent:c.text,fontWeight:'600',textAlign:'center'}}>{item.title}</Text></Pressable>)}</View>{error?<ErrorBanner text={error}/>:null}<View style={{paddingHorizontal:22,gap:22}}>
 {section==='profile'?<View style={[forms.card,{backgroundColor:c.surface,borderWidth:1,borderColor:c.line}]}><View style={{flexDirection:'row',gap:14,alignItems:'center'}}><Brand size={60} label={initials(bootstrap.profile.name)}/><View style={{flex:1,gap:5}}><Text style={{color:c.text,fontSize:20,fontWeight:'600'}}>{bootstrap.profile.name}</Text><Text style={{color:c.accent,fontSize:12}}>Proprietário</Text></View></View><Text style={[forms.label,{color:c.muted,marginTop:6}]}>NOME</Text><TextInput value={name} onChangeText={setName} maxLength={80} accessibilityLabel="Nome do perfil" style={[forms.input,{color:c.text,backgroundColor:c.input,borderColor:c.line}]}/><Text style={[forms.label,{color:c.muted}]}>E-MAIL DE LOGIN</Text><Text selectable style={{color:c.text,fontSize:13,lineHeight:20}}>{bootstrap.profile.email}</Text><Button title="Salvar perfil" secondary loading={saving} disabled={!name.trim()||name.trim()===bootstrap.profile.name} onPress={()=>void save()}/></View>:null}
 {section==='app'?<><View style={[forms.card,{backgroundColor:c.surface,borderWidth:1,borderColor:c.line}]}><Text style={{color:c.text,fontWeight:'600',fontSize:18}}>Do seu jeito</Text><Text style={{fontSize:12,color:c.muted}}>Aparência neste dispositivo</Text><View style={{flexDirection:'row',gap:8}}>{([{id:'schedule',label:'Horário'},{id:'system',label:'Sistema'},{id:'light',label:'Claro'},{id:'dark',label:'Escuro'}] as {id:Appearance;label:string}[]).map(mode=><Pressable key={mode.id} accessibilityRole="button" accessibilityState={{selected:prefs.appearance===mode.id}} onPress={()=>void preference({...prefs,appearance:mode.id})} style={{flex:1,backgroundColor:prefs.appearance===mode.id?c.accentSoft:c.input,minHeight:45,borderRadius:12,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:12,color:prefs.appearance===mode.id?c.accent:c.muted,fontWeight:'600'}}>{mode.label}</Text></Pressable>)}</View>{prefs.appearance==='schedule'?<ThemeScheduleSettings prefs={prefs} onSave={preference}/>:null}<View style={{flexDirection:'row',alignItems:'center',gap:12,marginTop:12}}><View style={{flex:1,gap:5}}><Text style={{color:c.text,fontWeight:'500'}}>Enter para enviar</Text><Text style={{fontSize:12,color:c.muted,lineHeight:18}}>Desligado: Enter quebra a linha.</Text></View><Switch value={prefs.enterToSend} onValueChange={v=>void preference({...prefs,enterToSend:v})}/></View>
 <View style={{flexDirection:'row',alignItems:'center',gap:12,marginTop:12}}><View style={{flex:1,gap:5}}><Text style={{color:c.text,fontWeight:'500'}}>Enviar áudio ao parar</Text><Text style={{fontSize:12,color:c.muted,lineHeight:18}}>Ligado por padrão: ao tocar em parar, a gravação é enviada. Desligue para ouvir antes.</Text></View><Switch value={prefs.autoSendVoice} onValueChange={v=>void preference({...prefs,autoSendVoice:v})}/></View></View><AgendaNotificationSettings/><ConnectionsSettings api={api}/><GoogleCalendarSettings api={api}/></>:null}
 {section==='profile'?<View style={[forms.card,{backgroundColor:c.surface,borderWidth:1,borderColor:c.line}]}><View style={{flexDirection:'row',gap:10,alignItems:'center'}}><Icon name="shield" color={c.accent}/><Text style={{color:c.text,fontSize:18,fontWeight:'600'}}>Segurança e sessão</Text></View><Text style={{color:c.muted,fontSize:12,lineHeight:20}}>Você permanece conectado até sair. A sessão continua válida entre atualizações e sua senha não fica salva neste aparelho.</Text><Button title="Alterar senha" secondary onPress={()=>{setError('');setPasswordModal(true);}}/><Button title="Sair deste dispositivo" secondary onPress={()=>{Alert.alert('Sair da Sofia?','Você precisará entrar novamente.',[{text:'Cancelar',style:'cancel'},{text:'Sair',onPress:()=>void onLogout()}]);}}/><Pressable onPress={logoutAll} style={{minHeight:44,justifyContent:'center'}}><Text style={{color:c.danger,textAlign:'center',fontWeight:'600',fontSize:13}}>Encerrar todas as sessões</Text></Pressable></View>:null}
 {section==='app'?<View style={[forms.card,{backgroundColor:c.surface,borderWidth:1,borderColor:c.line}]}><Text style={{color:c.text,fontSize:18,fontWeight:'600'}}>Histórico da conversa</Text><Text style={{color:c.muted,fontSize:12,lineHeight:19}}>App e web usam o mesmo histórico. Mensagens individuais podem ser apagadas segurando sobre elas.</Text><Pressable onPress={clearHistory} style={{minHeight:48,justifyContent:'center'}}><Text style={{color:c.danger,textAlign:'center',fontWeight:'700'}}>Apagar histórico do chat</Text></Pressable></View>:null}
 {section==='app'?<View style={[forms.card,{backgroundColor:c.surface,borderWidth:1,borderColor:c.line}]}><Text style={{color:c.text,fontSize:18,fontWeight:'600'}}>Atualizações</Text><Text accessibilityLabel={'Versão instalada '+APP_VERSION} style={{color:c.accent,fontSize:14,fontWeight:'600'}}>Versão instalada: {APP_VERSION}</Text><Text style={{color:c.muted,fontSize:12,lineHeight:19}}>A Sofia verifica novas versões automaticamente. A instalação sempre pede sua confirmação no Android.</Text><Button title="Verificar atualizações" secondary onPress={()=>void onCheckUpdate()}/></View>:null}
 <View style={{gap:4}}>{[['Site público','site'],['Privacidade','privacy'],['Termos de serviço','terms'],['Solicitar exclusão de dados','data-deletion']].map(([label,path])=><Pressable key={path} accessibilityRole="link" onPress={()=>void Linking.openURL(SITE+'/'+path)} style={{minHeight:46,flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{color:c.muted,fontSize:13}}>{label}</Text><Icon name="chevron" color={c.muted} size={16}/></Pressable>)}</View><Text style={{color:c.muted,fontSize:11,textAlign:'center'}}>Sofia OS {APP_VERSION} · Servidor {bootstrap.version}</Text></View></ScrollView>
 <MotionModal visible={passwordModal} animationType="slide" onRequestClose={()=>{if(!saving)setPasswordModal(false);}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,paddingTop:48,gap:18,flexGrow:1,backgroundColor:c.bg}}><ScreenTitle title="Alterar senha" right={<IconButton name="close" label="Fechar" onPress={()=>setPasswordModal(false)} disabled={saving}/>}/>{error?<ErrorBanner text={error}/>:null}{[{label:'Senha atual',value:current,set:setCurrent},{label:'Nova senha',value:next,set:setNext},{label:'Repita a nova senha',value:confirm,set:setConfirm}].map(f=><View key={f.label}><Text style={[forms.label,{color:c.muted}]}>{f.label}</Text><TextInput accessibilityLabel={f.label} secureTextEntry autoCapitalize="none" value={f.value} onChangeText={f.set} maxLength={200} style={[forms.input,{borderColor:c.line,backgroundColor:c.surface,color:c.text}]}/></View>)}<Text style={{color:c.muted,fontSize:13,lineHeight:21}}>Use 12 caracteres ou mais. A alteração encerra as sessões abertas.</Text><Button title="Salvar nova senha" onPress={()=>void changePassword()} loading={saving}/></ScrollView></MotionModal></>;
}
