import React,{useEffect,useState} from 'react';
import {View,Text,ScrollView,TextInput,Pressable,Modal,Switch,Alert,ActivityIndicator,RefreshControl,Linking,KeyboardAvoidingView,Platform} from 'react-native';
import {SofiaApi,SITE} from '../lib/api';
import type {Catalog,Definition,Entity,Field,Task,Tab} from '../lib/types';
import {useTheme} from '../lib/theme';
import {errorText} from '../lib/chat-model';
import {Icon,IconName} from '../components/Icon';
import {Button,Empty,ErrorBanner,IconButton,ScreenTitle,forms} from '../components/UI';
const states:Record<string,string>={active:'Ativo',archived:'Arquivado',idea:'Ideia',paused:'Pausado',completed:'Concluído',planned:'Planejado',confirmed:'Confirmado',pending:'Pendente',done:'Concluído',todo:'A fazer',cancelled:'Cancelado',draft:'Rascunho',interest:'Interesse',purchased:'Comprado',needed:'Necessário',unavailable:'Indisponível',learning:'Estudando',acquired:'Adquirido',saved:'Salvo',to_watch:'Para assistir',watched:'Assistido',reading:'Lendo',ready:'Pronto',collecting:'Reunindo',questions:'Dúvidas',new:'Novo',waiting:'Aguardando',local:'Somente local',private:'Privado',shared:'Compartilhado',public:'Público',list:'Lista',board:'Quadro',gallery:'Galeria',notes:'Notas',manual:'Manual',json:'Feed autorizado'};
const translated=(v:string)=>states[v]||v;
const modules:{id:string;title:string;caption:string;icon:IconName;kinds?:string[];group?:string}[]=[
 {id:'tasks',title:'Tarefas',caption:'A fazer e prioridades',icon:'check'},
 {id:'pages',title:'Páginas',caption:'Seus espaços e conteúdo',icon:'book',kinds:['user_page']},
 {id:'lists',title:'Listas',caption:'Pessoais, mercado e compras',icon:'list',kinds:['list_collection','list_item','shopping_item','purchase_group','purchase']},
 {id:'library',title:'Biblioteca',caption:'Leituras, referências e arquivos',icon:'book',group:'library'},
 {id:'study',title:'Estudos',caption:'Cursos, aulas e progresso',icon:'edit',group:'study'},
 {id:'monitor',title:'Monitoramentos',caption:'Produtos e preços observados',icon:'monitor',kinds:['monitor','purchase','study_progress']},
 {id:'flow',title:'Projetos e rotina',caption:'Planos, compromissos e ações',icon:'calendar',group:'flow'},
 {id:'knowledge',title:'Ideias e anotações',caption:'Conhecimento da sua Sofia',icon:'edit',group:'knowledge'},
 {id:'connections',title:'Conexões',caption:'Serviços e WhatsApp',icon:'grid'},
 {id:'all',title:'Todos os registros',caption:'Catálogo completo do servidor',icon:'grid'}
];
export function Choice({value,options,onChange,label}:{value:string;options:{value:string;label:string}[];onChange:(v:string)=>void;label:string}){
 const c=useTheme(),[open,setOpen]=useState(false),[query,setQuery]=useState('');
 return <><Pressable onPress={()=>{setQuery('');setOpen(true);}} accessibilityRole="button" accessibilityLabel={label} style={[forms.input,{borderColor:c.line,backgroundColor:c.input,flexDirection:'row',alignItems:'center',gap:12}]}><Text numberOfLines={2} style={{flex:1,color:c.text,fontSize:14}}>{options.find(x=>x.value===value)?.label||value||'Selecionar'}</Text><Icon name="chevron" color={c.muted} size={18}/></Pressable><Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={{flex:1,justifyContent:'flex-end',backgroundColor:'#00000070'}}><View style={{maxHeight:'80%',backgroundColor:c.surface,borderTopLeftRadius:25,borderTopRightRadius:25,padding:20,gap:12}}><View style={{flexDirection:'row',alignItems:'center'}}><Text style={{flex:1,fontSize:20,fontWeight:'600',color:c.text}}>{label}</Text><IconButton name="close" label="Fechar seleção" onPress={()=>setOpen(false)}/></View>{options.length>8?<TextInput value={query} onChangeText={setQuery} placeholder="Buscar" placeholderTextColor={c.muted} style={[forms.input,{borderColor:c.line,color:c.text}]}/>:null}<ScrollView keyboardShouldPersistTaps="handled">{options.filter(o=>o.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(o=><Pressable key={o.value} onPress={()=>{onChange(o.value);setOpen(false);}} style={{minHeight:48,padding:12,borderBottomWidth:1,borderColor:c.line,flexDirection:'row',gap:10,alignItems:'center'}}><Text style={{flex:1,color:c.text,fontSize:15}}>{o.label}</Text>{value===o.value?<Icon name="check" color={c.accent}/>:null}</Pressable>)}</ScrollView></View></View></Modal></>;
}
export function Input({label,value,onChange,multiline=false,placeholder='',keyboardType='default'}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean;placeholder?:string;keyboardType?:'default'|'numeric'|'email-address'|'url'}){
 const c=useTheme();return <View><Text style={[forms.label,{color:c.muted}]}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} multiline={multiline} keyboardType={keyboardType} placeholder={placeholder} placeholderTextColor={c.muted} style={[forms.input,{color:c.text,borderColor:c.line,backgroundColor:c.input,minHeight:multiline?100:52,paddingVertical:12,textAlignVertical:multiline?'top':'center'}]}/></View>;
}
function Blocks({value,onChange}:{value:string;onChange:(v:string)=>void}){
 const c=useTheme();let blocks:any[]=[];let invalid=false;try{const p=JSON.parse(value||'[]');if(!Array.isArray(p))throw Error();blocks=p;}catch{invalid=true;}
 function change(i:number,patch:object){const n=blocks.map((b,j)=>j===i?{...b,...patch}:b);onChange(JSON.stringify(n));}
 function move(i:number,d:number){const n=[...blocks];if(i+d<0||i+d>=n.length)return;[n[i],n[i+d]]=[n[i+d],n[i]];onChange(JSON.stringify(n));}
 if(invalid)return <ErrorBanner text="O conteúdo em blocos está em um formato diferente. Ele será preservado sem alterações."/>;
 return <View style={{gap:12}}><Text style={{fontWeight:'700',fontSize:16,color:c.text}}>Conteúdo da página</Text>{blocks.map((b,i)=><View key={b.id||i} style={{borderWidth:1,borderColor:c.line,padding:12,borderRadius:16,gap:8,backgroundColor:c.surface}}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Text style={{flex:1,color:c.muted,fontSize:11}}>{b.type||'text'}</Text><Pressable onPress={()=>move(i,-1)} style={{padding:8}} accessibilityLabel="Mover bloco para cima"><Text style={{color:c.accent}}>↑</Text></Pressable><Pressable onPress={()=>move(i,1)} style={{padding:8}} accessibilityLabel="Mover bloco para baixo"><Text style={{color:c.accent}}>↓</Text></Pressable><IconButton name="trash" label="Remover bloco" size={36} onPress={()=>Alert.alert('Remover bloco?','A remoção só será aplicada ao salvar a página.',[{text:'Cancelar',style:'cancel'},{text:'Remover',style:'destructive',onPress:()=>onChange(JSON.stringify(blocks.filter((_,j)=>j!==i)))}])}/></View>{b.type==='divider'?<View style={{height:1,backgroundColor:c.line}}/>:null}{b.type==='todo'?<View style={{flexDirection:'row',alignItems:'center'}}><Text style={{flex:1,color:c.text}}>Concluído</Text><Switch value={!!b.checked} onValueChange={v=>change(i,{checked:v})}/></View>:null}{b.type!=='divider'?<TextInput value={String(b.text||'')} onChangeText={t=>change(i,{text:t,html:''})} placeholder="Texto do bloco" placeholderTextColor={c.muted} multiline style={{color:c.text,fontSize:b.type?.startsWith('heading')?21:15,lineHeight:24,minHeight:48,textAlignVertical:'top'}}/>:null}{b.data&&Object.keys(b.data).length?<Text style={{fontSize:11,color:c.muted}}>Links, tabelas e dados adicionais deste bloco são preservados.</Text>:null}</View>)}<Choice label="Adicionar bloco" value="" options={[{value:'text',label:'Parágrafo'},{value:'heading1',label:'Título'},{value:'bullet',label:'Item com marcador'},{value:'todo',label:'Tarefa'},{value:'quote',label:'Citação'},{value:'divider',label:'Divisor'}]} onChange={type=>onChange(JSON.stringify([...blocks,{id:Date.now().toString(36)+Math.random().toString(36).slice(2,7),type,text:''}]))}/></View>;
}
function localDate(value:string){if(!value)return '';const d=new Date(value);if(!Number.isFinite(d.getTime()))return value;return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function FieldInput({field,value,onChange,api}:{field:Field;value:any;onChange:(v:any)=>void;api:SofiaApi}){
 const c=useTheme(),[choices,setChoices]=useState<{value:string;label:string}[]>([]);const relations:Record<string,string[]>={collection_id:['list_collection'],course_id:['course'],target_id:['purchase','course'],parent_id:['user_page']};
 useEffect(()=>{let live=true;const kinds=relations[field.key];if(!kinds)return;Promise.all(kinds.map(k=>api.entities(k))).then(rs=>{if(live)setChoices(rs.flatMap(r=>r.items.map(e=>({value:e.id,label:e.title}))));}).catch(()=>{});return()=>{live=false;};},[field.key,api]);
 if(field.key==='blocks_json')return <Blocks value={value||''} onChange={onChange}/>;
 if(field.type==='checkbox')return <View style={{flexDirection:'row',alignItems:'center',gap:12}}><Text style={{flex:1,color:c.text,fontSize:14,lineHeight:21}}>{field.label}</Text><Switch value={!!value} onValueChange={onChange}/></View>;
 if(field.type==='select'||relations[field.key])return <View><Text style={[forms.label,{color:c.muted}]}>{field.label}</Text><Choice label={field.label} value={String(value||'')} options={[{value:'',label:'Não definido'},...(field.type==='select'?(field.options||[]).map(v=>({value:v,label:translated(v)})):choices)]} onChange={onChange}/></View>;
 return <Input label={field.label} value={String(value??'')} onChange={onChange} multiline={field.type==='textarea'} keyboardType={field.type==='number'?'numeric':field.type==='url'?'url':'default'} placeholder={field.type==='date'?'AAAA-MM-DD':field.type==='datetime'?'AAAA-MM-DD HH:MM':field.type==='time'?'HH:MM':''}/>;
}
export function EntityEditor({api,item,definition,areas,onClose,onSaved}:{api:SofiaApi;item:Partial<Entity>;definition:Definition;areas:string[];onClose:()=>void;onSaved:()=>void}){
 const c=useTheme(),[title,setTitle]=useState(item.title||''),[content,setContent]=useState(item.content||''),[area,setArea]=useState(item.area||'Pessoal'),[privacy,setPrivacy]=useState(item.privacy||'private'),[state,setState]=useState(item.state||definition.states[0]),[tags,setTags]=useState((item.tags||[]).join(', ')),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [data,setData]=useState<Record<string,any>>(()=>{const d={...(item.data||{})};for(const f of definition.fields)if(f.type==='datetime'&&d[f.key])d[f.key]=localDate(d[f.key]);return d;});
 const fields=definition.fields.filter(f=>!(f as any).developerOnly);
 async function save(){if(busy||!title.trim())return;setBusy(true);setError('');try{const packed={...data};for(const f of definition.fields){const v=packed[f.key];if(f.type==='number'&&v!==''&&v!==undefined)packed[f.key]=Number(String(v).replace(',','.'));if(f.type==='datetime'&&v){const d=new Date(String(v).replace(' ','T'));if(!Number.isFinite(d.getTime()))throw new Error(f.label+': use AAAA-MM-DD HH:MM');packed[f.key]=d.toISOString();}}
 await api.saveEntity({...item,title:title.trim(),content,area,state,privacy,tags:tags.split(',').map(x=>x.trim()).filter(Boolean),data:packed});onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 function remove(){Alert.alert('Excluir registro?',`“${item.title}” será removido também do site.`,[{text:'Cancelar',style:'cancel'},{text:'Excluir',style:'destructive',onPress:()=>{setBusy(true);api.deleteEntity(item.id!).then(onSaved).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}]);}
 return <Modal visible animationType="slide" onRequestClose={()=>{if(!busy)onClose();}}><KeyboardAvoidingView style={{flex:1,backgroundColor:c.bg}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={{paddingTop:20,flexDirection:'row',alignItems:'center',paddingHorizontal:12,borderBottomWidth:1,borderColor:c.line}}><IconButton name="close" label="Fechar editor" onPress={onClose} disabled={busy}/><Text numberOfLines={1} style={{flex:1,fontWeight:'700',fontSize:18,color:c.text}}>{item.id?'Editar':'Criar'} · {definition.label}</Text>{item.id?<IconButton name="trash" label="Excluir registro" onPress={remove} disabled={busy}/>:null}</View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:22,gap:18,paddingBottom:35}}>{error?<ErrorBanner text={error}/>:null}<Input label="Título" value={title} onChange={setTitle}/><Input label="Descrição" value={content} onChange={setContent} multiline/><View><Text style={[forms.label,{color:c.muted}]}>Estado</Text><Choice label="Estado" value={state} options={definition.states.map(v=>({value:v,label:translated(v)}))} onChange={setState}/></View><View><Text style={[forms.label,{color:c.muted}]}>Área</Text><Choice label="Área" value={area} options={areas.map(v=>({value:v,label:v}))} onChange={setArea}/></View><View><Text style={[forms.label,{color:c.muted}]}>Privacidade</Text><Choice label="Privacidade" value={privacy} options={(definition.private?['private','local']:['private','local','shared']).map(v=>({value:v,label:translated(v)}))} onChange={setPrivacy}/></View><Input label="Etiquetas separadas por vírgula" value={tags} onChange={setTags}/>{fields.map(f=><FieldInput key={f.key} field={f} value={data[f.key]} onChange={v=>setData(d=>({...d,[f.key]:v}))} api={api}/>)}<Text style={{fontSize:12,color:c.muted,lineHeight:19}}>As alterações usam o mesmo registro do site. Se ele mudar em outro dispositivo, reabra antes de salvar.</Text><Button title="Salvar alterações" loading={busy} disabled={!title.trim()} onPress={()=>void save()}/></ScrollView></KeyboardAvoidingView></Modal>;
}
function Tasks({api,onBack}:{api:SofiaApi;onBack:()=>void}){
 const c=useTheme(),[items,setItems]=useState<Task[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState<Partial<Task>|null>(null),[saving,setSaving]=useState(false),[query,setQuery]=useState('');
 async function load(){setLoading(true);try{setItems((await api.tasks()).items);setError('');}catch(e){setError(errorText(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[api]);
 async function save(){if(!editing?.title?.trim())return;setSaving(true);try{await api.saveTask({...editing,due_at:editing.due_at?new Date(editing.due_at.replace(' ','T')).toISOString():''});setEditing(null);await load();}catch(e){setError(errorText(e));}finally{setSaving(false);}}
 return <View style={{flex:1}}><ScreenTitle title="Tarefas" right={<View style={{flexDirection:'row'}}><IconButton name="back" label="Voltar aos apps" onPress={onBack}/><IconButton name="plus" label="Nova tarefa" onPress={()=>setEditing({title:'',state:'todo',priority:2,area:'Pessoal'})}/></View>}/><TextInput value={query} onChangeText={setQuery} placeholder="Buscar tarefa" placeholderTextColor={c.muted} style={[forms.input,{marginHorizontal:22,color:c.text,borderColor:c.line}]}/>{error?<ErrorBanner text={error}/>:null}<ScrollView contentContainerStyle={{padding:22,gap:10}} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void load()}/>}>
 {items.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())).map(t=><View key={t.id} style={{flexDirection:'row',alignItems:'center',gap:8,borderRadius:18,backgroundColor:c.surface,padding:12,borderWidth:1,borderColor:c.line}}><Pressable onPress={()=>{api.taskState(t,t.state==='done'?'todo':'done').then(load).catch(e=>setError(errorText(e)));}} accessibilityRole="checkbox" accessibilityState={{checked:t.state==='done'}} style={{minWidth:42,minHeight:46,alignItems:'center',justifyContent:'center'}}><Icon name={t.state==='done'?'check':'calendar'} color={c.accent}/></Pressable><Pressable onPress={()=>setEditing({...t,due_at:localDate(t.due_at||'')})} style={{flex:1,gap:6,paddingVertical:10}}><Text style={{fontSize:15,color:c.text,textDecorationLine:t.state==='done'?'line-through':'none'}}>{t.title}</Text><Text style={{fontSize:11,color:c.muted}}>{t.area||'Pessoal'}{t.due_at?' · '+new Date(t.due_at).toLocaleDateString('pt-BR'):''}</Text></Pressable><Icon name="edit" color={c.muted} size={18}/></View>)}{!items.length&&!loading?<Empty icon="check" title="Sua lista começa aqui" body="Toque no + para criar uma tarefa. Ela também aparece no site."/>:null}</ScrollView>
 {editing?<Modal visible animationType="slide" onRequestClose={()=>setEditing(null)}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,paddingTop:50,gap:18,flexGrow:1,backgroundColor:c.bg}}><ScreenTitle title={editing.id?'Editar tarefa':'Nova tarefa'} right={<IconButton name="close" label="Fechar" onPress={()=>setEditing(null)}/>}/>{error?<ErrorBanner text={error}/>:null}<Input label="Título" value={editing.title||''} onChange={v=>setEditing(t=>({...t,title:v}))}/><Input label="Data e hora (opcional)" value={editing.due_at||''} placeholder="AAAA-MM-DD HH:MM" onChange={v=>setEditing(t=>({...t,due_at:v}))}/><Input label="Área" value={editing.area||'Pessoal'} onChange={v=>setEditing(t=>({...t,area:v}))}/><Choice label="Prioridade" value={String(editing.priority??2)} onChange={v=>setEditing(t=>({...t,priority:Number(v)}))} options={[{value:'1',label:'Alta'},{value:'2',label:'Normal'},{value:'3',label:'Baixa'}]}/><Button title="Salvar tarefa" loading={saving} onPress={()=>void save()}/>{editing.id?<Button title="Excluir tarefa" secondary onPress={()=>Alert.alert('Excluir tarefa?','Esta ação também remove a tarefa do site.',[{text:'Cancelar',style:'cancel'},{text:'Excluir',style:'destructive',onPress:()=>{api.deleteTask(editing.id!).then(()=>{setEditing(null);return load();}).catch(e=>setError(errorText(e)));}}])}/>:null}</ScrollView></Modal>:null}</View>;
}
export function Workspace({api,navigate}:{api:SofiaApi;navigate:(tab:Tab)=>void}){
 const c=useTheme(),[catalog,setCatalog]=useState<Catalog|null>(null),[module,setModule]=useState(''),[kind,setKind]=useState(''),[items,setItems]=useState<Entity[]>([]),[editing,setEditing]=useState<Partial<Entity>|null>(null),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[error,setError]=useState(''),[integrations,setIntegrations]=useState<any[]>([]);
 useEffect(()=>{api.catalog().then(setCatalog).catch(e=>setError(errorText(e)));},[api]);
 async function load(more=false){if(!kind)return;setLoading(true);try{const result=await api.entities(kind,query,more?items.length:0);setItems(p=>more?[...p,...result.items]:result.items);setError('');}catch(e){setError(errorText(e));}finally{setLoading(false);}}
 useEffect(()=>{if(!kind)return;const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t);},[kind,query,api]);
 const selected=modules.find(m=>m.id===module),definitions=catalog?.catalog||{},kinds=Object.keys(definitions).filter(k=>!selected?.kinds||selected.kinds.includes(k)).filter(k=>!selected?.group||definitions[k].group===selected.group);
 function choose(id:string){setQuery('');setError('');setModule(id);const m=modules.find(x=>x.id===id);if(id==='connections'){setKind('');api.integrations().then(r=>setIntegrations(r.items)).catch(e=>setError(errorText(e)));return;}if(id==='tasks'){setKind('');return;}const k=Object.keys(definitions).filter(k=>!m?.kinds||m.kinds.includes(k)).filter(k=>!m?.group||definitions[k].group===m.group);setKind(k[0]||'');setItems([]);}
 if(module==='tasks')return <Tasks api={api} onBack={()=>setModule('')}/>;
 return <View style={{flex:1}}><ScreenTitle title={selected?.title||'Seus espaços'} eyebrow="UMA CONTA · MESMOS DADOS" right={module?<View style={{flexDirection:'row'}}><IconButton name="back" label="Voltar aos apps" onPress={()=>{setModule('');setKind('');setEditing(null);}}/>{kind?<IconButton name="plus" label="Criar registro" onPress={()=>setEditing({kind,title:'',data:{}})}/>:null}</View>:<IconButton name="bell" label="Abrir notificações" onPress={()=>navigate('notifications')}/>}/>{error?<ErrorBanner text={error}/>:null}
 {!module?<ScrollView contentContainerStyle={{paddingHorizontal:22,paddingBottom:24,gap:14}}><Text style={{fontSize:14,lineHeight:22,color:c.muted,marginBottom:5}}>Tudo se conecta à estrutura da sua Sofia. Crie no celular e continue no computador.</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}>{modules.map(m=><Pressable key={m.id} disabled={!catalog} onPress={()=>choose(m.id)} style={{width:'47.5%',minHeight:135,padding:18,gap:12,borderRadius:22,borderWidth:1,borderColor:c.line,backgroundColor:c.surface}}><Icon name={m.icon} color={c.accent} size={25}/><Text style={{color:c.text,fontWeight:'700',fontSize:15}}>{m.title}</Text><Text style={{color:c.muted,fontSize:12,lineHeight:18}}>{m.caption}</Text></Pressable>)}</View>{!catalog?<ActivityIndicator color={c.accent}/>:null}<Pressable onPress={()=>navigate('profile')} style={{padding:18,borderRadius:20,backgroundColor:c.accentSoft,flexDirection:'row',gap:14,alignItems:'center'}}><Icon name="user" color={c.accent}/><Text style={{color:c.accent,fontWeight:'600'}}>Perfil, aparência e segurança</Text></Pressable></ScrollView>:
 module==='connections'?<ScrollView contentContainerStyle={{padding:22,gap:12}}>{integrations.map(i=><View key={i.key} style={{padding:20,gap:12,borderRadius:20,backgroundColor:c.surface,borderWidth:1,borderColor:c.line}}><Text style={{fontSize:17,fontWeight:'700',color:c.text}}>{i.name}</Text><Text style={{fontSize:11,color:c.accent}}>{i.status}</Text><Text style={{fontSize:14,lineHeight:22,color:c.muted}}>{i.description}</Text>{i.connect_url?<Button title="Abrir conexão oficial" secondary onPress={()=>void Linking.openURL(i.connect_url)}/>:null}</View>)}</ScrollView>:
 <><View style={{paddingHorizontal:22,gap:12,paddingBottom:10}}><Choice label="Tipo de registro" value={kind} options={kinds.map(k=>({value:k,label:definitions[k].label}))} onChange={k=>{setItems([]);setKind(k);}}/><TextInput value={query} onChangeText={setQuery} placeholder="Buscar nesta categoria" placeholderTextColor={c.muted} style={[forms.input,{borderColor:c.line,color:c.text,backgroundColor:c.surface}]}/></View><ScrollView contentContainerStyle={{padding:22,gap:12,paddingTop:8}} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void load()}/>}>
 {items.map(e=><Pressable key={e.id} onPress={()=>setEditing(e)} style={{padding:18,gap:9,borderRadius:20,backgroundColor:c.surface,borderWidth:1,borderColor:c.line}}><View style={{flexDirection:'row',gap:12,alignItems:'center'}}><Text style={{flex:1,color:c.text,fontSize:16,fontWeight:'600'}}>{e.title}</Text><Icon name="edit" size={17} color={c.muted}/></View>{e.content?<Text numberOfLines={3} style={{color:c.muted,fontSize:13,lineHeight:20}}>{e.content}</Text>:null}<Text style={{color:c.accent,fontSize:11}}>{translated(e.state)} · {e.area}</Text></Pressable>)}{!items.length&&!loading?<Empty icon="grid" title="Nenhum registro aqui" body="Use o + no topo para criar. O conteúdo será salvo na mesma base do site."/>:null}{items.length>=100&&items.length%100===0?<Button title="Carregar mais" secondary onPress={()=>void load(true)}/>:null}</ScrollView></>}
 {editing&&catalog&&definitions[editing.kind||'']?<EntityEditor api={api} item={editing} definition={definitions[editing.kind!]} areas={catalog.areas} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);void load();}}/>:null}</View>;
}
