'use strict';
const {OWNER}=require('../memory/store');
const {AppError,validId}=require('../core/util');
const TIME=/^([01]\d|2[0-3]):[0-5]\d$/;
function day(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+'T12:00:00Z'))||new Date(value+'T12:00:00Z').toISOString().slice(0,10)!==value)throw new AppError('BAD_DATE','Escolha uma data válida.');return value;}
function validateCapsule(data){let times;try{times=JSON.parse(data.times_json);}catch{throw new AppError('BAD_CAPSULE_TIMES','Selecione os horários das doses.');}if(!Array.isArray(times)||times.length<1||times.length>8||times.some(t=>typeof t!=='string'||!TIME.test(t))||new Set(times).size!==times.length)throw new AppError('BAD_CAPSULE_TIMES','Use de 1 a 8 horários distintos no formato HH:MM.');data.times_json=JSON.stringify(times.sort());data.repeat_type=data.repeat_type||'daily';if(!['daily','once','weekdays','interval','monthly','yearly'].includes(data.repeat_type))throw new AppError('BAD_REPEAT','Escolha uma repetição válida.');if(data.repeat_type==='weekdays'){let days;try{days=JSON.parse(data.weekdays_json);}catch{}if(!Array.isArray(days)||!days.length||days.some(d=>!Number.isInteger(d)||d<0||d>6)||new Set(days).size!==days.length)throw new AppError('BAD_REPEAT','Selecione os dias da semana.');data.weekdays_json=JSON.stringify(days.sort());}if(data.repeat_type==='interval'&&(!Number.isInteger(data.interval_days)||data.interval_days<1||data.interval_days>365))throw new AppError('BAD_REPEAT','Use um intervalo de 1 a 365 dias.');if(!data.start_date)throw new AppError('BAD_DATE','Selecione o primeiro dia.');if(data.end_date&&data.end_date<data.start_date)throw new AppError('BAD_DATE','O último dia deve ser igual ou posterior ao primeiro.');if(!Number.isInteger(data.remind_minutes)||data.remind_minutes<0||data.remind_minutes>1440)throw new AppError('BAD_REMINDER','Use de 0 a 1440 minutos de antecedência.');}
function capsuleOccurs(data,day){
 const start=data.start_date;if(!start||day<start||(data.end_date&&day>data.end_date))return false;
 const date=new Date(day+'T12:00:00Z'),anchor=new Date(start+'T12:00:00Z');if(!Number.isFinite(date.getTime())||!Number.isFinite(anchor.getTime()))return false;
 const mode=data.repeat_type||'daily';
 if(mode==='once')return day===start;
 if(mode==='weekdays'){try{return JSON.parse(data.weekdays_json||'[]').includes(date.getUTCDay());}catch{return false;}}
 if(mode==='interval')return Math.round((date.getTime()-anchor.getTime())/86400000)%Math.max(1,Number(data.interval_days)||1)===0;
 const last=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,0)).getUTCDate();
 if(mode==='monthly')return date.getUTCDate()===Math.min(anchor.getUTCDate(),last);
 if(mode==='yearly')return date.getUTCMonth()===anchor.getUTCMonth()&&date.getUTCDate()===Math.min(anchor.getUTCDate(),last);
 return mode==='daily';
}
class Capsules {
 constructor(store,workspace){this.store=store;this.workspace=workspace;store.db.exec("CREATE UNIQUE INDEX IF NOT EXISTS capsule_dose_once ON entities(owner,json_extract(data,'$.capsule_id'),json_extract(data,'$.day'),json_extract(data,'$.time')) WHERE kind='capsule_dose'");}
 history(from,to){day(from);day(to);if(to<from||Date.parse(to)-Date.parse(from)>366*86400000)throw new AppError('BAD_DATE','Consulte até um ano por vez.');return this.store.db.prepare("SELECT id FROM entities WHERE owner=? AND kind='capsule_dose' AND json_extract(data,'$.day')>=? AND json_extract(data,'$.day')<=? ORDER BY json_extract(data,'$.day') DESC,json_extract(data,'$.time') DESC").all(OWNER,from,to).map(r=>this.workspace.get(r.id));}
 take({capsule_id,day:date,time,taken=true}){validId(capsule_id);day(date);if(!TIME.test(time)||typeof taken!=='boolean')throw new AppError('BAD_DOSE','Dose inválida.');return this.store.tx(()=>{const plan=this.workspace.get(capsule_id);if(plan.kind!=='capsule')throw new AppError('BAD_KIND','Selecione uma cápsula.');const existing=this.store.db.prepare("SELECT id FROM entities WHERE owner=? AND kind='capsule_dose' AND json_extract(data,'$.capsule_id')=? AND json_extract(data,'$.day')=? AND json_extract(data,'$.time')=?").get(OWNER,capsule_id,date,time);if(!taken){if(existing)this.workspace.deleteEntity(existing.id);return {ok:true,item:null};}if(existing)return {ok:true,item:this.workspace.get(existing.id)};if(plan.state!=='active'||!capsuleOccurs(plan.data,date)||!JSON.parse(plan.data.times_json).includes(time))throw new AppError('BAD_DOSE','Esta dose não faz parte da rotina ativa.');const today=new Intl.DateTimeFormat('en-CA',{timeZone:this.store.settings().timezone||'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(date>today)throw new AppError('FUTURE_DOSE','Só marque doses de hoje ou de dias anteriores.');return {ok:true,item:this.workspace.save({kind:'capsule_dose',title:plan.title,content:plan.content,area:plan.area,state:'done',privacy:'private',data:{capsule_id,day:date,time,taken_at:new Date().toISOString(),dose_text:plan.data.dose_text||''}})};});}
}
module.exports={Capsules,validateCapsule,capsuleOccurs};
