'use strict';
const {readFeed}=require('./safe-feed');const {AppError,normalize}=require('../core/util');const {httpsFetch}=require('./http-client');
function productsFromHTML(html){const out=[];function visit(v){if(Array.isArray(v)){v.forEach(visit);return;}if(!v||typeof v!=='object')return;const types=Array.isArray(v['@type'])?v['@type']:[v['@type']];if(types.includes('Product'))out.push(v);if(v['@graph'])visit(v['@graph']);if(v.mainEntity)visit(v.mainEntity);}
 for(const m of String(html).matchAll(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{visit(JSON.parse(m[1]));}catch{}}
 return out;
}
function comparable(a,b){for(const key of ['gtin','gtin13','gtin12','gtin14'])if(a[key]&&b[key])return String(a[key])===String(b[key]);const x=normalize(a.name||''),y=normalize(b.name||'');if(x===y&&x.length>4)return true;const nums=s=>(s.match(/\b[\w-]*\d[\w-]*\b/g)||[]).sort().join('|');if(nums(x)!==nums(y))return false;const words=x.split(/\W+/).filter(v=>v&&!['de','da','do','com','the','and','e','para'].includes(v));return words.length>=3&&words.every(w=>y.split(/\W+/).includes(w));}
function quote(product,currency){const offers=Array.isArray(product.offers)?product.offers:[product.offers];for(const offer of offers){if(!offer||!['Offer','https://schema.org/Offer'].includes(offer['@type']||'Offer'))continue;if(offer.availability&& !/InStock$/.test(offer.availability))continue;const raw=offer.price??offer.priceSpecification?.price;const price=Number(raw);if(raw!==''&&Number.isFinite(price)&&price>0&&price<=1e8&&offer.priceCurrency===currency)return {price,shipping:0};}return null;}
async function discover(product,config,{signal,fetcher=httpsFetch}={}){const key=config.privateApiKey||config.apiKey;if(!key)return [];const res=await fetcher('https://api.openai.com/v1/responses',{method:'POST',signal:AbortSignal.any([signal||new AbortController().signal,AbortSignal.timeout(45000)]),headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:config.model,store:false,max_output_tokens:1600,tools:[{type:'web_search'}],include:['web_search_call.action.sources'],input:'Pesquise lojas no Brasil vendendo exatamente este produto e variante: '+String(product.name).slice(0,300)+'. Retorne somente JSON {"urls":[até 5 URLs HTTPS das páginas de compra do produto]}. Não inclua preço, anúncios genéricos, busca, afiliados nem variantes diferentes.'})});if(!res.ok)throw new AppError('PRODUCT_SEARCH_UNAVAILABLE','Busca de lojas indisponível.');const body=await res.json(),sources=new Set(),texts=[];for(const o of body.output||[]){for(const s of o.action?.sources||[])if(s.url)sources.add(s.url);for(const c of o.content||[]){if(c.text)texts.push(c.text);for(const a of c.annotations||[])if(a.url)sources.add(a.url);}}
 try{const text=texts.join(''),json=JSON.parse(text.slice(text.indexOf('{'),text.lastIndexOf('}')+1));return (json.urls||[]).filter(u=>typeof u==='string'&&sources.has(u)&&u.startsWith('https://')).slice(0,5);}catch{return [];}}
async function collect(workspace,monitor,{stamp=new Date().toISOString(),signal,config={},reader=readFeed,search=discover}={}){
 const d=monitor.data,url=d.preferred_url;let reference={name:d.variant},preferredError=null;
 try{const html=await reader(url,{signal,format:'html'}),products=productsFromHTML(html);const wanted=normalize(d.variant);reference=products.find(p=>normalize(p.name)===wanted)||products.find(p=>comparable({name:d.variant},p));if(!reference)throw new AppError('PRODUCT_UNVERIFIED','Não foi possível confirmar o modelo e a variante no link principal.');const first=quote(reference,d.currency);if(!first)throw new AppError('PRICE_UNAVAILABLE','A loja principal não publicou preço e moeda verificáveis para esta variante.');workspace.observe(monitor.id,{...first,variant:d.variant,currency:d.currency,source:url,source_key:require('node:crypto').createHash('sha256').update(url+stamp).digest('hex'),observed_at:stamp});}catch(e){preferredError=e;reference={name:d.variant};}

 workspace.db.exec('CREATE TABLE IF NOT EXISTS product_sources(monitor_id TEXT NOT NULL,url TEXT NOT NULL,last_checked TEXT,last_error TEXT,PRIMARY KEY(monitor_id,url));CREATE TABLE IF NOT EXISTS product_discovery(monitor_id TEXT PRIMARY KEY,last_at TEXT NOT NULL);');
 const cached=workspace.db.prepare('SELECT url FROM product_sources WHERE monitor_id=?').all(monitor.id).map(x=>x.url);const last=workspace.db.prepare('SELECT last_at FROM product_discovery WHERE monitor_id=?').get(monitor.id);let found=[];
 if(d.discover&&(!last||Date.parse(stamp)-Date.parse(last.last_at)>=86400000)){try{found=await search(reference,config,{signal});workspace.db.prepare('INSERT OR REPLACE INTO product_discovery VALUES (?,?)').run(monitor.id,stamp);}catch{workspace.notify('price',monitor.title+' — busca de lojas pendente','O link principal foi consultado. A busca de outras lojas será tentada novamente.',monitor.id,'info',monitor.id+':discovery:'+stamp.slice(0,10));}}
 const candidates=[...new Set([...String(d.comparison_urls||'').split(/\n/).map(x=>x.trim()).filter(Boolean),...cached,...found])].filter(u=>u!==url).slice(0,8);
 for(const other of candidates){if(signal?.aborted)break;let error=null;try{const page=await reader(other,{signal,format:'html'}),product=productsFromHTML(page).find(p=>comparable(reference,p));if(!product)throw new AppError('VARIANT_MISMATCH','Variante diferente');const value=quote(product,d.currency);if(!value)throw new AppError('PRICE_UNAVAILABLE','Preço indisponível');workspace.observe(monitor.id,{...value,variant:d.variant,currency:d.currency,source:other,source_key:require('node:crypto').createHash('sha256').update(other+stamp).digest('hex'),observed_at:stamp});}catch(e){error=e.code||'SOURCE_UNAVAILABLE';}workspace.db.prepare('INSERT INTO product_sources VALUES (?,?,?,?) ON CONFLICT(monitor_id,url) DO UPDATE SET last_checked=excluded.last_checked,last_error=excluded.last_error').run(monitor.id,other,stamp,error);await new Promise(r=>setImmediate(r));}
 if(preferredError)throw preferredError;
 return {preferred:true,checked:candidates.length+1};
}
module.exports={productsFromHTML,comparable,quote,discover,collect};
