'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {KeyStore}=require('./backup');
const {AppError,atomicWrite,id,now,cleanText,rejectSecrets}=require('../core/util');
const {OWNER}=require('../memory/store');
const ALPH='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function base32(bytes){let bits=0,value=0,out='';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){out+=ALPH[(value>>>(bits-5))&31];bits-=5;}}if(bits)out+=ALPH[(value<<(5-bits))&31];return out;}
function unbase32(text){let value=0,bits=0,out=[];for(const c of text.toUpperCase().replace(/=+$/,'')){const p=ALPH.indexOf(c);if(p<0)throw new Error('base32');value=(value<<5)|p;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
function totp(secret,counter){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(counter));const h=crypto.createHmac('sha1',unbase32(secret)).update(b).digest(),o=h.at(-1)&15;return ((h.readUInt32BE(o)&0x7fffffff)%1000000).toString().padStart(6,'0');}
class VaultService{
 constructor(store,{secureDir,clock=()=>Date.now()}={}){this.s=store;this.db=store.db;this.clock=clock;this.keys=new KeyStore(secureDir);this.master=null;this.grants=new Map();this.pending=null;}
 file(){return path.join(this.keys.directory,process.platform==='win32'?'meditations-v1.dpapi':'meditations-v1.key');}
 key(){if(this.master)return this.master;const f=this.file();if(fs.existsSync(f)){const bytes=fs.readFileSync(f);this.master=process.platform==='win32'?this.keys.dpapi(bytes,false):bytes;}else{if(this.state('initialized'))throw new AppError('VAULT_KEY_MISSING','A chave do cofre não está neste usuário. Restaure um backup portátil completo.',409);this.importKey(crypto.randomBytes(32));}if(this.master.length!==32)throw new AppError('VAULT_KEY','Chave do cofre inválida.');return this.master;}
 importKey(key){if(!Buffer.isBuffer(key)||key.length!==32)throw new AppError('VAULT_KEY','Chave de recuperação inválida.');atomicWrite(this.file(),process.platform==='win32'?this.keys.dpapi(key,true):key);this.master=key;this.grants.clear();}
 exportKey(){return this.state('initialized')?this.key().toString('base64'):null;}
 state(k){const r=this.db.prepare('SELECT value FROM vault_state WHERE key=?').get(k);return r?JSON.parse(r.value):null;}
 set(k,v){this.db.prepare('INSERT INTO vault_state VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,JSON.stringify(v));}
 encrypt(value,aad){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',this.key(),iv);c.setAAD(Buffer.from(aad));const out=Buffer.concat([c.update(Buffer.from(JSON.stringify(value))),c.final()]);return {iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),ciphertext:out.toString('base64')};}
 decrypt(e,aad){try{const d=crypto.createDecipheriv('aes-256-gcm',this.key(),Buffer.from(e.iv,'base64'));d.setAAD(Buffer.from(aad));d.setAuthTag(Buffer.from(e.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(e.ciphertext,'base64')),d.final()]).toString());}catch{throw new AppError('VAULT_DECRYPT','Não foi possível abrir esta entrada. Confira a chave/restauração; nenhum conteúdo foi exibido.');}}
 status(){return {initialized:Boolean(this.state('initialized')),count:this.db.prepare('SELECT COUNT(*) n FROM vault_entries').get().n,encrypted:true,setup_method:'manual-authenticator',notice:'Safe Chat: conteúdo armazenado de forma criptografada. Leitura exige código. Proteção local não substitui a segurança do Windows.'};}
 setup(){if(this.state('initialized'))throw new AppError('ALREADY_SETUP','O cofre já está configurado.');const secret=base32(crypto.randomBytes(20));this.key();this.pending={secret,until:this.clock()+10*60000};return {secret,issuer:'Sofia OS',account:'Safe Chat',digits:6,period:30,notice:'No Authenticator: adicionar chave de configuração, tipo baseado no tempo. Não envie este segredo ao chat.'};}
 verifyCode(secret,code,last=-1){if(typeof code!=='string'||!/^\d{6}$/.test(code))return -1;const counter=Math.floor(this.clock()/30000);for(let i=-1;i<=1;i++){const at=counter+i;if(at>last&&crypto.timingSafeEqual(Buffer.from(totp(secret,at)),Buffer.from(code)))return at;}return -1;}
 rate(){const locked=this.state('locked_until')||0;if(locked>this.clock())throw new AppError('VAULT_RATE','Muitas tentativas. Aguarde cinco minutos.',429);}
 failure(){const n=(this.state('failures')||0)+1;this.set('failures',n);if(n>=5){this.set('locked_until',this.clock()+300000);this.set('failures',0);}throw new AppError('VAULT_CODE','Código inválido, expirado ou já utilizado.',403);}
 confirm(code){this.rate();if(!this.pending||this.pending.until<this.clock())throw new AppError('SETUP_EXPIRED','Reabra a configuração do Authenticator.');const counter=this.verifyCode(this.pending.secret,code);if(counter<0)return this.failure();const recovery=crypto.randomBytes(24).toString('hex');this.s.tx(()=>{this.set('secret',this.encrypt({secret:this.pending.secret},'totp'));this.set('last_counter',counter);this.set('recovery_hash',crypto.createHash('sha256').update(recovery).digest('hex'));this.set('initialized',true);this.set('failures',0);});this.pending=null;return {...this.grant(),recovery,notice:'Guarde este código de recuperação fora do computador. Ele é exibido uma única vez.'};}
 grant(){const grant=crypto.randomBytes(32).toString('hex'),expires=this.clock()+5*60000;this.grants.set(grant,expires);return {grant,expires_at:new Date(expires).toISOString()};}
 unlock(code){this.rate();if(!this.state('initialized'))throw new AppError('NOT_SETUP','Configure o cofre primeiro.');const secret=this.decrypt(this.state('secret'),'totp').secret,at=this.verifyCode(secret,code,this.state('last_counter')??-1);if(at<0)return this.failure();this.set('last_counter',at);this.set('failures',0);return this.grant();}
 require(grant){const until=this.grants.get(grant);if(!until||until<this.clock()){this.grants.delete(grant);throw new AppError('VAULT_LOCKED','O cofre está bloqueado. Informe um novo código do Authenticator.',403);}}
 lock(){this.grants.clear();return {locked:true};}
 recover(code){this.rate();if(typeof code!=='string'||code.length!==48)return this.failure();const stored=this.state('recovery_hash'),got=crypto.createHash('sha256').update(code).digest('hex');if(!stored||!crypto.timingSafeEqual(Buffer.from(stored),Buffer.from(got)))return this.failure();this.grants.clear();this.set('recovery_hash',null);this.set('initialized',false);this.set('failures',0);return this.setup();}
 add({title,content,previous_id,category='Diário Pessoal',role='entry',session_id=null,labels=[],source_channel='local'},grant){if(!this.state('initialized'))throw new AppError('NOT_SETUP','Configure o cofre primeiro.');title=cleanText(title||'Diário Pessoal','Título',160);content=cleanText(content,'Conteúdo protegido',20000);rejectSecrets(content);category=cleanText(category||'Diário Pessoal','Categoria',80);role=cleanText(role||'entry','Papel',40);if(!['entry','user','assistant'].includes(role))throw new AppError('BAD_VAULT_ROLE','Papel inválido.');if(!Array.isArray(labels)||labels.length>20)throw new AppError('BAD_LABELS','Labels inválidas.');labels=labels.map(x=>cleanText(String(x),'Label',60));let revision=1;if(previous_id){this.require(grant);const old=this.entry(previous_id,grant);revision=old.revision+1;}const eid=id(),e=this.encrypt({title,content,category,role,session_id,labels,source_channel},eid);this.db.prepare('INSERT INTO vault_entries VALUES(?,?,?,?,?,?,?,?)').run(eid,OWNER,e.iv,e.tag,e.ciphertext,revision,previous_id||null,now());this.db.prepare('INSERT OR REPLACE INTO vault_meta VALUES(?,?,?,?,?,?)').run(eid,category,role,session_id,JSON.stringify(labels),source_channel);this.s.audit('vault.added',eid);return {id:eid,revision,saved:true,encrypted:true,category,role,session_id};}
 entry(eid,grant){this.require(grant);const e=this.db.prepare('SELECT * FROM vault_entries WHERE id=? AND owner=?').get(eid,OWNER);if(!e)throw new AppError('NOT_FOUND','Entrada não encontrada.',404);return {id:e.id,revision:e.revision,previous_id:e.previous_id,created_at:e.created_at,...this.decrypt(e,e.id)};}
 list(grant){this.require(grant);return this.db.prepare('SELECT id FROM vault_entries WHERE owner=? ORDER BY created_at DESC,rowid DESC LIMIT 200').all(OWNER).map(e=>this.entry(e.id,grant));}
 recent(grant,limit=8){this.require(grant);limit=Math.max(1,Math.min(20,Number(limit)||8));return this.db.prepare('SELECT id FROM vault_entries WHERE owner=? ORDER BY created_at DESC,rowid DESC LIMIT ?').all(OWNER,limit).reverse().map(e=>this.entry(e.id,grant));}
 autoCategory(text){const n=String(text||'').toLowerCase();if(/medita|reflex|hermet|ego|espiritual/.test(n))return 'Meditação';if(/meu dia|hoje eu|aconteceu|senti|estou me sentindo|desabafo/.test(n))return 'Diário Pessoal';return 'Registro Protegido';}
}
module.exports={VaultService,totp,base32,unbase32};
