'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Store}=require('../src/memory/store'),{Workspace}=require('../src/core/workspace'),{installFields}=require('../src/core/md-api'),{GoogleCalendarSync}=require('../src/services/google-calendar-sync');
function fixture(t){installFields();const store=new Store(':memory:'),workspace=new Workspace(store),state={events:[{id:'series',etag:'master1',recurrence:['RRULE:FREQ=WEEKLY'],summary:'Série',start:{dateTime:'2026-10-03T12:00:00Z'},end:{dateTime:'2026-10-03T13:00:00Z'}}],instances:[],calls:[],pages:false,fail:false};
 const sync=new GoogleCalendarSync({store,workspace,config:{publicBaseUrl:'https://sofia.example'}},{env:{GOOGLE_CALENDAR_CLIENT_ID:'test',GOOGLE_CALENDAR_CLIENT_SECRET:'test',SOFIA_CALENDAR_TOKEN_KEY:Buffer.alloc(32,7).toString('base64')},fetchImpl:async(url,opt={})=>{const u=new URL(url);state.calls.push({u,method:opt.method||'GET'});assert.equal(opt.method||'GET','GET','Import must never rewrite a Google occurrence');let result;
 if(u.pathname.endsWith('/instances')){if(state.fail)return new Response('{}',{status:503});assert.ok(u.searchParams.get('timeMin'));assert.ok(u.searchParams.get('timeMax'));assert.equal(u.searchParams.has('syncToken'),false);result=state.pages?(u.searchParams.has('pageToken')?{items:state.instances.slice(1)}:{items:state.instances.slice(0,1),nextPageToken:'next'}):{items:state.instances};}
 else result={items:state.events,nextSyncToken:'token'};return new Response(JSON.stringify(result));}});
 sync.schedule=()=>{};sync.write({access_token:'test',refresh_token:'test',expires_at:Date.now()+3600000,account_key:'test',meta:{calendar_id:'test@example.test'}});t.after(()=>{sync.close();store.close();});return {store,workspace,sync,state};}
const occurrence=(id,start,extra={})=>({id,etag:id+'1',recurringEventId:'series',originalStartTime:{dateTime:start},summary:'Reunião',start:{dateTime:start,timeZone:'America/Sao_Paulo'},end:{dateTime:new Date(Date.parse(start)+3600000).toISOString()},...extra});
test('Google expands paginated occurrences using actual timezone-adjusted times and all-day exclusive end',async t=>{const f=fixture(t);f.state.pages=true;f.state.instances=[occurrence('a','2026-10-03T09:00:00-03:00'),occurrence('b','2026-10-10T09:00:00-03:00',{start:{date:'2026-10-10'},end:{date:'2026-10-12'}})];await f.sync.sync();const items=f.workspace.list({kind:'commitment'});assert.equal(items.length,2);const a=items.find(e=>e.data.external_event_id==='a'),b=items.find(e=>e.data.external_event_id==='b');assert.equal(a.data.start_at,'2026-10-03T12:00:00.000Z');assert.equal(a.data.calendar_recurring_id,'series');assert.equal(b.data.calendar_all_day,true);assert.equal(b.data.calendar_date_end,'2026-10-12');assert.equal(f.sync.status().warnings.length,0);});
test('changed exception retains local ID; cancelled exception and removed rule instances disappear without deleting history',async t=>{const f=fixture(t);f.state.instances=[occurrence('a','2026-10-03T12:00:00Z'),occurrence('b','2026-10-10T12:00:00Z')];await f.sync.sync();const a=f.workspace.list({kind:'commitment'}).find(e=>e.data.external_event_id==='a');f.state.events[0].etag='master2';f.state.instances=[occurrence('a','2026-10-04T15:00:00Z',{etag:'a2',summary:'Mudou'}),{id:'b',recurringEventId:'series',status:'cancelled',originalStartTime:{dateTime:'2026-10-10T12:00:00Z'}}];await f.sync.sync();assert.equal(f.workspace.get(a.id).title,'Mudou');assert.equal(f.workspace.list({kind:'commitment'}).find(e=>e.data.external_event_id==='b').state,'cancelled');f.state.events[0].etag='master3';f.state.instances=[];await f.sync.sync();assert.equal(f.workspace.get(a.id).state,'cancelled');});
test('failed page never reconciles away existing occurrences; unchanged series avoids repeated expansion',async t=>{const f=fixture(t);f.state.instances=[occurrence('a','2026-10-03T12:00:00Z')];await f.sync.sync();const count=f.state.calls.length;await f.sync.sync();assert.equal(f.state.calls.slice(count).filter(c=>c.u.pathname.endsWith('/instances')).length,0);f.state.events[0].etag='master2';f.state.fail=true;await assert.rejects(f.sync.sync());assert.equal(f.workspace.list({kind:'commitment'})[0].state,'confirmed');});
test('browsing an arbitrary future month fetches real instances beyond initial window',async t=>{const f=fixture(t);await f.sync.sync();await f.sync.ensureMonth('2035-06');assert.ok(f.state.calls.some(c=>c.u.searchParams.get('timeMin')?.startsWith('2035-05')));await assert.rejects(f.sync.ensureMonth('2035-19'),e=>e.code==='BAD_DATE');});
test('Google cancelled master cancels all its imported occurrences while retaining records',async t=>{const f=fixture(t);f.state.instances=[occurrence('a','2026-10-03T12:00:00Z')];await f.sync.sync();f.state.events=[{id:'series',status:'cancelled'}];await f.sync.sync();assert.equal(f.workspace.list({kind:'commitment'})[0].state,'cancelled');});
test('rich knowledge document saves formatting alongside plain text and keeps original record and fields',t=>{const f=fixture(t);const e=f.workspace.save({kind:'annotation',title:'Nota',content:'Antes',data:{context:'Preservado'}});const document=JSON.stringify({version:1,blocks:[{id:'body',type:'text',text:'Depois',marks:[{start:0,end:6,bold:true}]}],properties:[]});const saved=f.workspace.save({...e,content:'Depois',data:{...e.data,leaf_document:document}},e.id);assert.equal(saved.id,e.id);assert.equal(saved.data.context,'Preservado');assert.equal(JSON.parse(saved.data.leaf_document).blocks[0].marks[0].bold,true);});

test('upgrade resets the old unexpanded feed token once, importing unchanged series without duplicating existing instances',async t=>{const f=fixture(t),a=f.sync.account();a.meta.sync_token='legacy-token';f.sync.write(a);f.state.instances=[occurrence('a','2026-10-03T12:00:00Z')];await f.sync.sync();assert.equal(f.state.calls[0].u.searchParams.has('syncToken'),false);assert.equal(f.sync.account().meta.recurrence_version,1);const id=f.workspace.list({kind:'commitment'})[0].id;await f.sync.sync();assert.ok(f.state.calls.some(c=>c.u.searchParams.get('syncToken')==='token'));assert.equal(f.workspace.list({kind:'commitment'}).length,1);assert.equal(f.workspace.list({kind:'commitment'})[0].id,id);});

test('site/plain-text edits refresh the rich body while retaining properties, record identity and prior version',t=>{const f=fixture(t);const document=JSON.stringify({version:1,created_at:'2026-10-05T12:00:00Z',blocks:[{id:'body',type:'text',text:'Antes',marks:[{start:0,end:5,bold:true}]}],properties:[{id:'author',name:'Autor',value:'Eu'}]});const e=f.workspace.save({kind:'annotation',title:'Nota',content:'Antes',data:{leaf_document:document}});const next=f.workspace.save({revision:e.revision,content:'Mudou no site'},e.id),rich=JSON.parse(next.data.leaf_document);assert.equal(next.id,e.id);assert.equal(rich.blocks[0].text,next.content);assert.equal(rich.properties[0].value,'Eu');assert.equal(rich.created_at,'2026-10-05T12:00:00Z');assert.ok(f.store.db.prepare('SELECT COUNT(*) AS n FROM entity_versions WHERE entity_id=?').get(e.id).n>=2);});
