const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const {fixture}=require(root+'/tests/helpers.cjs'),{createRuntime}=require(root+'/src/core/runtime');
test('mobile capsules: authenticated complete flow and preservation of existing records',async t=>{
const f=fixture(t);f.config.loginPassword='test-only-capsules-password';f.config.loginEmail='owner@example.test';const runtime=createRuntime(f.config,{store:f.store,provider:f.provider,secureDir:path.join(f.dir,'secure')});const server=http.createServer(runtime.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});const base='http://127.0.0.1:'+server.address().port+'/api/mobile';let token='';const request=async(route,body,method=body===undefined?'GET':'POST')=>{const r=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()};};
assert.equal((await request('/md/capsules/doses?from=2026-01-01&to=2026-01-02')).status,401);const auth=await request('/auth/login',{email:'owner@example.test',password:f.config.loginPassword});assert.equal(auth.status,200);token=auth.data.token;
const page=runtime.workspace.save({kind:'user_page',title:'Página preservada',data:{blocks_json:'[]'}});const conversation=f.store.createConversation('Histórico preservado','web');f.store.userMessage({conversationId:conversation.id,clientId:crypto.randomUUID(),message:'Mensagem preservada'});const before=JSON.stringify({page:runtime.workspace.get(page.id),messages:f.store.messages(conversation.id)});
const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const saved=await request('/workspace/entities',{kind:'capsule',title:'Cápsula isolada QA',privacy:'private',state:'active',data:{capsule_type:'herbal',dose_text:'1 cápsula',times_json:'["00:00"]',start_date:date,remind_minutes:30,notifications:true}});assert.equal(saved.status,201);const input={capsule_id:saved.data.id,day:date,time:'00:00',taken:true};const taken=await request('/md/capsules/doses',input);assert.equal(taken.status,200);assert.equal((await request('/md/capsules/doses',input)).data.item.id,taken.data.item.id);assert.equal((await request('/md/capsules/doses?from='+date+'&to='+date)).data.items.length,1);assert.equal((await request('/md/capsules/doses',{...input,taken:false})).status,200);assert.equal((await request('/md/capsules/doses?from='+date+'&to='+date)).data.items.length,0);assert.equal((await request('/md/dashboard')).data.widgets.includes('capsules'),true);assert.equal((await request('/md/capabilities')).data.capsules,true);assert.equal(JSON.stringify({page:runtime.workspace.get(page.id),messages:f.store.messages(conversation.id)}),before);
});
