'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const {Store}=require('../src/memory/store');const {SofiaCore}=require('../src/core/sofia-core');const {createRuntime}=require('../src/core/runtime');const {authorize}=require('../src/core/semantic-authority');
const API_KEY='sk-'+'test_only_'.repeat(6);
function blankAction(){return {entity_kind:'',memory_kind:'',title:'',content:'',area:'',state:'',scope:'',date:'',time:'',location:'',list_name:'',quantity:'',parent_title:'',scope_id:'',target_id:'',target_ids:[],page_id:'',block_id:'',block_type:'',position:'',changes:[],token_limit:0,page_blocks:[],priority:false,query_target:'none',privacy_route:'auto',tags:[]};}
function base(intent='respond',extra={}){const executable=!['respond','clarify'].includes(intent);return authorize({intent,confidence:.98,explicit_action:false,needs_context:false,context_query:'',assistant_message:'Resposta simulada para testes.',response_ready:false,ready_for_backend:executable,execution_confirmed:false,pending_state:intent==='clarify'?'replace':'none',ui_target:'none',decision_basis:'Plano simulado para teste.',privacy:{sensitivity:'general',recommended_route:'shared',reason:'Conteúdo geral no teste.'},action:blankAction(),actions:[],clarification:{question:'',options:[]},...extra},'test-fixture');}
function inputText(input=[]){
  const arr=Array.isArray(input)?input:[];const joined=arr.map(x=>String(x?.content||'')).join('\n');
  const pending=joined.match(/RESPOSTA(?: ATUAL)? AO ESCLARECIMENTO:?\s*([\s\S]*?)$/i)||joined.match(/RESPOSTA ATUAL AO ESCLARECIMENTO\s*([\s\S]*?)$/i);if(pending)return pending[1].trim();
  for(let i=arr.length-1;i>=0;i--){const c=String(arr[i]?.content||'');if(!c||/^Use o contexto acima/i.test(c)||/^CONTEXTO /i.test(c))continue;return c.trim();}
  return '';
}
function originalText(input=[]){const joined=(input||[]).map(x=>String(x?.content||'')).join('\n');const m=joined.match(/PEDIDO ORIGINAL(?: QUE GEROU O ESCLARECIMENTO)?:?\s*([\s\S]*?)(?:\n(?:A Sofia pediu|PLANO PENDENTE)|$)/i);return m?m[1].trim():inputText(input);}
function semanticPlan(req){
  const text=inputText(req.input),orig=originalText(req.input),n=text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const origN=orig.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  if(/(?:exclu|apag|remov|limp).*tudo.*agenda|(?:agenda).*(?:inteira|toda)/i.test(origN)&&/^(sim|pode|confirmo|confirmar|sim[, ]|isso mesmo)/i.test(n))return base('delete_agenda',{confidence:.99,explicit_action:true,ready_for_backend:true,execution_confirmed:true,pending_state:'resolve',assistant_message:'Limpeza da Agenda confirmada.',ui_target:'commitments',privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Gestão da agenda cotidiana no teste.'},action:{...blankAction(),scope:'all',title:'Tudo da Agenda'}});
  if(/(?:exclu|apag|remov).*todos.*lembret/i.test(origN)&&/^(sim|pode|confirmo|confirmar|sim[, ]|isso mesmo)/i.test(n))return base('delete_reminders',{confidence:.99,explicit_action:true,ready_for_backend:true,execution_confirmed:true,pending_state:'resolve',assistant_message:'Exclusão de lembretes confirmada.',ui_target:'commitments',privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Gestão da agenda cotidiana no teste.'},action:{...blankAction(),scope:'all',title:'Todos os lembretes'}});
  if(/(?:exclu|apag|remov).*todos.*compromiss/i.test(origN)&&/^(sim|pode|confirmo|confirmar|sim[, ]|isso mesmo)/i.test(n))return base('delete_commitments',{confidence:.99,explicit_action:true,ready_for_backend:true,execution_confirmed:true,pending_state:'resolve',assistant_message:'Exclusão confirmada.',ui_target:'commitments',privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Gestão da agenda cotidiana no teste.'},action:{...blankAction(),scope:'all',title:'Todos os compromissos'}});
  if(/(?:exclu|apag|remov).*todos.*compromiss/i.test(origN)&&/^(nao|não|cancela|cancelar|deixa|deixe)/i.test(text))return base('respond',{assistant_message:'Certo, cancelei essa ação.',pending_state:'resolve',response_ready:true,privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Cancelamento da ação pendente.'}});
  if(/(?:exclu|apag|remov).*todos.*compromiss/i.test(origN)&&/lembretes|isso vai|vai apagar/i.test(n))return base('respond',{assistant_message:'Não. Essa exclusão se refere apenas aos compromissos; os lembretes ficam separados.',pending_state:'keep',response_ready:false,privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Pergunta lateral sobre a ação pendente.'}});
  if(/^(adicionar aos compromissos|adicionar compromisso)/i.test(text))return base('create_commitment',{explicit_action:true,assistant_message:'Vou registrar esse compromisso.',ui_target:'commitments',action:{...blankAction(),title:'aniversario de um colega',content:'Aniversário de um colega no Capão.',area:'Pessoal',date:'2026-09-19',time:'19:00',location:'Capão'}});
  if(/pagamento|cart[aã]o|cpf|localiza[cç][aã]o atual|confidencial/i.test(n))return base('respond',{privacy:{sensitivity:'sensitive',recommended_route:'private',reason:'Conteúdo sensível no teste.'},assistant_message:'Resposta privada simulada.'});
  if(/^criar tarefa$/i.test(text))return base('create_task',{explicit_action:true,assistant_message:'Vou criar uma tarefa.',ui_target:'tasks',action:{...blankAction(),title:'Ir ao aniversário de um colega',content:'Ir ao aniversário',area:'Pessoal'}});
  if(/^criar lembrete$/i.test(text))return base('create_reminder',{explicit_action:true,assistant_message:'Vou criar um lembrete.',ui_target:'commitments',action:{...blankAction(),title:'Aniversário de um colega',content:'Lembrar do aniversário',area:'Pessoal',date:'2026-09-19',time:'19:00',location:'Capão'}});
  if(/^so estou contando/i.test(n))return base('respond',{assistant_message:'Entendi. Não vou registrar nenhuma ação.'});
  if(/hoje eu tenho um aniversario de um colega.*19/i.test(n)&&!/adicione|agende|registre|marque|crie/i.test(n))return base('clarify',{confidence:.94,explicit_action:false,assistant_message:'O que você quer que eu faça com isso?',privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Compromisso cotidiano de baixo risco.'},clarification:{question:'O que você quer que eu faça com isso?',options:[{id:'add_commitment',label:'Adicionar aos compromissos',meaning:'Registrar como compromisso.'},{id:'create_task',label:'Criar tarefa',meaning:'Registrar uma ação que precisa ser feita.'},{id:'create_reminder',label:'Criar lembrete',meaning:'Criar um lembrete separado.'},{id:'just_telling',label:'Só estou contando',meaning:'Não registrar nem executar ação.'}]}});
  let m=text.match(/(?:guarde|salve|registre).*mem[oó]ria\s*[:,-]?\s*([\s\S]+)/i);if(m)return base('save_memory',{explicit_action:true,assistant_message:'Guardei isso na memória.',action:{...blankAction(),memory_kind:'fact',title:m[1].trim().slice(0,100),content:m[1].trim(),area:'Geral'}});
  m=text.match(/(?:registre|salve).*decis[aã]o\s*:\s*([\s\S]+)/i);if(m)return base('save_memory',{explicit_action:true,assistant_message:'Registrei a decisão.',action:{...blankAction(),memory_kind:'decision',title:m[1].trim().slice(0,100),content:m[1].trim(),area:'Geral'}});
  m=text.match(/(?:coloque|coloca|adicione|adiciona).*a fazer\s*[:,-]?\s*([\s\S]+)/i);if(m)return base('create_task',{explicit_action:true,assistant_message:'Adicionei à sua lista de tarefas.',ui_target:'tasks',action:{...blankAction(),title:m[1].trim(),content:m[1].trim(),area:'Geral'}});
  if(/minhas prioridades/i.test(n))return base('query',{explicit_action:true,assistant_message:'Consultando prioridades.',ui_target:'tasks',action:{...blankAction(),query_target:'priorities'}});
  if(/o que.*tenho.*fazer|mostre.*a fazer|liste.*a fazer/i.test(n))return base('query',{explicit_action:true,ui_target:'tasks',action:{...blankAction(),query_target:'tasks'}});
  if(/compromissos/i.test(n)&&/mostre|liste|quais|tenho/i.test(n))return base('query',{explicit_action:true,ui_target:'commitments',action:{...blankAction(),query_target:'commitments'}});
  if(/(?:exclu|apag|remov|limp).*tudo.*agenda|(?:agenda).*(?:inteira|toda)/i.test(n))return base('clarify',{confidence:.99,explicit_action:true,ready_for_backend:false,execution_confirmed:false,pending_state:'replace',assistant_message:'Você quer excluir todos os compromissos e lembretes da sua Agenda? Essa ação não poderá ser desfeita.',ui_target:'commitments',privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Gestão da agenda cotidiana no teste.'},actions:[{intent:'delete_agenda',action:{...blankAction(),scope:'all',title:'Tudo da Agenda'}}],clarification:{question:'Você quer excluir todos os compromissos e lembretes da sua Agenda? Essa ação não poderá ser desfeita.',options:[{id:'confirm_delete_agenda',label:'Sim, limpar Agenda',meaning:'Confirmar a exclusão de compromissos e lembretes.'},{id:'cancel_delete',label:'Cancelar',meaning:'Não excluir nada.'}]}});
  if(/(?:exclu|apag|remov).*todos.*lembret/i.test(n))return base('clarify',{confidence:.99,explicit_action:true,ready_for_backend:false,execution_confirmed:false,pending_state:'replace',assistant_message:'Você quer excluir todos os seus lembretes? Essa ação não poderá ser desfeita.',ui_target:'commitments',privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Gestão da agenda cotidiana no teste.'},actions:[{intent:'delete_reminders',action:{...blankAction(),scope:'all',title:'Todos os lembretes'}}],clarification:{question:'Você quer excluir todos os seus lembretes? Essa ação não poderá ser desfeita.',options:[{id:'confirm_delete_reminders',label:'Sim, excluir lembretes',meaning:'Confirmar a exclusão de todos os lembretes.'},{id:'cancel_delete',label:'Cancelar',meaning:'Não excluir nada.'}]}});
  if(/(?:exclu|apag|remov).*todos.*compromiss/i.test(n))return base('clarify',{confidence:.99,explicit_action:true,ready_for_backend:false,execution_confirmed:false,pending_state:'replace',assistant_message:'Você quer excluir todos os seus compromissos? Essa ação não poderá ser desfeita.',ui_target:'commitments',privacy:{sensitivity:'personal_non_sensitive',recommended_route:'shared',reason:'Gestão da agenda cotidiana no teste.'},actions:[{intent:'delete_commitments',action:{...blankAction(),scope:'all',title:'Todos os compromissos'}}],clarification:{question:'Você quer excluir todos os seus compromissos? Essa ação não poderá ser desfeita.',options:[{id:'confirm_delete',label:'Sim, excluir todos',meaning:'Confirmar a exclusão de todos os compromissos.'},{id:'cancel_delete',label:'Cancelar',meaning:'Não excluir nada.'}]}});
  if(/mercado/i.test(n)&&/mostre|liste|falta/i.test(n))return base('query',{explicit_action:true,ui_target:'lists',action:{...blankAction(),query_target:'market'}});
  if(/farmacia/i.test(n)&&/mostre|liste|falta/i.test(n))return base('query',{explicit_action:true,ui_target:'lists',action:{...blankAction(),query_target:'pharmacy'}});
  if(/cursos|estudos/i.test(n)&&/mostre|liste|quais/i.test(n))return base('query',{explicit_action:true,ui_target:'study',action:{...blankAction(),query_target:'study'}});
  if(/biblioteca|acervo/i.test(n)&&/mostre|abra|liste/i.test(n))return base('query',{explicit_action:true,ui_target:'library',action:{...blankAction(),query_target:'library'}});
  if(/o que combinamos|qual era|como ficou|continue|continua|retome|onde paramos|dobre as quantidades|mais curto/i.test(n))return base('respond',{needs_context:true,context_query:text,assistant_message:'Resposta simulada com contexto relevante.'});
  if(/isso.*privad/i.test(n))return base('reclassify_route',{explicit_action:true,assistant_message:'Marquei como privado.',action:{...blankAction(),privacy_route:'private'}});
  if(/isso.*compartilhad/i.test(n))return base('reclassify_route',{explicit_action:true,assistant_message:'Marquei como compartilhado.',action:{...blankAction(),privacy_route:'shared'}});
  if(/crie.*(?:pagina|area|espaco)|coloca.*pagina/i.test(n)){
    const nested=text.match(/p[aá]gina(?:\s+(?:chamada|de))?\s+["“]?(.+?)["”]?\s+dentro\s+d[aeo]\s+["“]?(.+?)["”]?\s*$/i);
    if(nested)return base('create_user_page',{explicit_action:true,assistant_message:'Criei a página dentro do espaço.',ui_target:'userpage',action:{...blankAction(),title:nested[1].trim(),content:'',area:'Pessoal',parent_title:nested[2].trim()}});
    const title=(text.match(/(?:pagina|área|area|espaço|espaco).*?(?:chamad[ao]\s+)?["“]?([^"”]+)["”]?$/i)||[])[1]||'Novo espaço';return base('create_user_page',{explicit_action:true,assistant_message:'Criei o espaço.',ui_target:'userpage',action:{...blankAction(),title:title.trim(),content:'Espaço solicitado pelo usuário.',area:'Pessoal'}});
  }
  if(/vamos estudar/i.test(n))return base('respond',{needs_context:false,assistant_message:'Resposta simulada para aula.'});
  if(/registro privado testeconfidencialorion/i.test(n))return base('respond',{assistant_message:'Entendi.'});
  if(/qual era a cor do experimento orion/i.test(n))return base('respond',{needs_context:true,context_query:'experimento Orion cor',assistant_message:'Resposta simulada com histórico.'});
  if(/qual era o nome do projeto aurora/i.test(n))return base('respond',{needs_context:true,context_query:'projeto Aurora',assistant_message:'Resposta simulada com memória.'});
  return base('respond');
}
function semanticPendingReply(req){
  const text=inputText(req.input),n=text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  if(/^(sim|sim[, ]|pode|confirmo|confirma|isso mesmo)/i.test(n))return {relation:'confirm',assistant_message:'Confirmado.'};
  if(/^(nao|não|cancela|cancelar|deixa|deixe)/i.test(text))return {relation:'cancel',assistant_message:'Cancelado.'};
  if(/\?|por que|porque voce|o que acontece|como assim/i.test(n))return {relation:'question',assistant_message:'O usuário fez uma pergunta sobre a pendência.'};
  if(/os dois|ambos|as duas|quero os dois/i.test(n))return {relation:'answer_clarification',assistant_message:'O usuário escolheu as duas opções.'};
  if(/na verdade|em vez|troca|muda|so monitora|só monitora/i.test(n))return {relation:'change_request',assistant_message:'O usuário mudou o pedido.'};
  if(/\d{1,2}:?\d{0,2}|manha|manhã|tarde|noite|black friday|amanha|amanhã|hoje|dia \d/i.test(text))return {relation:'provide_information',assistant_message:'O usuário forneceu informação que faltava.'};
  return {relation:'answer_clarification',assistant_message:'A resposta se refere à pergunta pendente.'};
}
function fixture(t,{privateMode=true,plans=[]}={}){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sofia-test-'));const store=new Store(path.join(dir,'data','sofia.sqlite'));
  if(privateMode)store.updateSettings({privacyMode:'private',routingEnabled:true,privateConfirmed:true,sharedConfirmed:true,sharedBillingAcknowledged:true,legacyRoute:'private',privateDailyUSD:10,privateMonthlyUSD:100,sharedDailyUSD:10,sharedMonthlyUSD:100,privateInputPerMillion:1,privateOutputPerMillion:1,sharedInputPerMillion:1,sharedOutputPerMillion:1,sharedDailyTokenCap:1000000});
  else store.updateSettings({privacyMode:'auto',routingEnabled:true,privateConfirmed:true,sharedConfirmed:true,sharedBillingAcknowledged:true,legacyRoute:'private',privateDailyUSD:10,privateMonthlyUSD:100,sharedDailyUSD:10,sharedMonthlyUSD:100,privateInputPerMillion:1,privateOutputPerMillion:1,sharedInputPerMillion:1,sharedOutputPerMillion:1,sharedDailyTokenCap:1000000});
  const calls=[],queue=[...plans];const config={root:path.resolve(__dirname,'..'),dataDir:path.join(dir,'data'),backupDir:path.join(dir,'backups'),apiKey:API_KEY,privateApiKey:API_KEY,sharedApiKey:'sk-fictitious-shared-key-for-tests-123456789',model:'gpt-5.6-luna',apiTimeoutMs:50,maxMessageChars:12000,maxContextChars:20000};
  const provider={
    respond:async request=>{calls.push({kind:'respond',...request});const joined=(request.input||[]).map(x=>String(x?.content||'')).join('\n');let reply='Resposta simulada para testes.';const tech=joined.match(/RESULTADO TÉCNICO DO BACKEND[^:]*:\s*({[\s\S]*})/);if(tech){try{const data=JSON.parse(tech[1]);if(data.suggested_summary)reply=data.suggested_summary;}catch{}}else{const dir=joined.match(/DIREÇÃO CONVERSACIONAL INTERNA DA SOFIA[^:]*:\s*({[\s\S]*})/);if(dir){try{const data=JSON.parse(dir[1]);if(data.pending_state&&data.pending_state!=='none'&&data.assistant_message)reply=data.assistant_message;}catch{}}}return {reply,usage:{input_tokens:24,output_tokens:9},requestId:'req_text'};},
    structured:async request=>{calls.push({kind:'structured',...request});const data=request.name==='sofia_pending_reply_v60'?semanticPendingReply(request):(request.name==='sofia_destructive_confirmation_v60'?{decision:/^(sim|pode|confirmo)/i.test(inputText(request.input))?'confirm':/^(nao|não|cancela)/i.test(inputText(request.input))?'cancel':'unclear',assistant_message:'Confirmação simulada.'}:(queue.length?queue.shift():semanticPlan(request)));return {data,reply:JSON.stringify(data),usage:{input_tokens:30,output_tokens:18},requestId:'req_structured'};}
  };
  const core=new SofiaCore({store,config,provider});t.after(()=>{try{store.close();}catch{}fs.rmSync(dir,{recursive:true,force:true});});return {dir,store,core,config,provider,calls,plans:queue};
}
async function httpFixture(t,runtimeOptions={}){const f=fixture(t);const runtime=createRuntime(f.config,{store:f.store,provider:f.provider,secureDir:path.join(f.dir,'secure'),...runtimeOptions});const server=http.createServer(runtime.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const boot=await fetch(base+'/api/bootstrap').then(r=>r.json());t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});return {...f,...runtime,base,token:boot.token,server,request:async(url,body,method='POST',extra={})=>{const r=await fetch(base+url,{method,headers:{'Content-Type':'application/json','X-Sofia-Token':boot.token,...extra},body:body===undefined?undefined:JSON.stringify(body)});let payload;try{payload=await r.json();}catch{payload=null;}return {status:r.status,headers:r.headers,body:payload};}};}
module.exports={fixture,httpFixture,API_KEY,base,blankAction,semanticPlan};
