'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {Store}=require('../src/memory/store'),{createChatSync,recoverShutdownConversations}=require('../src/services/chat-sync');
function fixture(t,filename=':memory:'){const store=new Store(filename);t.after(()=>store.close());return store;}
function add(store,c,text='Mensagem preservada'){const user=store.userMessage({conversationId:c.id,clientId:crypto.randomUUID(),message:text}).message;store.complete(user.id,null,{reply:'Resposta preservada'},[]);return user;}
function legacyPause(store,c){store.checkpoint(c.id,{reason:'shutdown'});store.db.prepare("UPDATE conversations SET state='paused' WHERE id=?").run(c.id);}
const rows=store=>JSON.stringify(store.db.prepare('SELECT * FROM messages ORDER BY rowid').all());
test('054 backend: shutdown checkpoint preserves active conversation, selection, timestamps and every message row',t=>{const s=fixture(t),c=s.createConversation('Pessoal','web');add(s,c);const sync=createChatSync(s);sync.select(c.id);const before=rows(s),updated=s.conversation(c.id).updated_at;s.checkpoint(c.id,{reason:'shutdown'});assert.equal(s.conversation(c.id).state,'active');assert.equal(s.conversation(c.id).updated_at,updated);assert.equal(sync.current(true).id,c.id);assert.equal(rows(s),before);assert.equal(s.checkpoints(c.id)[0].reason,'shutdown');});
test('054 backend: manual pause still pauses and is never treated as a restart',t=>{const s=fixture(t),c=s.createConversation('Pausa manual');add(s,c);s.checkpoint(c.id,{reason:'manual'});assert.equal(s.conversation(c.id).state,'paused');assert.deepEqual(recoverShutdownConversations(s,()=>assert.fail('No recovery backup should be necessary')),{conversations:0,messages:0});assert.equal(s.conversation(c.id).state,'paused');});
test('054 backend: legacy shutdown recovery requires backup first and changes only conversation visibility',t=>{const s=fixture(t),c=s.createConversation('Histórico','mobile');const m=add(s,c);s.saveVoiceMessage(m.id,{mime:'audio/mp4',duration_ms:1000,transcript:'voz',bytes:Buffer.from('audio-fixture')});const task=s.saveTask({title:'Tarefa preservada'});createChatSync(s).select(c.id);legacyPause(s,c);const before=rows(s),voice=JSON.stringify(s.db.prepare('SELECT * FROM voice_messages').all()),updated=s.conversation(c.id).updated_at;let backup=0;const result=recoverShutdownConversations(s,()=>{backup++;assert.equal(s.conversation(c.id).state,'paused');assert.equal(rows(s),before);});assert.deepEqual(result,{conversations:1,messages:2});assert.equal(backup,1);assert.equal(s.conversation(c.id).state,'active');assert.equal(s.conversation(c.id).updated_at,updated);assert.equal(rows(s),before);assert.equal(JSON.stringify(s.db.prepare('SELECT * FROM voice_messages').all()),voice);assert.equal(s.task(task.id).title,'Tarefa preservada');assert.equal(createChatSync(s).snapshot().conversation.id,c.id);});
test('054 backend: backup failure aborts recovery without touching current data',t=>{const s=fixture(t),c=s.createConversation('Histórico');add(s,c);legacyPause(s,c);const before=rows(s);assert.throws(()=>recoverShutdownConversations(s),/backup/);assert.throws(()=>recoverShutdownConversations(s,()=>{throw Error('disk full');}),/disk full/);assert.equal(s.conversation(c.id).state,'paused');assert.equal(rows(s),before);});
test('054 backend: deleted, archived, contact, simulation, other-owner and manually paused histories never reappear',t=>{const s=fixture(t),keep=[];for(const kind of ['deleted','archived','whatsapp','test','whatsapp-simulator','other-owner','manual']){const c=s.createConversation(kind,'web');add(s,c);legacyPause(s,c);if(['deleted','archived'].includes(kind))s.db.prepare('UPDATE conversations SET state=? WHERE id=?').run(kind,c.id);else if(['whatsapp','test','whatsapp-simulator'].includes(kind))s.db.prepare('UPDATE conversations SET channel=? WHERE id=?').run(kind,c.id);else if(kind==='other-owner')s.db.prepare("UPDATE conversations SET owner='someone-else' WHERE id=?").run(c.id);else s.checkpoint(c.id,{reason:'manual'});keep.push({...s.db.prepare('SELECT * FROM conversations WHERE id=?').get(c.id)});}const before=rows(s);assert.deepEqual(recoverShutdownConversations(s,()=>assert.fail()),{conversations:0,messages:0});for(const c of keep)assert.deepEqual({...s.db.prepare('SELECT * FROM conversations WHERE id=?').get(c.id)},c);assert.equal(rows(s),before);});
test('054 backend: recovery is idempotent and does not replace an explicitly selected current thread',t=>{const s=fixture(t),old=s.createConversation('Antiga'),current=s.createConversation('Atual');add(s,old);add(s,current);legacyPause(s,old);createChatSync(s).select(current.id);let backups=0;assert.equal(recoverShutdownConversations(s,()=>backups++).conversations,1);assert.deepEqual(recoverShutdownConversations(s,()=>backups++),{conversations:0,messages:0});assert.equal(backups,1);assert.equal(createChatSync(s).current(true).id,current.id);assert.equal(s.db.prepare("SELECT COUNT(*) AS n FROM audit WHERE event='conversation.recovered-after-shutdown'").get().n,1);});
test('054 backend: recovery transaction rolls back every reactivation if audit fails',t=>{const s=fixture(t),a=s.createConversation('A'),b=s.createConversation('B');add(s,a);add(s,b);legacyPause(s,a);legacyPause(s,b);const before=rows(s),original=s.audit.bind(s);s.audit=(event,id)=>{if(id===b.id)throw Error('audit full');return original(event,id);};assert.throws(()=>recoverShutdownConversations(s,()=>{}),/audit full/);assert.equal(s.conversation(a.id).state,'paused');assert.equal(s.conversation(b.id).state,'paused');assert.equal(rows(s),before);assert.equal(s.db.prepare("SELECT COUNT(*) AS n FROM audit WHERE event='conversation.recovered-after-shutdown'").get().n,0);});
test('054 backend: multiple real SQLite restarts preserve the same thread and exact message content',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sofia-history-054-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const filename=path.join(dir,'sofia.sqlite');let s=new Store(filename);const c=s.createConversation('Persistente');add(s,c);createChatSync(s).select(c.id);const before=rows(s);for(let i=0;i<3;i++){s.checkpoint(c.id,{reason:'shutdown'});s.close();s=new Store(filename);assert.equal(createChatSync(s).current(true).id,c.id);assert.equal(rows(s),before);}s.close();});
