'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const crypto=require('node:crypto');const {apply,rollback,plan}=require('../tools/update-library.cjs');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sofia-install-test-')),target=path.join(dir,'SOFIA-OS'),release=path.join(dir,'release');fs.mkdirSync(path.join(target,'src'),{recursive:true});fs.mkdirSync(path.join(release,'projeto','src'),{recursive:true});fs.writeFileSync(path.join(target,'package.json'),'{}');fs.writeFileSync(path.join(target,'src','server.js'),'original-server');fs.writeFileSync(path.join(target,'.env'),'LOCAL_SECRET=do-not-touch');fs.writeFileSync(path.join(target,'webhook-debug.js'),'original-webhook');fs.writeFileSync(path.join(release,'projeto','src','server.js'),'new-server');fs.writeFileSync(path.join(release,'projeto','src','core.js'),'new-core');fs.writeFileSync(path.join(release,'MANIFESTO_V45.json'),JSON.stringify({version:45,files:[{path:'src/server.js',before_sha256:hash('original-server'),sha256:hash('new-server')},{path:'src/core.js',before_sha256:null,sha256:hash('new-core')}]}));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return {dir,target,release};}
test('Atualizador instala apenas arquivos previstos e preserva credenciais e webhook',t=>{const f=setup(t);const r=apply(f.release,f.target);assert.equal(fs.readFileSync(path.join(f.target,'src','server.js'),'utf8'),'new-server');assert.equal(fs.readFileSync(path.join(f.target,'.env'),'utf8'),'LOCAL_SECRET=do-not-touch');assert.equal(fs.readFileSync(path.join(f.target,'webhook-debug.js'),'utf8'),'original-webhook');assert.equal(fs.existsSync(path.join(r.backup,'.env')),false);assert.match(fs.readFileSync(path.join(f.target,'.gitignore'),'utf8'),/\/data\//);});
test('Atualização é idempotente sem sobrescrever arquivo já correto',t=>{const f=setup(t);apply(f.release,f.target);assert.equal(apply(f.release,f.target).already,true);});
test('Atualizador recusa modificação local não presente no ZIP original',t=>{const f=setup(t);fs.writeFileSync(path.join(f.target,'src','server.js'),'user-new-work');assert.throws(()=>apply(f.release,f.target),/mudou depois do ZIP/);assert.equal(fs.readFileSync(path.join(f.target,'src','server.js'),'utf8'),'user-new-work');});
test('Integridade é verificada antes da primeira alteração',t=>{const f=setup(t);fs.writeFileSync(path.join(f.release,'projeto','src','core.js'),'tampered');assert.throws(()=>apply(f.release,f.target),/integridade/);assert.equal(fs.readFileSync(path.join(f.target,'src','server.js'),'utf8'),'original-server');});
test('Falha durante cópia reverte todos os arquivos já trocados',t=>{const f=setup(t);assert.throws(()=>apply(f.release,f.target,{afterWrite:()=>{throw new Error('Simulated disk failure');}}),/revertidos/);assert.equal(fs.readFileSync(path.join(f.target,'src','server.js'),'utf8'),'original-server');assert.equal(fs.existsSync(path.join(f.target,'src','core.js')),false);});
test('Reversão volta ao código anterior sem apagar memória nem .env',t=>{const f=setup(t);const r=apply(f.release,f.target);fs.mkdirSync(path.join(f.target,'data'));fs.writeFileSync(path.join(f.target,'data','memory'),'preserve');rollback(r.backup,f.target);assert.equal(fs.readFileSync(path.join(f.target,'src','server.js'),'utf8'),'original-server');assert.equal(fs.existsSync(path.join(f.target,'src','core.js')),false);assert.equal(fs.readFileSync(path.join(f.target,'data','memory'),'utf8'),'preserve');assert.equal(fs.readFileSync(path.join(f.target,'.env'),'utf8'),'LOCAL_SECRET=do-not-touch');});
test('Reversão não descarta edições posteriores',t=>{const f=setup(t);const r=apply(f.release,f.target);fs.writeFileSync(path.join(f.target,'src','core.js'),'later-work');assert.throws(()=>rollback(r.backup,f.target),/Arquivo alterado/);assert.equal(fs.readFileSync(path.join(f.target,'src','core.js'),'utf8'),'later-work');});
test('Manifesto não pode solicitar cópia de .env ou traversal',t=>{const f=setup(t);for(const name of ['.env','../outside']){fs.writeFileSync(path.join(f.release,'MANIFESTO_V45.json'),JSON.stringify({version:45,files:[{path:name,sha256:'fake'}]}));assert.throws(()=>plan(f.release,f.target));}assert.equal(fs.readFileSync(path.join(f.target,'.env'),'utf8'),'LOCAL_SECRET=do-not-touch');});
test('Conflito arquivo no lugar de pasta é detectado antes de alterar código',t=>{const f=setup(t);fs.mkdirSync(path.join(f.release,'projeto','src','config'));fs.writeFileSync(path.join(f.release,'projeto','src','config','identity.js'),'identity');const m=JSON.parse(fs.readFileSync(path.join(f.release,'MANIFESTO_V45.json')));m.files.push({path:'src/config/identity.js',before_sha256:null,sha256:hash('identity')});fs.writeFileSync(path.join(f.release,'MANIFESTO_V45.json'),JSON.stringify(m));fs.writeFileSync(path.join(f.target,'src','config'),'unexpected-file');assert.throws(()=>apply(f.release,f.target),/pasta esperada/);assert.equal(fs.readFileSync(path.join(f.target,'src','server.js'),'utf8'),'original-server');});
