import React,{useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {useTheme} from '../lib/theme';
import {useCapsules} from '../lib/capsule-store';
import {capsuleDoses} from '../lib/capsule-model';
import type {CapsuleDose} from '../lib/capsule-model';
import type {SofiaApi} from '../lib/api';
import {Sheet} from './Sheet';
import {Button,Empty,ErrorBanner} from './UI';
import {Icon} from './Icon';
export function CapsuleWidget({api,active,onOpen}:{api:SofiaApi;active:boolean;onOpen:()=>void}){const c=useTheme(),state=useCapsules(api,active),[detail,setDetail]=useState<CapsuleDose|null>(null),pending=capsuleDoses(state.plans,state.history).filter(d=>!d.taken);return <View style={{gap:16}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><Text style={{flex:1,color:c.text,fontSize:20,fontWeight:'600'}}>Cápsulas</Text><Text accessibilityLabel="Doses pendentes hoje" style={{color:c.muted}}>{pending.length}</Text><Pressable accessibilityLabel="Abrir app Cápsulas" onPress={onOpen} style={{padding:8}}><Icon name="capsule" color={c.accent}/></Pressable></View>{state.error?<ErrorBanner text={state.error} onRetry={()=>void state.load()}/>:null}{!state.loaded&&!state.error?<Text style={{color:c.muted}}>Carregando suas doses…</Text>:pending.length?<View style={{backgroundColor:c.surface,borderRadius:18,paddingHorizontal:14,borderWidth:1,borderColor:c.line}}>{pending.map(d=><View key={d.key} style={{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12,borderBottomWidth:1,borderColor:c.line}}><Pressable accessibilityRole="checkbox" accessibilityLabel={'Tomei '+d.plan.title+' às '+d.time} accessibilityState={{checked:false,disabled:!!state.saving}} disabled={!!state.saving} onPress={()=>void state.take(d.plan.id,d.day,d.time).catch(()=>{})} style={{minWidth:44,minHeight:44,justifyContent:'center',alignItems:'center'}}><View style={{width:22,height:22,borderWidth:1.5,borderRadius:7,borderColor:d.due?c.danger:c.accent}}/></Pressable><Pressable accessibilityLabel={'Ver dose '+d.plan.title+' às '+d.time} onPress={()=>setDetail(d)} style={{flex:1,gap:6}}><Text style={{color:c.text,fontSize:14}}>{d.plan.title}</Text>{d.plan.data.dose_text?<Text style={{color:c.muted,fontSize:12}}>{d.plan.data.dose_text}</Text>:null}<Text testID={'capsule-status-'+d.plan.id+'-'+d.time} style={{color:d.due?c.danger:c.muted,fontSize:12,fontWeight:d.due?'700':'400'}}>{d.time}{d.due?' · Hora de tomar':' · Hoje'}</Text></Pressable></View>)}</View>:<Empty icon="capsule" title={state.plans.some(p=>p.state==='active')?'Doses de hoje em dia':'Sua rotina de cápsulas'} body={state.plans.some(p=>p.state==='active')?'As próximas doses aparecem no próximo dia.':'Cadastre os horários e lembretes no app Cápsulas.'}/>}<Sheet visible={!!detail} onClose={()=>setDetail(null)} label="Fechar dose"><Text style={{fontSize:22,color:c.text,fontWeight:'700'}}>{detail?.plan.title}</Text><Text style={{color:c.muted,marginVertical:16}}>{detail?.time}{detail?.plan.data.dose_text?' · '+detail.plan.data.dose_text:''}</Text>{detail?.plan.content?<Text style={{color:c.text,marginBottom:18}}>{detail.plan.content}</Text>:null}<Button title="Abrir rotina e histórico" onPress={()=>{setDetail(null);onOpen();}}/></Sheet></View>;}
