import React,{useState} from 'react';
import {View,Text,Pressable,ScrollView,TextInput} from 'react-native';
import {useTheme} from '../lib/theme';
import {Icon} from './Icon';
import {Button,IconButton,forms} from './UI';
import {Sheet} from './Sheet';
export function Choice({value,options,onChange,label,creatable=false}:{creatable?:boolean;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void;label:string}){
 const c=useTheme(),[open,setOpen]=useState(false),[query,setQuery]=useState('');
 return <><Pressable onPress={()=>{setQuery('');setOpen(true);}} accessibilityRole="button" accessibilityLabel={label} style={[forms.input,{borderColor:c.line,backgroundColor:c.input,flexDirection:'row',alignItems:'center',gap:12}]}><Text numberOfLines={2} style={{flex:1,color:c.text,fontSize:14}}>{options.find(x=>x.value===value)?.label||value||'Selecionar'}</Text><Icon name="chevron" color={c.muted} size={18}/></Pressable><Sheet visible={open} onClose={()=>setOpen(false)} label="Fechar seleção"><View style={{gap:12}}><View style={{flexDirection:'row',alignItems:'center'}}><Text style={{flex:1,fontSize:20,fontWeight:'600',color:c.text}}>{label}</Text><IconButton name="close" label="Fechar seleção" onPress={()=>setOpen(false)}/></View>{options.length>8||creatable?<TextInput accessibilityLabel={'Buscar '+label} value={query} onChangeText={setQuery} placeholder="Buscar" placeholderTextColor={c.muted} style={[forms.input,{borderColor:c.line,color:c.text}]}/>:null}<ScrollView keyboardShouldPersistTaps="handled">{options.filter(o=>o.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(o=><Pressable key={o.value} onPress={()=>{onChange(o.value);setOpen(false);}} style={{minHeight:48,padding:12,borderBottomWidth:1,borderColor:c.line,flexDirection:'row',gap:10,alignItems:'center'}}><Text style={{flex:1,color:c.text,fontSize:15}}>{o.label}</Text>{value===o.value?<Icon name="check" color={c.accent}/>:null}</Pressable>)}{creatable&&query.trim()&&!options.some(o=>o.value.toLowerCase()===query.trim().toLowerCase())?<Button title={'Criar “'+query.trim()+'”'} onPress={()=>{onChange(query.trim());setOpen(false);}}/>:null}</ScrollView></View></Sheet></>;
}
