import React,{useMemo,useState} from 'react';
import {Alert,Modal,Pressable,ScrollView,Text,View} from 'react-native';
import Svg,{Circle,Line,Polyline} from 'react-native-svg';
import type {DayRecord,PriceSeries} from '../lib/dashboard';
import {localDateKey,monthCells,priceGeometry} from '../lib/dashboard';
import {useTheme} from '../lib/theme';
import {Button,IconButton} from './UI';
export function MiniAgenda({items,onOpen,onItem}:{items:DayRecord[];onOpen:(day:string)=>void;onItem:(item:DayRecord)=>void}){
 const c=useTheme(),[month,setMonth]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selected,setSelected]=useState(localDateKey(new Date()));
 const dates=useMemo(()=>new Set(items.map(item=>localDateKey(item.date))),[items]),chosen=items.filter(i=>localDateKey(i.date)===selected);
 return <View style={{padding:16,borderRadius:22,borderWidth:1,borderColor:c.line,backgroundColor:c.surface,gap:10}}><View style={{flexDirection:'row',alignItems:'center'}}><Text style={{flex:1,color:c.text,fontWeight:'700',fontSize:19}}>Agenda</Text><Pressable accessibilityLabel="Abrir agenda completa" onPress={()=>onOpen(selected)} style={{padding:8}}><Text style={{fontSize:12,color:c.accent}}>Abrir agenda</Text></Pressable></View>
 <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><IconButton size={36} name="back" label="Mês anterior" onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}/><Pressable onPress={()=>{const today=new Date();setMonth(new Date(today.getFullYear(),today.getMonth(),1));setSelected(localDateKey(today));}}><Text style={{color:c.text,fontSize:14,textTransform:'capitalize'}}>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</Text></Pressable><IconButton size={36} name="chevron" label="Próximo mês" onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}/></View>
 <View style={{flexDirection:'row'}}>{['D','S','T','Q','Q','S','S'].map((v,i)=><Text key={i} style={{width:'14.2857%',fontSize:10,color:c.muted,textAlign:'center'}}>{v}</Text>)}</View>
 <View style={{flexDirection:'row',flexWrap:'wrap'}}>{monthCells(month).map((day,i)=>{const key=day?localDateKey(day):'',active=key===selected;return <View key={i} style={{width:'14.2857%',padding:1}}>{day?<Pressable accessibilityLabel={day.toLocaleDateString('pt-BR')+(dates.has(key)?', com compromissos':'')} accessibilityState={{selected:active}} onPress={()=>setSelected(key)} style={{height:36,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:active?c.accent:'transparent',gap:2}}><Text style={{fontSize:12,color:active?'#fff':c.text}}>{day.getDate()}</Text><View style={{width:3,height:3,borderRadius:2,backgroundColor:dates.has(key)?(active?'#fff':c.accent):'transparent'}}/></Pressable>:null}</View>;})}</View>
 <Text style={{fontSize:12,fontWeight:'600',color:c.muted}}>Dia {selected.slice(8)}/{selected.slice(5,7)} · {chosen.length} {chosen.length===1?'item':'itens'}</Text><ScrollView nestedScrollEnabled style={{maxHeight:160}} contentContainerStyle={{gap:8,paddingBottom:4}}>{chosen.length?chosen.map(item=><Pressable key={item.id} accessibilityLabel={item.title} onPress={()=>onItem(item)} style={{flexDirection:'row',gap:10,paddingVertical:8}}><Text style={{color:c.accent,fontSize:11}}>{item.date.length===10?'Dia inteiro':new Date(item.date).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</Text><View style={{flex:1,gap:3}}><Text style={{color:c.text,fontSize:13}}>{item.title}</Text><Text style={{color:c.muted,fontSize:10}}>{item.isTask?'Tarefa':item.kind==='reminder'?'Lembrete':'Compromisso'}</Text></View></Pressable>):<Text style={{color:c.muted,fontSize:12,paddingVertical:12}}>Nenhum item neste dia.</Text>}</ScrollView></View>;
}
function PricePlot({series,height=132}:{series:PriceSeries[];height?:number}){const c=useTheme(),g=priceGeometry(series,320,height);if(!g)return <Text style={{color:c.muted,fontSize:12,paddingVertical:16}}>Ainda sem histórico de preços.</Text>;const currency=series[0]?.currency||'BRL',money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency});return <View><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{color:c.muted,fontSize:10}}>{money(g.ymax)}</Text><Text style={{color:c.muted,fontSize:10}}>Preço × tempo</Text></View><Svg width="100%" height={height} viewBox={`0 0 320 ${height}`}><Line x1={12} y1={height-8} x2={308} y2={height-8} stroke={c.line}/>{g.lines.map(line=><React.Fragment key={line.id}><Polyline points={line.points.map(p=>p.join(',')).join(' ')} fill="none" stroke={line.color} strokeWidth={2.5}/>{line.points.length===1?<Circle cx={line.points[0][0]} cy={line.points[0][1]} r={3} fill={line.color}/>:null}</React.Fragment>)}</Svg><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontSize:10,color:c.muted}}>{new Date(g.xmin).toLocaleDateString('pt-BR')}</Text><Text style={{fontSize:10,color:c.muted}}>{money(g.ymin)}</Text><Text style={{fontSize:10,color:c.muted}}>{new Date(g.xmax).toLocaleDateString('pt-BR')}</Text></View></View>;}
export function PriceWidget({series}:{series:PriceSeries[]}){const c=useTheme(),[open,setOpen]=useState(false),currency=series[0]?.currency||'BRL';const preview=series.filter(s=>s.currency===currency).slice(0,4),currencies=[...new Set(series.map(s=>s.currency))];return <><Pressable accessibilityLabel="Abrir análise de preços" onPress={()=>setOpen(true)} style={{backgroundColor:c.surface,padding:16,borderRadius:22,borderWidth:1,borderColor:c.line,gap:12}}><Text style={{fontSize:19,fontWeight:'700',color:c.text}}>Monitoramentos</Text><PricePlot series={preview}/><View style={{gap:5}}>{preview.map(s=><Text key={s.monitor.id} numberOfLines={1} style={{fontSize:11,color:s.color}}>● {s.monitor.title}</Text>)}</View><Text style={{fontSize:11,color:c.muted}}>{series.length?`${series.length} monitoramentos · toque para ver o histórico`:'Seus preços acompanhados aparecem aqui.'}</Text></Pressable><Modal visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><ScrollView contentContainerStyle={{padding:22,paddingTop:50,paddingBottom:35,gap:14,backgroundColor:c.bg,flexGrow:1}}><View style={{flexDirection:'row',alignItems:'center'}}><Text style={{flex:1,fontSize:23,fontWeight:'700',color:c.text}}>Análise de preços</Text><IconButton name="close" label="Fechar análise" onPress={()=>setOpen(false)}/></View>{currencies.map(code=><View key={code} style={{gap:10}}><Text style={{color:c.text,fontSize:16}}>{code}</Text><PricePlot height={200} series={series.filter(s=>s.currency===code)}/></View>)}{series.map(s=><View key={s.monitor.id} style={{padding:14,gap:8,borderWidth:1,borderColor:c.line,borderRadius:14,backgroundColor:c.surface}}><Text style={{color:s.color,fontSize:16,fontWeight:'600'}}>{s.monitor.title}</Text><Text style={{color:c.muted,fontSize:11}}>{String(s.monitor.data.variant||'')}</Text>{s.points.length?s.points.map((p,i)=><View key={p.id||i} style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><Text style={{fontSize:11,color:c.muted}}>{new Date(p.time).toLocaleString('pt-BR')}</Text><Text style={{fontSize:12,color:c.text}}>{p.value.toLocaleString('pt-BR',{style:'currency',currency:s.currency})}</Text></View>):<Text style={{color:c.muted,fontSize:12}}>Ainda sem observações.</Text>}</View>)}</ScrollView></Modal></>;}
