import React,{useState} from 'react';
import {Pressable,ScrollView,Text,View} from 'react-native';
import {useTheme} from '../lib/theme';
import {dateDisplay} from '../lib/date-time';
import {monthCells,localDateKey} from '../lib/dashboard';
import {Sheet} from './Sheet';
import {Button,IconButton,forms} from './UI';
import {MonthSwipe} from './MonthSwipe';
export function DateTimeField({label,value,onChange,dateOnly=false,compact=false,allowClear=true,emptyLabel='Selecionar…'}:{label:string;value:string;onChange:(value:string)=>void;dateOnly?:boolean;compact?:boolean;allowClear?:boolean;emptyLabel?:string}){
 const c=useTheme(),[open,setOpen]=useState(false),[selected,setSelected]=useState(new Date()),[month,setMonth]=useState(new Date());
 function reveal(){const d=value?new Date(value.length===10?value+'T12:00:00':value):new Date();const valid=Number.isFinite(d.getTime())?d:new Date();setSelected(valid);setMonth(new Date(valid.getFullYear(),valid.getMonth(),1));setOpen(true);}
 const change=(part:'hours'|'minutes',n:number)=>setSelected(old=>{const d=new Date(old);part==='hours'?d.setHours(n):d.setMinutes(n);d.setSeconds(0,0);return d;});
 return <><View style={compact?{flexDirection:"row",gap:20,alignItems:"center"}:undefined}><Text style={compact?{color:c.muted,fontSize:13}:[forms.label,{color:c.muted}]}>{compact?"◷  ":""}{label}</Text><Pressable accessibilityLabel={label} onPress={reveal} style={compact?{flex:1,minHeight:40,justifyContent:"center"}:[forms.input,{backgroundColor:c.input,borderColor:c.line,minHeight:52,justifyContent:"center"}]}><Text style={{color:value?c.text:c.muted,fontSize:14}}>{value&&compact?new Date(value).toLocaleString('pt-BR',{dateStyle:'long',timeStyle:'short'}):dateDisplay(value,dateOnly)||emptyLabel}</Text></Pressable></View>
 <Sheet visible={open} onClose={()=>setOpen(false)} label="Fechar data e horário"><ScrollView keyboardShouldPersistTaps="handled"><View style={{flexDirection:'row',alignItems:'center'}}><Text style={{flex:1,fontSize:20,fontWeight:'700',color:c.text}}>{label}</Text><IconButton name="close" label="Fechar data e horário" onPress={()=>setOpen(false)}/></View><MonthSwipe onMonth={delta=>setMonth(m=>new Date(m.getFullYear(),m.getMonth()+delta,1))}>
 <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><IconButton name="back" label="Mês anterior do seletor" onPress={()=>setMonth(m=>new Date(m.getFullYear(),m.getMonth()-1,1))}/><Text style={{color:c.text,fontSize:16}}>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</Text><IconButton name="chevron" label="Próximo mês do seletor" onPress={()=>setMonth(m=>new Date(m.getFullYear(),m.getMonth()+1,1))}/></View>
 <View style={{flexDirection:'row'}}>{['D','S','T','Q','Q','S','S'].map((d,i)=><Text key={i} style={{width:'14.2857%',textAlign:'center',color:c.muted}}>{d}</Text>)}</View><View style={{flexDirection:'row',flexWrap:'wrap',marginVertical:8}}>{monthCells(month).map((d,i)=><View key={i} style={{width:'14.2857%',padding:2}}>{d?<Pressable accessibilityLabel={'Selecionar '+dateDisplay(localDateKey(d),true)} onPress={()=>{const next=new Date(d);next.setHours(selected.getHours(),selected.getMinutes(),0,0);setSelected(next);}} style={{height:36,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:localDateKey(d)===localDateKey(selected)?c.accent:'transparent'}}><Text style={{color:localDateKey(d)===localDateKey(selected)?'#fff':c.text}}>{d.getDate()}</Text></Pressable>:null}</View>)}</View></MonthSwipe>
 {!dateOnly?<View style={{flexDirection:'row',gap:12,marginVertical:12}}>{(['hours','minutes'] as const).map(part=><View key={part} style={{flex:1}}><Text style={{textAlign:'center',color:c.muted,marginBottom:8}}>{part==='hours'?'Hora · 24h':'Minutos'}</Text><ScrollView style={{height:126,backgroundColor:c.input,borderRadius:12}} nestedScrollEnabled contentOffset={{x:0,y:Math.max(0,(part==='hours'?selected.getHours():selected.getMinutes())*42-42)}}>{Array.from({length:part==='hours'?24:60},(_,i)=><Pressable key={i} accessibilityLabel={(part==='hours'?'Hora ':'Minuto ')+i} onPress={()=>change(part,i)} style={{height:42,alignItems:'center',justifyContent:'center',backgroundColor:(part==='hours'?selected.getHours():selected.getMinutes())===i?c.accentSoft:'transparent'}}><Text style={{color:c.text,fontSize:20,fontWeight:'600'}}>{String(i).padStart(2,'0')}</Text></Pressable>)}</ScrollView></View>)}</View>:null}
 <Text style={{color:c.accent,textAlign:'center',marginVertical:12,fontWeight:'600'}}>{dateDisplay(selected.toISOString(),dateOnly)}</Text><Button title="Confirmar data e horário" onPress={()=>{onChange(dateOnly?localDateKey(selected):selected.toISOString());setOpen(false);}}/>{allowClear?<Pressable onPress={()=>{onChange('');setOpen(false);}} style={{padding:14,alignItems:'center'}}><Text style={{color:c.muted}}>Remover data</Text></Pressable>:null}</ScrollView></Sheet></>;
}
