import React,{useRef,useState} from 'react';
import {Keyboard,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {useTheme} from '../lib/theme';
import {editBlockText,formatRange,leafBlocks,leafId,textRuns} from '../lib/leaf-document';
import type {Leaf,LeafBlock,Mark} from '../lib/leaf-document';
import {Sheet} from './Sheet';
import {Button,IconButton} from './UI';
export function LeafEditor({leaf,onChange,titleRef}:{leaf:Leaf;onChange:(patch:Partial<Leaf>)=>void;titleRef:React.RefObject<TextInput|null>}){
 const c=useTheme(),blocks=leafBlocks(leaf),[active,setActive]=useState(blocks[0].id),[selection,setSelection]=useState({start:0,end:0}),[typing,setTyping]=useState<Partial<Mark>>({}),[format,setFormat]=useState(false),[property,setProperty]=useState(false),[propName,setPropName]=useState(''),[propValue,setPropValue]=useState('');
 const inputs=useRef(new Map<string,TextInput>()),past=useRef<LeafBlock[][]>([]),future=useRef<LeafBlock[][]>([]),latest=useRef(blocks);latest.current=blocks;
 function save(next:LeafBlock[],history=true){if(history){past.current.push(JSON.parse(JSON.stringify(latest.current)));past.current=past.current.slice(-100);future.current=[];}latest.current=next;onChange({blocks:next,content:next.map(b=>b.text).join('\n\n')});}
 function patch(change:Partial<LeafBlock>){save(blocks.map(b=>b.id===active?{...b,...change}:b));}
 function mark(style:Partial<Mark>){if(selection.end>selection.start)save(blocks.map(b=>b.id===active?formatRange(b,selection.start,selection.end,style):b));else setTyping(old=>({...old,...style}));inputs.current.get(active)?.focus();}
 function toggleStyle(key:'bold'|'italic'|'underline'|'strike'|'code'){const block=blocks.find(b=>b.id===active);const selected=block?textRuns(block).filter(r=>r.end>selection.start&&r.start<selection.end):[];const enabled=selection.end>selection.start?selected.length>0&&selected.every(r=>r.style[key]):!!typing[key];mark({[key]:!enabled});}
 function undo(redo=false){const from=redo?future.current:past.current,to=redo?past.current:future.current;const value=from.pop();if(value){to.push(JSON.parse(JSON.stringify(blocks)));save(value,false);}}
 function add(type='text'){const next={id:leafId(),text:'',type,marks:[]};const at=blocks.findIndex(b=>b.id===active);save([...blocks.slice(0,at+1),next,...blocks.slice(at+1)]);setActive(next.id);setSelection({start:0,end:0});setTyping({});setFormat(false);setTimeout(()=>inputs.current.get(next.id)?.focus(),100);}
 const action=(label:string,text:string,fn:()=>void)=><Pressable key={label} accessibilityLabel={label} onPress={fn} style={{minWidth:42,height:44,alignItems:'center',justifyContent:'center',paddingHorizontal:10}}><Text style={{color:c.text,fontSize:18}}>{text}</Text></Pressable>;
 return <View style={{flex:1}}><ScrollView keyboardShouldPersistTaps="always" contentContainerStyle={{padding:24,paddingBottom:80}}>
 <TextInput ref={titleRef} accessibilityLabel="Título da folha" value={leaf.title} onChangeText={title=>onChange({title})} multiline placeholder="Sem título" placeholderTextColor={c.muted+'88'} style={{fontSize:32,fontWeight:'800',color:c.text,padding:0,marginBottom:22}}/>
 <View style={{flexDirection:'row',gap:20,marginBottom:16}}><Text style={{color:c.muted,fontSize:13}}>◷  Criado em</Text><Text style={{color:c.text,fontSize:13,flex:1}}>{leaf.created_at?new Date(leaf.created_at).toLocaleString('pt-BR',{dateStyle:'long',timeStyle:'short'}):'Data não registrada'}</Text></View>
 {(leaf.properties||[]).map(p=><View key={p.id} style={{flexDirection:'row',gap:14,marginVertical:4}}><Text style={{color:c.muted,width:120,paddingVertical:8}}>{p.name}</Text><TextInput accessibilityLabel={'Propriedade '+p.name} value={p.value} onChangeText={value=>onChange({properties:leaf.properties!.map(x=>x.id===p.id?{...x,value}:x)})} style={{flex:1,color:c.text,paddingVertical:8}}/></View>)}
 <Pressable accessibilityLabel="Adicionar propriedade" onPress={()=>{setPropName('');setPropValue('');setProperty(true);}} style={{paddingVertical:12}}><Text style={{color:c.muted}}>＋ Adicionar propriedade</Text></Pressable><View style={{height:1,backgroundColor:c.line,marginTop:14,marginBottom:24}}/>
 {blocks.map((b,i)=>b.type==='divider'?<Pressable key={b.id} onPress={()=>setActive(b.id)} style={{paddingVertical:14}}><View style={{height:1,backgroundColor:c.line}}/></Pressable>:<View key={b.id} style={{flexDirection:'row',marginBottom:16,borderLeftWidth:b.type==='quote'?3:0,borderColor:c.accent,paddingLeft:b.type==='quote'?14:0,backgroundColor:b.type==='code'?c.input:'transparent',borderRadius:4}}>
 {['bullet','number','todo'].includes(b.type)?<Pressable onPress={()=>{setActive(b.id);if(b.type==='todo')save(blocks.map(x=>x.id===b.id?{...x,checked:!x.checked}:x));}} style={{paddingTop:8,paddingRight:10}}><Text style={{color:c.text}}>{b.type==='todo'?(b.checked?'☑':'☐'):b.type==='number'?String(i+1)+'.':'•'}</Text></Pressable>:null}
 <TextInput ref={r=>{if(r)inputs.current.set(b.id,r);else inputs.current.delete(b.id);}} accessibilityLabel={i===0?'Conteúdo da folha':'Bloco de texto '+(i+1)} multiline onFocus={()=>setActive(b.id)} onSelectionChange={e=>{if(active===b.id)setSelection(e.nativeEvent.selection);}} onChangeText={text=>save(blocks.map(x=>x.id===b.id?editBlockText(x,text,typing):x))} placeholder={i===0?'Escreva algo…':''} placeholderTextColor={c.muted+'77'} style={{flex:1,minHeight:42,color:c.text,padding:0,textAlignVertical:'top',fontSize:b.type==='heading1'?29:b.type==='heading2'?24:b.type==='heading3'?20:16,lineHeight:b.type.startsWith('heading')?36:26,fontWeight:b.type.startsWith('heading')?'700':'400',fontFamily:b.type==='code'?'monospace':undefined,textAlign:b.align||'left',textDecorationLine:b.checked?'line-through':'none'}}>{textRuns(b).map(r=><Text key={r.start} style={{fontWeight:r.style.bold?'700':undefined,fontStyle:r.style.italic?'italic':undefined,textDecorationLine:r.style.underline&&r.style.strike?'underline line-through':r.style.underline?'underline':r.style.strike?'line-through':'none',fontFamily:r.style.code?'monospace':undefined,color:r.style.color||c.text,backgroundColor:r.style.highlight||'transparent'}}>{r.text}</Text>)}</TextInput></View>)}
 </ScrollView><View testID="leaf-format-toolbar" style={{borderTopWidth:1,borderColor:c.line,backgroundColor:c.surface}}><ScrollView horizontal keyboardShouldPersistTaps="always" showsHorizontalScrollIndicator={false}>{action('Novo bloco','＋',()=>add())}{action('Estilos de texto','Aa',()=>setFormat(true))}{action('Negrito','B',()=>toggleStyle('bold'))}{action('Itálico','𝘐',()=>toggleStyle('italic'))}{action('Sublinhado','U̲',()=>toggleStyle('underline'))}{action('Desfazer na folha','↶',()=>undo())}{action('Refazer na folha','↷',()=>undo(true))}{action('Excluir bloco','⌫',()=>{const next=blocks.filter(b=>b.id!==active);if(!next.length)next.push({id:leafId(),type:'text',text:'',marks:[]});save(next);setActive(next[0].id);})}{action('Fechar teclado','⌨',()=>Keyboard.dismiss())}</ScrollView></View>
 <Sheet visible={format} onClose={()=>setFormat(false)}><Text style={{color:c.text,fontSize:22,fontWeight:'700',marginBottom:14}}>Estilos de texto</Text><ScrollView keyboardShouldPersistTaps="always"><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{[['text','Texto'],['heading1','Título 1'],['heading2','Título 2'],['heading3','Título 3'],['bullet','Lista com marcadores'],['number','Lista numerada'],['todo','Lista de tarefas'],['quote','Citação'],['code','Código']].map(([type,label])=><Pressable key={type} onPress={()=>{patch({type});setFormat(false);}} style={{backgroundColor:c.input,borderRadius:9,padding:12}}><Text style={{color:c.text}}>{label}</Text></Pressable>)}</View><View style={{flexDirection:'row',flexWrap:'wrap',marginVertical:12}}>{action('Tachado','S̶',()=>{toggleStyle('strike');setFormat(false);})}{action('Código no texto','<>',()=>{toggleStyle('code');setFormat(false);})}{action('Alinhar à esquerda','≡←',()=>patch({align:'left'}))}{action('Centralizar','≡',()=>patch({align:'center'}))}{action('Alinhar à direita','→≡',()=>patch({align:'right'}))}{action('Inserir divisor','―',()=>add('divider'))}</View><Text style={{color:c.muted}}>Cor do texto</Text><View style={{flexDirection:'row',gap:12,marginVertical:14}}>{[c.text,'#AF9AFF','#F26B7A','#38BFA4','#DBAA36','#54A5ED'].map(color=><Pressable accessibilityLabel={'Cor '+color} key={color} onPress={()=>{mark({color});setFormat(false);}} style={{width:34,height:34,borderRadius:17,backgroundColor:color}}/>)}</View><Text style={{color:c.muted}}>Destaque</Text><View style={{flexDirection:'row',gap:12,marginVertical:14}}>{['transparent','#7353B855','#DA9C2655','#2A9B8155','#C4506155'].map(highlight=><Pressable accessibilityLabel={'Destaque '+highlight} key={highlight} onPress={()=>{mark({highlight});setFormat(false);}} style={{width:34,height:34,borderRadius:8,borderWidth:1,borderColor:c.line,backgroundColor:highlight}}/>)}</View></ScrollView></Sheet>
 <Sheet visible={property} onClose={()=>setProperty(false)}><Text style={{color:c.text,fontSize:22,fontWeight:'700'}}>Nova propriedade</Text><TextInput accessibilityLabel="Nome da propriedade" value={propName} onChangeText={setPropName} placeholder="Nome" placeholderTextColor={c.muted} style={{color:c.text,padding:14,backgroundColor:c.input,marginVertical:12}}/><TextInput accessibilityLabel="Valor da propriedade" value={propValue} onChangeText={setPropValue} placeholder="Valor" placeholderTextColor={c.muted} style={{color:c.text,padding:14,backgroundColor:c.input,marginBottom:12}}/><Button title="Adicionar propriedade" disabled={!propName.trim()} onPress={()=>{onChange({properties:[...(leaf.properties||[]),{id:leafId(),name:propName.trim(),value:propValue}]});setProperty(false);}}/></Sheet>
 </View>;
}
