import React,{useState} from 'react';
import {View,Text,TextInput,ScrollView,KeyboardAvoidingView,Platform} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {MotionModal} from './MotionModal';
import {Button,IconButton,ErrorBanner,forms} from './UI';
import {RatingStars} from './RatingStars';
import {useTheme} from '../lib/theme';
import {libraryRating} from '../lib/library-filters';
import {areaPayload,customPayload,customValues,suggestedFields,normalized} from '../lib/library-areas';
import type {LibraryArea,LibraryField} from '../lib/library-areas';
import type {SofiaApi} from '../lib/api';
import type {Entity} from '../lib/types';
import {errorText} from '../lib/chat-model';
function Field({label,value,onChange,multiline=false,maxLength=300}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean;maxLength?:number}){const c=useTheme();return <View style={{gap:7}}><Text style={{color:c.muted,fontSize:12}}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} multiline={multiline} maxLength={maxLength} style={[forms.input,{color:c.text,backgroundColor:c.input,borderColor:c.line,minHeight:multiline?90:50,textAlignVertical:multiline?'top':'center'}]}/></View>;}
function Frame({title,onClose,busy,children}:{title:string;onClose:()=>void;busy:boolean;children:React.ReactNode}){const c=useTheme();return <MotionModal visible animationType="none" onRequestClose={()=>{if(!busy)onClose();}}><SafeAreaView style={{flex:1,backgroundColor:c.bg}}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={{padding:12,flexDirection:'row',alignItems:'center'}}><IconButton name="close" label="Fechar área da Biblioteca" disabled={busy} onPress={onClose}/><Text style={{color:c.text,fontSize:20,fontWeight:'700',flex:1}}>{title}</Text></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:22,gap:18,paddingBottom:40}}>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView></MotionModal>;}
export function LibraryAreaEditor({api,area,existing,onClose,onSaved}:{api:SofiaApi;area?:LibraryArea;existing:LibraryArea[];onClose:()=>void;onSaved:(record:Entity)=>void}){
 const c=useTheme(),[title,setTitle]=useState(area?.record.title||''),[content,setContent]=useState(area?.record.content||''),[edited,setEdited]=useState(!!area),[fields,setFields]=useState<LibraryField[]>(area?.fields||suggestedFields('').map((label,i)=>({id:'field'+i,label}))),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function rename(value:string){setTitle(value);if(!edited)setFields(suggestedFields(value).map((label,i)=>({id:'field'+i,label})));}
 async function save(){if(busy)return;setBusy(true);setError('');try{if(existing.some(a=>a.record.id!==area?.record.id&&normalized(a.record.title)===normalized(title)))throw Error('Já existe uma área com esse nome.');const result=await api.saveEntity(areaPayload(title,content,fields,area?.record));onSaved(result);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <Frame title={area?'Editar área':'Nova área da Biblioteca'} busy={busy} onClose={onClose}>{error?<ErrorBanner text={error}/>:null}<Field label="Nome da área" value={title} onChange={rename} maxLength={80}/><Field label="Descrição da área" value={content} onChange={setContent} multiline maxLength={16000}/><Text style={{color:c.text,fontSize:17,fontWeight:'600'}}>Filtros da área</Text><Text style={{color:c.muted,lineHeight:21}}>Sugestões pelo nome da área. Você pode ajustar os campos. Os valores preenchidos nos registros viram opções de filtro automaticamente, junto com as estrelas.</Text>{fields.map((field,i)=><View key={field.id} style={{flexDirection:'row',gap:8,alignItems:'center'}}><View style={{flex:1}}><Field label={'Filtro '+(i+1)} value={field.label} maxLength={40} onChange={label=>{setEdited(true);setFields(rows=>rows.map(row=>row.id===field.id?{...row,label}:row));}}/></View><IconButton name="trash" label={'Remover filtro '+(i+1)} onPress={()=>{setEdited(true);setFields(rows=>rows.filter(row=>row.id!==field.id));}}/></View>)}{fields.length<6?<Button secondary title="Adicionar campo de filtro" onPress={()=>{setEdited(true);setFields(rows=>[...rows,{id:'f'+Date.now().toString(36),label:''}]);}}/>:null}<Button title="Salvar área" loading={busy} disabled={!title.trim()} onPress={()=>void save()}/></Frame>;
}
export function LibraryRecordEditor({api,area,item,onClose,onSaved}:{api:SofiaApi;area:LibraryArea;item:Partial<Entity>;onClose:()=>void;onSaved:(record:Entity)=>void}){
 const c=useTheme(),[title,setTitle]=useState(item.title||''),[content,setContent]=useState(item.content||''),[url,setUrl]=useState(item.data?.url||''),[rating,setRating]=useState(libraryRating(item)),[values,setValues]=useState(customValues(item)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){if(busy)return;setBusy(true);setError('');try{onSaved(await api.saveEntity(customPayload(area,item,title,content,url,rating,values)));}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <Frame title={area.record.title} busy={busy} onClose={onClose}>{error?<ErrorBanner text={error}/>:null}<Field label="Nome do registro" value={title} onChange={setTitle} maxLength={240}/><Field label="Descrição" value={content} onChange={setContent} multiline maxLength={16000}/><RatingStars value={rating} onChange={setRating}/>{area.fields.map(field=><Field key={field.id} label={field.label} value={values[field.id]||''} onChange={value=>setValues(old=>({...old,[field.id]:value}))}/>)}<Text style={{color:c.muted,fontSize:12,lineHeight:19}}>Separe vários valores com vírgula. As opções dos filtros são atualizadas ao salvar.</Text><Field label="Link de referência" value={url} onChange={setUrl} maxLength={1000}/><Button title="Salvar registro" loading={busy} disabled={!title.trim()} onPress={()=>void save()}/></Frame>;
}
