import React,{useRef,useState} from 'react';
import {Alert,Modal,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useTheme} from '../lib/theme';
import {Button,IconButton} from './UI';
import {Sheet} from './Sheet';
type Leaf={id:string;title:string;content:string};type Book={id:string;name:string;emoji:string;expanded:boolean;pages:Leaf[]};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
export function NotebookBlock({data,onChange,onDelete}:{data:Record<string,any>;onChange:(data:Record<string,any>,group?:string)=>void;onDelete?:()=>void}){
 const leafTitle=useRef<TextInput>(null);
 const c=useTheme(),books:Book[]=Array.isArray(data.notebooks)?data.notebooks:(data.rows||[]).map((r:any)=>({id:r.id,name:String(r.values?.name||''),emoji:'',expanded:false,pages:r.page_content?[{id:r.id+'-leaf',title:'',content:r.page_content}]:[]}));
 const [bookId,setBookId]=useState<string|null>(null),[leafId,setLeafId]=useState<string|null>(null),[newName,setNewName]=useState(''),[create,setCreate]=useState(false),[emojiBook,setEmojiBook]=useState<string|null>(null),[emoji,setEmoji]=useState(''),[moving,setMoving]=useState(false),[menu,setMenu]=useState(false);
 const book=books.find(b=>b.id===bookId),leaf=book?.pages.find(p=>p.id===leafId);
 function update(fn:(next:Book[])=>void,group='notebooks'){const next=clone(books);fn(next);onChange({...data,mode:'notebooks',notebooks:next},group);}
 function addLeaf(id:string){const p={id:uid(),title:'',content:''};update(next=>{const b=next.find(b=>b.id===id);if(b){b.pages.push(p);b.expanded=true;}});setBookId(id);setLeafId(p.id);}
 function changeLeaf(patch:Partial<Leaf>){if(!book||!leaf)return;update(next=>{const p=next.find(b=>b.id===book.id)?.pages.find(p=>p.id===leaf.id);if(p)Object.assign(p,patch);},'leaf:'+leaf.id+':'+Object.keys(patch).join(','));}
 function removeLeaf(){if(!book||!leaf)return;Alert.alert('Excluir página?',`“${leaf.title||'Sem título'}” será removida deste caderno.`,[{text:'Cancelar',style:'cancel'},{text:'Excluir',style:'destructive',onPress:()=>{update(next=>{const b=next.find(b=>b.id===book.id)!;b.pages=b.pages.filter(p=>p.id!==leaf.id);});setLeafId(null);setMenu(false);}}]);}
 const pageRows=(b:Book)=>b.pages.map(p=><Pressable key={p.id} accessibilityLabel={'Abrir folha '+(p.title||'Sem título')} onPress={()=>{setBookId(b.id);setLeafId(p.id);}} style={{paddingVertical:12,paddingLeft:38}}><Text style={{color:c.text,fontSize:15}}>{p.title||'Sem título'}</Text></Pressable>);
 return <View style={{gap:6}}><View style={{flexDirection:'row',alignItems:'center'}}><Pressable onLongPress={onDelete} style={{flex:1}}><Text style={{fontSize:23,fontWeight:'700',color:c.text}}>Anotações</Text></Pressable><IconButton name="plus" label="Novo caderno" size={34} onPress={()=>{setNewName('');setCreate(true);}}/></View>
 {books.map(b=><View key={b.id}><View style={{flexDirection:'row',alignItems:'center'}}><Pressable accessibilityLabel={(b.expanded?'Recolher':'Expandir')+' caderno '+b.name} onPress={()=>update(next=>{const v=next.find(x=>x.id===b.id)!;v.expanded=!v.expanded;})} style={{padding:10}}><Text style={{color:c.muted}}>{b.expanded?'⌄':'›'}</Text></Pressable><Pressable accessibilityLabel={'Ícone do caderno '+b.name} onPress={()=>{setEmojiBook(b.id);setEmoji(b.emoji||'');}} style={{padding:6}}><Text style={{fontSize:22}}>{b.emoji||'▧'}</Text></Pressable><Pressable accessibilityLabel={'Abrir caderno '+b.name} onPress={()=>{setBookId(b.id);setLeafId(null);}} style={{paddingVertical:12,flex:1}}><Text style={{fontSize:16,color:c.text,fontWeight:'600'}}>{b.name||'Sem título'}</Text></Pressable></View>{b.expanded?<>{pageRows(b)}<Pressable onPress={()=>addLeaf(b.id)} style={{padding:10,paddingLeft:38}}><Text style={{color:c.muted}}>＋ Nova folha</Text></Pressable></>:null}</View>)}
 <Sheet visible={create} onClose={()=>setCreate(false)}><Text style={{fontSize:21,fontWeight:'700',color:c.text}}>Novo caderno</Text><TextInput accessibilityLabel="Nome do caderno" autoFocus value={newName} onChangeText={setNewName} placeholder="Adicionar…" placeholderTextColor={c.muted} style={{color:c.text,backgroundColor:c.input,borderRadius:10,padding:14,marginVertical:15}}/><Button title="Criar caderno" disabled={!newName.trim()} onPress={()=>{update(next=>next.push({id:uid(),name:newName.trim(),emoji:'',expanded:true,pages:[]}));setCreate(false);}}/></Sheet>
 <Sheet visible={!!emojiBook} onClose={()=>setEmojiBook(null)}><Text style={{fontSize:21,fontWeight:'700',color:c.text}}>Ícone do caderno</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:12,marginVertical:14}}>{['💼','🎬','🏠','💡','📘','🎨','✍️','🌿'].map(e=><Pressable key={e} onPress={()=>setEmoji(e)} style={{padding:10,borderRadius:10,backgroundColor:emoji===e?c.accentSoft:c.input}}><Text style={{fontSize:26}}>{e}</Text></Pressable>)}</View><TextInput accessibilityLabel="Emoji do caderno" value={emoji} onChangeText={setEmoji} maxLength={16} style={{color:c.text,padding:12,fontSize:24}}/><Button title="Salvar ícone" onPress={()=>{update(next=>{next.find(b=>b.id===emojiBook)!.emoji=emoji;});setEmojiBook(null);}}/><Pressable onPress={()=>{update(next=>{next.find(b=>b.id===emojiBook)!.emoji='';});setEmojiBook(null);}} style={{padding:15}}><Text style={{color:c.muted}}>Remover ícone</Text></Pressable></Sheet>
 <Modal visible={!!book} animationType="slide" onRequestClose={()=>leafId?setLeafId(null):setBookId(null)}><SafeAreaView style={{flex:1,backgroundColor:c.bg}}><View testID="notebook-top-bar" style={{zIndex:10,elevation:10,backgroundColor:c.surface,minHeight:56,flexDirection:'row',alignItems:'center',paddingHorizontal:8,borderBottomWidth:1,borderColor:c.line}}><IconButton name="back" label="Voltar ao caderno" onPress={()=>leafId?setLeafId(null):setBookId(null)}/><Text numberOfLines={1} style={{flex:1,color:c.text,fontSize:15}}>{leaf?leaf.title||'Sem título':book?.name}</Text>{leaf?<IconButton name="more" label="Ações da folha" onPress={()=>setMenu(true)}/>:<IconButton name="plus" label="Nova folha" onPress={()=>book&&addLeaf(book.id)}/>}</View><ScrollView keyboardShouldPersistTaps="handled" style={{flex:1,overflow:'hidden'}} contentContainerStyle={{padding:24,paddingBottom:50}}>{leaf?<><TextInput ref={leafTitle} accessibilityLabel="Título da folha" value={leaf.title} onChangeText={title=>changeLeaf({title})} multiline placeholder="Sem título" placeholderTextColor={c.muted+'88'} style={{fontSize:34,fontWeight:'800',color:c.text,padding:0,marginBottom:16}}/><TextInput accessibilityLabel="Conteúdo da folha" value={leaf.content} onChangeText={content=>changeLeaf({content})} multiline placeholder="Escreva algo…" placeholderTextColor={c.muted+'77'} style={{fontSize:16,lineHeight:25,color:c.text,minHeight:200,textAlignVertical:'top',padding:0}}/></>:book?<><TextInput accessibilityLabel="Título do caderno" value={book.name} onChangeText={name=>update(next=>{next.find(b=>b.id===book.id)!.name=name;},'book:'+book.id)} style={{fontSize:32,fontWeight:'800',color:c.text,marginBottom:20}}/>{pageRows(book)}</>:null}</ScrollView></SafeAreaView></Modal>
 <Sheet visible={menu} onClose={()=>setMenu(false)}><Button title="Renomear" secondary onPress={()=>{setMenu(false);setTimeout(()=>leafTitle.current?.focus(),240);}}/><View style={{height:8}}/><Button title="Duplicar" secondary onPress={()=>{if(book&&leaf){const copy={...leaf,id:uid(),title:(leaf.title||'Sem título')+' cópia'};update(next=>next.find(b=>b.id===book.id)!.pages.push(copy));setLeafId(copy.id);}setMenu(false);}}/><View style={{height:8}}/><Button title="Mover" secondary onPress={()=>{setMenu(false);setMoving(true);}}/><Pressable onPress={removeLeaf} style={{paddingVertical:22}}><Text style={{color:c.danger}}>Excluir página</Text></Pressable></Sheet>
 <Sheet visible={moving} onClose={()=>setMoving(false)}><Text style={{color:c.text,fontSize:20,fontWeight:'700',marginBottom:12}}>Mover para caderno</Text>{books.filter(b=>b.id!==bookId).map(target=><Pressable key={target.id} onPress={()=>{if(book&&leaf){update(next=>{next.find(b=>b.id===book.id)!.pages=next.find(b=>b.id===book.id)!.pages.filter(p=>p.id!==leaf.id);next.find(b=>b.id===target.id)!.pages.push(leaf);});setBookId(target.id);}setMoving(false);}} style={{padding:14}}><Text style={{color:c.text}}>{target.name}</Text></Pressable>)}</Sheet>
 </View>;
}
