import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from 'react';
import {AppState,Modal,Pressable,ScrollView,Text,View,Alert} from 'react-native';
import type {Notice} from '../lib/types';
import {SofiaApi} from '../lib/api';
import {useTheme} from '../lib/theme';
import {errorText} from '../lib/chat-model';
import {Button,ErrorBanner,IconButton} from './UI';
import {Icon} from './Icon';
export const noticeArea=(n:Notice)=>{const category=String(n.category||'').toLowerCase();if(/course|curso|lesson|aula/.test(category))return 'Cursos';if(/study|estud/.test(category))return 'Estudos';if(/price|monitor|preço|compra|purchase/.test(category))return 'Monitoramento de produtos';if(/task|tarefa/.test(category))return 'Tarefas';if(/agenda|remind|commitment|routine|calendar|lembrete/.test(category))return 'Agenda';return 'Outros';};
type State={localOnly:boolean;items:Notice[];unread:number;loading:boolean;error:string;refresh:()=>Promise<void>;read:(n:Notice)=>Promise<void>;clear:(n:Notice)=>Promise<void>;clearAll:()=>Promise<void>};
const Context=createContext<State|null>(null);
export function NotificationProvider({api,enabled,children}:{api:SofiaApi;enabled:boolean;children:React.ReactNode}){
 const [items,setItems]=useState<Notice[]>([]),[unread,setUnread]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const generation=useRef(0),request=useRef(false);
 const refresh=useCallback(async()=>{if(!enabled||request.current)return;request.current=true;const current=generation.current;setLoading(true);try{const all:Notice[]=[];let offset:number|null=0,count=0;const seen=new Set<number>();while(offset!==null){if(seen.has(offset))throw Error('Paginação de notificações inválida.');seen.add(offset);const result=await api.allNotifications(offset);all.push(...result.items);offset=result.next_offset;count=result.unread;}if(current===generation.current){setItems([...new Map(all.map(n=>[n.id,n])).values()]);setUnread(count);setError('');}}catch(e){if(current===generation.current)setError(errorText(e));}finally{if(current===generation.current){setLoading(false);request.current=false;}}},[api,enabled]);
 useEffect(()=>{generation.current++;request.current=false;setItems([]);setUnread(0);setError('');void refresh();const timer=setInterval(()=>{if(AppState.currentState==='active')void refresh();},30000),subscription=AppState.addEventListener('change',state=>{if(state==='active')void refresh();});return()=>{generation.current++;request.current=false;clearInterval(timer);subscription.remove();};},[refresh]);
 async function read(n:Notice){try{await api.markRead(n.id);setItems(old=>old.map(x=>x.id===n.id?{...x,state:'read'}:x));if(n.state==='unread')setUnread(v=>Math.max(0,v-1));await refresh();}catch(e){setError(errorText(e));}}
 async function clear(n:Notice){try{await api.clearNotification(n.id);setItems(old=>old.filter(x=>x.id!==n.id));if(n.state==='unread')setUnread(v=>Math.max(0,v-1));await refresh();}catch(e){setError(errorText(e));}}
 async function clearAll(){try{await api.clearNotification('all');setItems([]);setUnread(0);await refresh();}catch(e){setError(errorText(e));}}
 return <Context.Provider value={{localOnly:api.mdLocalOnly,items,unread,loading,error,refresh,read,clear,clearAll}}>{children}</Context.Provider>;
}
export function useNotifications(){const value=useContext(Context);if(!value)throw Error('Centro de notificações não montado.');return value;}
export function NoticeRow({item}:{item:Notice}){const c=useTheme(),notices=useNotifications();return <View style={{padding:14,borderWidth:1,borderColor:c.line,borderRadius:16,backgroundColor:c.surface,gap:6}}><Text style={{color:c.text,fontSize:15,fontWeight:item.state==='unread'?'700':'500'}}>{item.title}</Text><Text style={{color:c.muted,fontSize:12,lineHeight:19}}>{item.body}</Text><Text style={{color:c.muted,fontSize:10}}>{new Date(item.created_at).toLocaleString('pt-BR')}</Text><View style={{flexDirection:'row',gap:10}}>{item.state==='unread'?<Pressable accessibilityLabel={'Marcar como lida: '+item.title} onPress={()=>void notices.read(item)} style={{paddingVertical:10}}><Text style={{color:c.accent,fontSize:12}}>Marcar como lida</Text></Pressable>:<Text style={{paddingVertical:10,color:c.muted,fontSize:12}}>Lida</Text>}<Pressable accessibilityLabel={'Limpar notificação: '+item.title} onPress={()=>void notices.clear(item)} style={{padding:10}}><Text style={{color:c.muted,fontSize:12}}>Limpar</Text></Pressable></View></View>;}
export function NotificationList({grouped=false}:{grouped?:boolean}){const n=useNotifications(),c=useTheme(),[limits,setLimits]=useState<Record<string,number>>({});const groups=useMemo(()=>{const result=new Map<string,Notice[]>();for(const item of n.items){const key=grouped?noticeArea(item):'';if(!result.has(key))result.set(key,[]);result.get(key)!.push(item);}return result;},[n.items,grouped]);return <View style={{gap:12}}>{n.localOnly?<Text style={{color:c.muted,fontSize:11,lineHeight:17}}>Servidor atual: até 300 avisos recentes. Limpar oculta os avisos somente neste aparelho; marcar como lida é sincronizado.</Text>:null}{n.error?<ErrorBanner text={n.error} onRetry={()=>void n.refresh()}/>:null}{!n.items.length?<Text style={{color:c.muted,paddingVertical:16}}>{n.loading?'Carregando…':'Sem notificações.'}</Text>:null}{[...groups].map(([area,items])=>{const limit=grouped?(limits[area]||5):items.length;return <View key={area} style={{gap:8}}>{grouped?<Text style={{fontSize:18,color:c.text,fontWeight:'700',paddingTop:10}}>{area} · {items.length}</Text>:null}{items.slice(0,limit).map(item=><NoticeRow key={item.id} item={item}/>)}{items.length>limit?<Button title={'Ver mais em '+area} secondary onPress={()=>setLimits(old=>({...old,[area]:limit+10}))}/>:null}</View>;})}</View>;}
export function NotificationBell({onViewAll}:{onViewAll:()=>void}){const c=useTheme(),n=useNotifications(),[open,setOpen]=useState(false);return <><Pressable accessibilityRole="button" accessibilityLabel={'Notificações: '+n.unread+' não lidas'} onPress={()=>{setOpen(true);void n.refresh();}} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Icon name="bell" color={c.text}/>{n.unread>0?<View style={{position:'absolute',right:0,top:0,minWidth:18,height:18,borderRadius:9,backgroundColor:c.accent,alignItems:'center',justifyContent:'center',paddingHorizontal:3}}><Text style={{color:'#fff',fontSize:10,fontWeight:'700'}}>{n.unread>99?'99+':n.unread}</Text></View>:null}</Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><Pressable onPress={()=>setOpen(false)} style={{flex:1,backgroundColor:'#00000055',justifyContent:'center',padding:18}}><Pressable onPress={()=>{}} style={{maxHeight:'84%',backgroundColor:c.bg,borderRadius:22,padding:16,gap:12}}><View style={{flexDirection:'row',alignItems:'center'}}><Text style={{flex:1,fontSize:20,fontWeight:'700',color:c.text}}>Notificações</Text><IconButton name="close" label="Fechar notificações" onPress={()=>setOpen(false)}/></View><ScrollView nestedScrollEnabled contentContainerStyle={{paddingBottom:10}}><NotificationList/></ScrollView>{n.items.length?<Pressable onPress={()=>Alert.alert('Limpar notificações?','Somente os avisos serão removidos. Seus eventos e registros permanecem.',[{text:'Cancelar',style:'cancel'},{text:'Limpar',onPress:()=>void n.clearAll()}])}><Text style={{color:c.muted,fontSize:12,padding:6}}>Limpar todas</Text></Pressable>:null}<Button title="Ver todas as notificações" onPress={()=>{setOpen(false);onViewAll();}}/></Pressable></Pressable></Modal></>;}
