import React,{useRef,useState} from 'react';
import {Pressable,ScrollView,Text,TextInput,View,type TextStyle} from 'react-native';
import {editBlockText,formatRange,textRuns,type Mark,type LeafBlock} from '../lib/leaf-document';
import {useTheme} from '../lib/theme';
import type {Task} from '../lib/types';
type Document=NonNullable<Task['description_document']>;
function blockFor(text:string,doc?:Document):LeafBlock{return {id:'description',type:'text',text,marks:doc?.text===text?doc.marks:[]};}
function runStyle(m:Partial<Mark>):TextStyle{return {fontWeight:m.bold?'700':'400',fontStyle:m.italic?'italic':'normal',textDecorationLine:m.underline&&m.strike?'underline line-through':m.underline?'underline':m.strike?'line-through':'none',...(m.color?{color:m.color}:{}),...(m.highlight?{backgroundColor:m.highlight}:{}),...(m.code?{fontFamily:'monospace'}:{})};}
export function TaskDescription({text,document,lines}:{text:string;document?:Document;lines?:number}){const c=useTheme();return <Text selectable numberOfLines={lines} style={{color:text?c.text:c.muted,fontSize:16,lineHeight:24}}>{text?textRuns(blockFor(text,document)).map((r,i)=><Text key={i} style={runStyle(r.style)}>{r.text}</Text>):'Sem descrição'}</Text>;}
export function TaskDescriptionEditor({text,document,onChange,disabled=false}:{text:string;document?:Document;onChange:(text:string,doc:Document)=>void;disabled?:boolean}){
 const c=useTheme(),input=useRef<TextInput>(null),selection=useRef({start:0,end:0}),[typing,setTyping]=useState<Partial<Mark>>({}),[palette,setPalette]=useState<'color'|'highlight'|null>(null);const block=blockFor(text,document);
 function commit(b:LeafBlock){onChange(b.text,{version:1,text:b.text,marks:b.marks});}
 function mark(style:Partial<Mark>){const {start,end}=selection.current;if(end>start)commit(formatRange(block,start,end,style));else if(text.length&&!input.current?.isFocused())commit(formatRange(block,0,text.length,style));else setTyping(t=>({...t,...style}));input.current?.focus();}
 function toggle(key:'bold'|'italic'|'underline'|'strike'|'code'){const {start,end}=selection.current;const current=end>start?textRuns(block).filter(r=>r.end>start&&r.start<end).every(r=>r.style[key]):!!typing[key];mark({[key]:!current});}
 return <View style={{gap:8}}><Text style={{color:c.muted,fontSize:12}}>Descrição</Text><TextInput ref={input} accessibilityLabel="Descrição" editable={!disabled} multiline onSelectionChange={e=>{selection.current=e.nativeEvent.selection;}} onChangeText={v=>commit(editBlockText(block,v,typing))} placeholder="Descrição da tarefa" placeholderTextColor={c.muted} style={{color:c.text,fontSize:16,lineHeight:24,minHeight:110,textAlignVertical:'top',padding:14,borderRadius:14,borderWidth:1,borderColor:c.line,backgroundColor:c.input}}>{textRuns(block).map((r,i)=><Text key={i} style={runStyle(r.style)}>{r.text}</Text>)}</TextInput><ScrollView horizontal showsHorizontalScrollIndicator={false} keyboardShouldPersistTaps="always" contentContainerStyle={{gap:5}}>{[['bold','B','Negrito'],['italic','I','Itálico'],['underline','U','Sublinhado'],['strike','S','Riscado'],['code','<>','Código']].map(([key,label,name])=><Pressable key={key} disabled={disabled} accessibilityRole="button" accessibilityLabel={name+' na descrição'} onPress={()=>toggle(key as 'bold')} style={{padding:12,borderRadius:10,backgroundColor:c.surface}}><Text style={{color:c.text,fontWeight:key==='bold'?'700':'400',fontStyle:key==='italic'?'italic':'normal'}}>{label}</Text></Pressable>)}<Pressable disabled={disabled} accessibilityLabel="Cor do texto da descrição" onPress={()=>setPalette(p=>p==='color'?null:'color')} style={{padding:12}}><Text style={{color:c.accent}}>Cor</Text></Pressable><Pressable disabled={disabled} accessibilityLabel="Grifar descrição" onPress={()=>setPalette(p=>p==='highlight'?null:'highlight')} style={{padding:12}}><Text style={{color:c.accent}}>Grifo</Text></Pressable></ScrollView>{palette?<View style={{flexDirection:'row',gap:12,flexWrap:'wrap'}}>{['#D94B57','#B77713','#378E78','#659DF2','#B497F5','#FFF59D',''].map(color=><Pressable key={color} accessibilityLabel={color?'Usar '+color:'Remover cor'} onPress={()=>{mark({[palette]:color});setPalette(null);}} style={{width:36,height:36,borderRadius:18,backgroundColor:color||c.surface,borderWidth:1,borderColor:c.line,justifyContent:'center',alignItems:'center'}}>{!color?<Text style={{color:c.text}}>×</Text>:null}</Pressable>)}</View>:null}<Text style={{color:c.muted,fontSize:11}}>Selecione um trecho para formatar ou ative um estilo antes de escrever.</Text></View>;
}
