import React from 'react';
import { View, Text, Pressable, ActivityIndicator, StyleSheet } from 'react-native';
import { useTheme } from '../lib/theme';
import { Icon, IconName } from './Icon';
export function IconButton({name,label,onPress,disabled=false,filled=false,size=44}:{name:IconName;label:string;onPress:()=>void;disabled?:boolean;filled?:boolean;size?:number}) {
 const c=useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({pressed})=>({height:size,width:size,borderRadius:size/2,alignItems:'center',justifyContent:'center',backgroundColor:filled?c.accent:'transparent',opacity:disabled?0.35:pressed?0.6:1})}><Icon name={name} color={filled?(c.accent==='#7258E8'?'#FFFFFF':'#21172F'):c.text}/></Pressable>;
}
export function Button({title,onPress,loading=false,disabled=false,secondary=false}:{title:string;onPress:()=>void;loading?:boolean;disabled?:boolean;secondary?:boolean}) {
 const c=useTheme(); return <Pressable accessibilityRole="button" disabled={disabled||loading} onPress={onPress} style={({pressed})=>({minHeight:50,borderRadius:16,paddingHorizontal:18,alignItems:'center',justifyContent:'center',backgroundColor:secondary?c.accentSoft:c.accent,opacity:disabled?0.4:pressed?0.7:1})}>{loading?<ActivityIndicator color={secondary?c.accent:'#FFFFFF'}/>:<Text style={{fontSize:15,fontWeight:'700',color:secondary?c.accent:'#FFFFFF'}}>{title}</Text>}</Pressable>;
}
export function Brand({size=44,label='S'}:{size?:number;label?:string}) { const c=useTheme();return <View style={{width:size,height:size,borderRadius:size/2,backgroundColor:c.accent,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:size*.4,fontWeight:'700',color:'#FFFFFF'}}>{label}</Text></View>; }
export function Empty({title,body,icon='chat'}:{title:string;body:string;icon?:IconName}) { const c=useTheme();return <View style={{alignItems:'center',padding:32,gap:12}}><View style={{padding:18,borderRadius:28,backgroundColor:c.accentSoft}}><Icon name={icon} color={c.accent} size={28}/></View><Text style={{fontSize:20,fontWeight:'600',color:c.text,textAlign:'center'}}>{title}</Text><Text style={{fontSize:14,lineHeight:22,color:c.muted,textAlign:'center'}}>{body}</Text></View>; }
export function ErrorBanner({text,onRetry}:{text:string;onRetry?:()=>void}) {const c=useTheme();return <View accessibilityRole="alert" style={{backgroundColor:c.dangerBg,padding:14,borderRadius:14,margin:12,gap:6}}><Text style={{color:c.danger,fontSize:13,lineHeight:19}}>{text}</Text>{onRetry&&<Pressable onPress={onRetry} accessibilityRole="button" style={{minHeight:36,justifyContent:'center'}}><Text style={{fontWeight:'700',color:c.danger}}>Tentar novamente</Text></Pressable>}</View>;}
export function ScreenTitle({title,eyebrow='SOFIA',right}:{title:string;eyebrow?:string;right?:React.ReactNode}) {const c=useTheme();return <View style={{paddingHorizontal:22,paddingTop:20,paddingBottom:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12}}><View style={{flex:1}}><Text style={{fontSize:10,letterSpacing:2,color:c.accent,fontWeight:'700',marginBottom:7}}>{eyebrow}</Text><Text style={{fontSize:29,letterSpacing:-1,fontWeight:'700',color:c.text}}>{title}</Text></View>{right}</View>;}
export const forms=StyleSheet.create({input:{minHeight:52,borderWidth:1,borderRadius:14,paddingHorizontal:15,fontSize:16},label:{fontSize:12,fontWeight:'600',marginBottom:8},card:{padding:20,borderRadius:22,gap:14},body:{fontSize:14,lineHeight:22}});
