import type {AgendaItem,Entity,Task} from './types';
export function localDateKey(input:Date|string):string{if(typeof input==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(input))return input;const d=input instanceof Date?input:new Date(input);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function monthCells(month:Date):(Date|null)[]{const out:(Date|null)[]=Array.from({length:month.getDay()},()=>null);for(let day=1;day<=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();day++)out.push(new Date(month.getFullYear(),month.getMonth(),day));while(out.length%7)out.push(null);return out;}
export type DayRecord={id:string;title:string;date:string;kind:string;location?:string;isTask:boolean;original:AgendaItem|Task};
export function dayRecords(events:AgendaItem[],tasks:Task[]):DayRecord[]{return [...events.filter(e=>!['cancelled','archived','completed','done'].includes(e.state)).map(e=>({id:e.id,title:e.title,date:e.data.calendar_all_day?e.data.calendar_date_start||'':e.data.start_at||e.data.remind_at||e.data.due_at||'',kind:e.kind,location:e.data.location,isTask:false,original:e})),...tasks.filter(t=>!['done','cancelled'].includes(t.state)&&t.due_at).map(t=>({id:t.id,title:t.title,date:t.due_at||'',kind:'task',isTask:true,original:t}))].filter(x=>x.date&&Number.isFinite(Date.parse(x.date))).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)||a.id.localeCompare(b.id));}
export function stableProductColor(id:string):string{let hash=2166136261;for(const char of id)hash=Math.imul(hash^char.charCodeAt(0),16777619);return `hsl(${(hash>>>0)%360}, 63%, 52%)`;}
export type PricePoint={time:number;value:number;observed_at:string;id:string};
export function observationPoints(rows:Record<string,any>[]):PricePoint[]{return rows.filter(r=>Number.isFinite(Number(r.total_cents))&&r.total_cents!==null&&r.total_cents!==undefined&&r.total_cents!==''&&Number(r.total_cents)>=0&&Number.isFinite(Date.parse(r.observed_at))).map(r=>({time:Date.parse(r.observed_at),value:Number(r.total_cents)/100,observed_at:r.observed_at,id:String(r.id)})).sort((a,b)=>a.time-b.time);}
export type PriceSeries={monitor:Entity;points:PricePoint[];color:string;currency:string};
export function priceGeometry(series:PriceSeries[],width=320,height=140){const all=series.flatMap(s=>s.points);if(!all.length)return null;const xmin=Math.min(...all.map(p=>p.time)),xmax=Math.max(...all.map(p=>p.time));let ymin=Math.min(...all.map(p=>p.value)),ymax=Math.max(...all.map(p=>p.value));const pad=(ymax-ymin||Math.max(1,ymax*.05))*.12;ymin=Math.max(0,ymin-pad);ymax+=pad;return {xmin,xmax,ymin,ymax,lines:series.map(s=>({id:s.monitor.id,color:s.color,points:s.points.map(p=>[12+(p.time-xmin)/(xmax-xmin||1)*(width-24),8+(1-(p.value-ymin)/(ymax-ymin||1))*(height-16)] as const)}))};}
