'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const d=require('./delivery.cjs');
const config=(v='0.3.47',code=52)=>({version:v,android:{package:'com.avsord.sofiaapp',versionCode:code}});
const release=v=>({tag_name:'sofia-android-v'+v,draft:false,prerelease:false,published_at:'2026-10-07T13:26:41Z',assets:[{name:'Sofia-OS.apk',state:'uploaded',size:50000000}]});
const files=['SOFIA_APP/src/screens/Home.tsx'];
test('version order is numeric and malformed versions fail closed',()=>{assert.equal(d.compare('0.3.100','0.3.99'),1);for(const v of ['0.03.1','1.2','a','1.2.3;echo BAD','1.2.3\n','9007199254740992.0.0'])assert.throws(()=>d.version(v));});
test('baseline excludes drafts, prereleases and incomplete APK uploads',()=>{assert.equal(d.newest([release('0.3.9'),{...release('0.3.999'),draft:true},{...release('0.3.998'),prerelease:true},{...release('0.3.997'),assets:[]},release('0.3.47')]).tag_name,'sofia-android-v0.3.47');assert.throws(()=>d.newest([]));assert.throws(()=>d.newest({}));});
test('a completed app change automatically advances version and Android code',()=>{const p=d.plan(config(),config(),[release('0.3.47')],files);assert.equal(p.release,true);assert.equal(p.version,'0.3.48');assert.equal(p.version_code,53);assert.equal(p.baseline_tag,'sofia-android-v0.3.47');});
test('a manually prepared valid higher identity is kept',()=>{const p=d.plan(config('0.3.49',55),config(),[release('0.3.47')],files);assert.equal(p.version,'0.3.49');assert.equal(p.version_code,55);});
test('reserved draft and orphan tags cannot collide with the next release',()=>{const p=d.plan(config(),config(),[release('0.3.47'),{...release('0.3.49'),draft:true}],files,['sofia-android-v0.3.50']);assert.equal(p.version,'0.3.51');});
test('restarting an unpublished prepared build does not keep bumping it',()=>{const p=d.plan(config('0.3.48',53),config(),[release('0.3.47')],files);assert.equal(p.version,'0.3.48');assert.equal(p.version_code,53);});
test('an unchanged app never rebuilds or replaces the published APK',()=>{const p=d.plan(config(),config(),[release('0.3.47')],[]);assert.equal(p.release,false);assert.equal(p.version,'0.3.47');});
test('pipeline and test-only edits do not manufacture an app release',()=>{const changed=['AGENTS.md','.github/workflows/sofia-native-047-update.yml','SOFIA_APP/tools/delivery.cjs','SOFIA_APP/tools/delivery.test.cjs','SOFIA_APP/tests/navigation.test.cjs','SOFIA_APP/RELEASE_0.3.47.md'];assert.ok(changed.every(f=>!d.runtimeFile(f)));assert.equal(d.plan(config(),config(),[release('0.3.47')],changed).release,false);});
test('native config, assets, dependencies and unknown build tools are not missed',()=>{for(const f of ['app.json','index.ts','package-lock.json','plugins/with-calendar-gesture.cjs','assets/icon.png','tools/assets.cjs','tools/normalize-source.cjs','tools/new-build-step.cjs'])assert.equal(d.runtimeFile('SOFIA_APP/'+f),true,f);});
test('an old source branch is not repackaged with a misleading higher version',()=>{assert.throws(()=>d.plan(config('0.3.22',27),config(),[release('0.3.47')],files),/older/);});
test('package changes and invalid or exhausted native codes are rejected',()=>{assert.throws(()=>d.plan({...config(),android:{package:'wrong',versionCode:53}},config(),[],files));assert.throws(()=>d.plan(config('0.3.47',NaN),config(),[],files));assert.throws(()=>d.plan(config('0.3.47',2100000000),config('0.3.47',2100000000),[],files));});
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'sofia-delivery-test-')),app=path.join(root,'SOFIA_APP');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const f of ['src/lib','tests'])fs.mkdirSync(path.join(app,f),{recursive:true});const put=(f,s)=>fs.writeFileSync(path.join(app,f),s),get=f=>fs.readFileSync(path.join(app,f),'utf8');put('package.json',JSON.stringify({version:'0.3.47',dependencies:{preserve:'1'}}));put('app.json',JSON.stringify({expo:config()}));put('package-lock.json',JSON.stringify({version:'0.3.47',packages:{'':{version:'0.3.47'}}}));put('src/lib/update.ts',"export const APP_VERSION = '0.3.47';\nconst RELEASE_PREFIX = 'sofia-android-v';");const check="assert.equal(config.version,'0.3.47');assert.equal(config.android.versionCode,52);assert.ok(updater.includes(\"APP_VERSION = '0.3.47'\"));assert.equal(userData,'preserve');";for(const f of ['navigation','release-024'])put('tests/'+f+'.test.cjs',check);return {root,app,put,get};}
test('preparation updates all identities together without touching behavior checks',t=>{const f=fixture(t),p=d.plan(config(),config(),[release('0.3.47')],files);d.prepareFiles(f.root,p);for(const file of ['package.json','package-lock.json'])assert.equal(JSON.parse(f.get(file)).version,'0.3.48');assert.equal(JSON.parse(f.get('app.json')).expo.android.versionCode,53);assert.equal(JSON.parse(f.get('package.json')).dependencies.preserve,'1');assert.ok(f.get('src/lib/update.ts').includes("APP_VERSION = '0.3.48'"));for(const name of ['navigation','release-024']){const s=f.get('tests/'+name+'.test.cjs');assert.ok(s.includes("assert.equal(config.version,'0.3.48')"));assert.ok(s.includes('assert.equal(config.android.versionCode,53)'));assert.ok(s.includes("assert.equal(userData,'preserve')"));}assert.ok(f.get('RELEASE_0.3.48.md').includes('0.3.48'));});
test('authored release notes are retained',t=>{const f=fixture(t);f.put('RELEASE_0.3.48.md','My reviewed scope');d.prepareFiles(f.root,{version:'0.3.48',version_code:53,baseline_version:'0.3.47'});assert.equal(f.get('RELEASE_0.3.48.md'),'My reviewed scope');});
test('unexpected updater layout fails before any metadata file is written',t=>{const f=fixture(t),before=f.get('package.json');f.put('src/lib/update.ts','unexpected format');assert.throws(()=>d.prepareFiles(f.root,{version:'0.3.48',version_code:53}),/declaration/);assert.equal(f.get('package.json'),before);});
test('unexpected version-test layout fails before any metadata file is written',t=>{const f=fixture(t),before=f.get('package.json');f.put('tests/navigation.test.cjs','unexpected format');assert.throws(()=>d.prepareFiles(f.root,{version:'0.3.48',version_code:53}),/test layout/);assert.equal(f.get('package.json'),before);});
const cp=require('node:child_process');
function cliFixture(t){const f=fixture(t);fs.mkdirSync(path.join(f.app,'tools'));fs.copyFileSync(__filename.replace('delivery.test.cjs','delivery.cjs'),path.join(f.app,'tools/delivery.cjs'));const git=(...args)=>cp.execFileSync('git',args,{cwd:f.root,encoding:'utf8'}).trim();git('init','-q');git('config','user.name','Test');git('config','user.email','test@example.invalid');git('add','.');git('commit','-qm','baseline');git('tag','sofia-android-v0.3.47');const bin=path.join(f.root,'bin');fs.mkdirSync(bin);fs.writeFileSync(path.join(bin,'gh'),`#!/usr/bin/env node\nconst args=process.argv.slice(2).join(' ');if(args.includes('/git/ref/'))console.log(JSON.stringify({object:{sha:process.env.MOCK_REMOTE_SHA}}));else if(args.includes('/releases?'))console.log(process.env.MOCK_RELEASES);else process.exit(1);\n`,{mode:0o755});const invoke=()=>cp.execFileSync(process.execPath,[path.join(f.app,'tools/delivery.cjs'),'prepare'],{cwd:f.root,encoding:'utf8',env:{...process.env,PATH:bin+path.delimiter+process.env.PATH,GITHUB_REPOSITORY:'avsord/sofiaos',GITHUB_REF:'refs/heads/sofia-app-android',MOCK_REMOTE_SHA:git('rev-parse','HEAD'),MOCK_RELEASES:JSON.stringify([[release('0.3.47')]]),GITHUB_OUTPUT:path.join(f.root,'output'),GITHUB_ENV:path.join(f.root,'env')}});return {...f,git,invoke};}
test('CLI skips the real git diff of a pipeline-only commit',t=>{const f=cliFixture(t);f.put('tools/delivery.test.cjs','// tests only');f.git('add','SOFIA_APP');f.git('commit','-qm','delivery tests');const p=JSON.parse(f.invoke());assert.equal(p.release,false);assert.equal(JSON.parse(f.get('app.json')).expo.version,'0.3.47');});
test('CLI emits next-version outputs and prepares a complete app-change snapshot',t=>{const f=cliFixture(t);f.put('src/changed.ts','export const changed=true;');f.git('add','SOFIA_APP');f.git('commit','-qm','app change');const p=JSON.parse(f.invoke());assert.equal(p.release,true);assert.equal(p.version,'0.3.48');assert.equal(JSON.parse(f.get('app.json')).expo.android.versionCode,53);assert.ok(fs.readFileSync(path.join(f.root,'env'),'utf8').includes('SOFIA_RELEASE_VERSION=0.3.48'));assert.ok(fs.readFileSync(path.join(f.root,'output'),'utf8').includes('release=true'));});
