'use strict';
const path=require('node:path');const {Store}=require('../memory/store');
const {KeyStore,BackupService}=require('../services/backup');const {SofiaCore}=require('./sofia-core');const {createHandler}=require('./http-handler');const {seed}=require('./seed');const {seed45}=require('./seed45');
const {Workspace}=require('./workspace');const {UsageService}=require('../services/usage');const {AudioService}=require('../services/audio');const {loadPersistedCredentials}=require('../services/credentials');const {seed46}=require('./seed46');const {seed47}=require('./seed47');const {seed48}=require('./seed48');const {seed52}=require('./seed52');const {seed58}=require('./seed58');const {seed59}=require('./seed59');const {seed61}=require('./seed61');const {RoutingService}=require('../services/routing');const {VaultService}=require('../services/vault');const {Scheduler}=require('../services/scheduler');
function createRuntime(config,options={}){
 loadPersistedCredentials(config);
 const store=options.store||new Store(path.join(config.dataDir,'sofia.sqlite'));seed(store);const workspace=new Workspace(store);seed45(store,workspace);seed46(store,workspace);seed47(store,workspace);seed48(store,workspace);seed52(store,workspace);seed58(store,workspace);seed59(store,workspace);seed61(store,workspace);
 const organizationMarker=store.db.prepare("SELECT value FROM settings WHERE key='libraryOrganization035'").get();
 if(!organizationMarker){store.tx(()=>{const legacy=new Set(['AVSORD','AVSORD Studio','AVSORD Technology','Enjoy The Void','Assets','Sofia OS','Pessoal','Geral','Estudos']);const {CATALOG}=require('./catalog');for(const e of workspace.list({group:'library',limit:500})){if(!legacy.has(e.area)||e.tags.includes('sofia-library-area-v1'))continue;const property=!['Pessoal','Geral','Estudos','Assets'].includes(e.area)&&!e.tags.some(t=>t.startsWith('sofia-property-v1:'))?['sofia-property-v1:'+e.area]:[];let area=CATALOG[e.kind].label;const member=e.tags.find(t=>t.startsWith('sofia-library-in-v1:'));if(member){try{area=workspace.get(member.slice('sofia-library-in-v1:'.length)).title;}catch{}}if(e.tags.length+property.length<=20)workspace.save({...e,area,tags:[...e.tags,...property]},e.id);}store.db.prepare('INSERT OR REPLACE INTO settings VALUES (?,?)').run('libraryOrganization035','true');});}
 let current=store.settings();
 // v133: inicializa o e-mail pessoal a partir do segredo/configuração de ambiente sem publicá-lo no Git/ZIP.
 if(config.loginEmail&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(config.loginEmail)){const marker=store.db.prepare('SELECT value FROM settings WHERE key=?').get('ownerLoginEmailV133Initialized');if(!marker){if(!current.profileEmail||String(current.profileEmail).toLowerCase()==='sofiaos.core@gmail.com')store.updateSettings({profileEmail:config.loginEmail});store.db.prepare('INSERT OR REPLACE INTO settings VALUES (?,?)').run('ownerLoginEmailV133Initialized',JSON.stringify(true));current=store.settings();}}
 // Migração personalizada da instalação local: a chave OPENAI_API_KEY existente era a chave do projeto compartilhado/cortesia já usada antes da v44.
 // Isso elimina a tela de primeiro uso sem inventar uma chave privada. Mensagens privadas continuam bloqueadas até o projeto privado ser configurado.
 if(config.apiKey&&!config.privateApiKey&&!config.sharedApiKey&&!current.routingEnabled&&current.legacyRoute==='none'){store.updateSettings({routingEnabled:true,privacyMode:'auto',legacyRoute:'shared',sharedConfirmed:true,sharedBillingAcknowledged:true});current=store.settings();}
 // v139: a presença explícita de OPENAI_PRIVATE_API_KEY no ambiente do servidor é a fonte de verdade
 // para o Filtro Privado online. Isso sincroniza web e app após redeploy sem gravar a chave no banco.
 // Não há fallback silencioso para a chave compartilhada: se a variável privada não existir, o Privado continua bloqueado.
 if(config.privateApiKey||(config.apiKey&&current.legacyRoute==='private')){const updates={};if(!current.routingEnabled)updates.routingEnabled=true;if(!current.privateConfirmed)updates.privateConfirmed=true;if(Object.keys(updates).length){store.updateSettings(updates);current=store.settings();}}
 const vault=new VaultService(store,{secureDir:options.secureDir});const routing=new RoutingService(store,config,options.providerFactory||(options.provider?()=>options.provider:undefined));
 const backups=new BackupService(store,config.backupDir,new KeyStore(options.secureDir));backups.vault=vault;
 const usageService=options.usageService||new UsageService(store,config,routing,options.fetchImpl||global.fetch);const audioService=options.audioService||new AudioService(config,options.fetchImpl||global.fetch);const core=new SofiaCore({store,config,workspace,routing,usageService});const scheduler=new Scheduler(workspace,{config,...options.schedulerOptions});
 const runtime={store,backups,core,config,workspace,routing,usageService,audioService,vault,scheduler,ownerAuth:options.ownerAuth,accountMailer:options.accountMailer};runtime.handler=createHandler(runtime);return runtime;
}
module.exports={createRuntime};
