'use strict';
function seed46(store,w){if(store.db.prepare("SELECT key FROM settings WHERE key='seedV46'").get())return;
 store.tx(()=>{
  for(const note of [
   {kind:'decision',title:'Interface em duas camadas',area:'Sofia OS',content:'A Sofia terá duas camadas: interface do usuário e visão de desenvolvimento. O usuário final não precisa ver Fluxo Ativo, Memória técnica, filtros, contexto, labels de roteamento ou diagnóstico. A visão de desenvolvimento continua disponível nesta fase para Pedro auditar e construir o sistema, mas deve ser bloqueada para usuários públicos.',pinned:true},
   {kind:'decision',title:'Início como panorama do usuário',area:'Sofia OS',content:'A Home do usuário chama-se Início. Ela reúne uma barra compacta de conversa com a Sofia, sino de notificações e widgets pré-definidos, como prioridades, mini agenda/compromissos, estudos, listas e atividades recentes. O botão Chat volta ao Início e inicia uma sessão visual limpa. Os widgets têm tamanhos pré-definidos para preservar organização visual; o usuário escolhe quais aparecem e sua ordem.',pinned:true},
   {kind:'decision',title:'Navegação do usuário inspirada em organização tipo Notion',area:'Sofia OS',content:'A experiência do usuário deve ser simples e modular: Início, Tarefas, Compromissos, Listas, Biblioteca, Estudos, Diário Pessoal/Safe Chat e espaços personalizados. A seção Seus Espaços começa vazia em instalações novas. O usuário pode criar páginas manualmente ou pedir à Sofia; quando surgir um novo espaço, a Sofia deve sugerir e pedir confirmação antes de criar para evitar bagunça.',pinned:true},
   {kind:'decision',title:'Fluxo Ativo como órgão interno',area:'Sofia OS',content:'Fluxo Ativo é a visão interna das intenções em movimento, como pontos ativos vistos de cima: tarefas, compromissos, projetos, sonhos, rotinas, compras, monitoramentos, solicitações, oportunidades e automações. A Fazer é apenas uma visão interna. Mercado e Farmácia são listas separadas; ciclo mensal vira frequência em Rotinas/Recorrências; automação externa planejada é estado/propriedade, não categoria; demanda vira Solicitação; candidatura entra em Oportunidades; saída/conferência vira Checklist de saída.',pinned:true},
   {kind:'decision',title:'Filtros de IA automáticos e invisíveis',area:'Sofia OS',content:'No uso normal, a pessoa não escolhe rota a cada mensagem. A Sofia usa automaticamente Filtro Compartilhado para conteúdo claramente geral e autorizado e Filtro Privado para conteúdo pessoal, sensível, confidencial ou incerto. Na dúvida, Privado. Ambos podem usar contexto compatível. A decisão, origem automática/manual e se houve contexto ficam registradas para auditoria e aprendizado por correção.',pinned:true},
   {kind:'decision',title:'Histórico, memória e contexto são camadas diferentes',area:'Sofia OS',content:'Histórico é o registro bruto cronológico. Memória é o conjunto persistente e curado do que importa. Contexto é o pacote temporário montado na hora com mensagens recentes, memórias e registros relevantes para responder ao pedido atual. Contexto não é exclusivo do Filtro Privado; o Filtro Compartilhado pode usar contexto geral autorizado.',pinned:true},
   {kind:'decision',title:'Safe Chat substitui modos locais visíveis',area:'Sofia OS',content:'O antigo Meditações Cofre evolui para Safe Chat. Não haverá um botão normal de Somente Local na experiência pública; o roteamento é automático. Conteúdo protegido deve nascer cifrado no armazenamento. O Safe Chat usa somente Filtro Privado quando chama IA. Dentro dele há categorias como Diário Pessoal, Meditação e Registro Protegido. Não prometer anonimato, segurança absoluta ou criptografia ponta a ponta quando não for tecnicamente verdade.',pinned:true},
   {kind:'decision',title:'Diário Pessoal dentro do Safe Chat',area:'Sofia OS',content:'Diário Pessoal é um espaço intuitivo para reflexões e cotidiano. Quanto mais a pessoa registra de forma autorizada, mais contexto a Sofia pode usar para compreender seu ecossistema pessoal, sem transformar inferências em fatos. O texto deve ser armazenado cifrado e o acesso deve respeitar autenticação e escopo.',pinned:true},
   {kind:'rule',title:'Estudos e Biblioteca normalmente compartilháveis',area:'Sofia OS',content:'Cursos, progresso de estudos, filmes, músicas, trilhas, vídeos, leituras, receitas e referências gerais podem usar Filtro Compartilhado por padrão quando não contiverem dados pessoais, confidenciais, proprietários ou de terceiros. Se o usuário corrigir um item para Privado, registrar o feedback para casos semelhantes.',pinned:true},
   {kind:'decision',title:'Monitoramento de curso significa progresso',area:'Sofia OS',content:'Em Estudos, acompanhar/monitorar um curso significa registrar nível, progresso, dificuldades, pontos fortes, evidências e próximo passo. Não usar formulário de variante/preço para curso. Monitoramento de preço pertence a compras/produtos.',pinned:true},
   {kind:'decision',title:'Listas e Biblioteca na experiência do usuário',area:'Sofia OS',content:'Listas é um guarda-chuva para Mercado, Farmácia, Comprar, Black Friday e outros conjuntos. Mercado e Farmácia permanecem independentes. Biblioteca reúne filmes, músicas/trilhas, vídeos para assistir, livros/leituras, referências e outras coleções pessoais. Black Friday é ocasião/filtro e monitoramento é capacidade; não duplicar o produto.',pinned:true},
   {kind:'decision',title:'Labels, origem e linha do tempo',area:'Sofia OS',content:'Registros devem carregar labels consistentes, origem, data/hora, versões e relações. Metadados de roteamento também registram Filtro usado, escolha automática/manual e uso de contexto. Isso permite consultar depois, por exemplo, o que foi tratado pelo Filtro Privado ou Compartilhado e acompanhar a evolução temporal das decisões.',pinned:true},
   {kind:'decision',title:'Aprendizado por correções de privacidade',area:'Sofia OS',content:'O usuário pode dizer que um conteúdo deveria ser Privado ou Compartilhado. A correção deve atualizar o registro e alimentar regras locais revisáveis para casos semelhantes. Nunca mover algo sensível para Compartilhado apenas para economizar; a dúvida continua indo para Privado.',pinned:true},
   {kind:'decision',title:'AVSORD — nome correto e estrutura',area:'AVSORD',content:'Grafia oficial de trabalho: AVSORD. AVSORD é Estúdio de Criação e Tecnologia. AVSORD Studio reúne publicidade, motion design, 3D, audiovisual e direção visual. AVSORD Technology reúne Sofia, Anchor Track e futuros softwares. Labs foi descartado por transmitir caráter experimental demais. Enjoy The Void permanece independente.',pinned:true}
  ])store.saveNote(note);
  store.db.prepare("INSERT INTO settings VALUES('seedV46','true')").run();
 });
}
module.exports={seed46};
