'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),load=require('./load-ts.cjs');
const hierarchy=load('src/lib/page-hierarchy.ts'),order=load('src/lib/page-order.ts',{'./page-hierarchy':hierarchy});
const {LegacyMdAdapter,legacyMovePlan}=load('src/lib/legacy-md.ts',{'./page-hierarchy':hierarchy,'./page-order':order});
const page=(id,parent='')=>({id,kind:'user_page',title:id,state:'active',revision:1,data:{parent_id:parent,icon:'🖤',blocks_json:'[{"type":"text","text":"Preservar"}]'}});
const disk=()=>{const map=new Map();return {getItem:async k=>map.get(k)||null,setItem:async(k,v)=>map.set(k,v)};};
const missing=()=>{throw Object.assign(Error('Not found'),{status:404});};
function fixture(){const storage=disk(),a=page('A'),b=page('B','A'),c=page('C'),pages=[a,b,c],calls=[];const call=async(path,body,method)=>{calls.push({path,body,method});if(path==='/md/capabilities')missing();if(path.startsWith('/workspace/entities?'))return {items:pages};if(path==='/workspace/entities/B'){assert.equal(method,'PATCH');assert.equal(body.revision,1);assert.equal(body.data.sort_order,undefined);Object.assign(b,{revision:2,data:body.data});return b;}throw Error('Unexpected '+path);};return {storage,pages,calls,call,adapter:new LegacyMdAdapter(call,storage,'owner')};}
test('legacy mode is cached and only used for 404, never auth or server failure',async()=>{let n=0;const a=new LegacyMdAdapter(async()=>{n++;missing();},disk(),'owner');assert.equal(await a.supports(),false);assert.equal(await a.supports(),false);assert.equal(n,1);for(const status of [401,403,500]){const b=new LegacyMdAdapter(async()=>{throw Object.assign(Error('blocked'),{status});},disk(),'owner');await assert.rejects(b.supports());assert.equal(b.localOnly,false);}});
test('hierarchy update on old server preserves identity, content and revision',async()=>{const f=fixture(),r=await f.adapter.move({id:'B',revision:1,parentId:'',anchorId:'A',kind:'after'}),p=r.items.find(x=>x.id==='B');assert.equal(p.data.parent_id,'');assert.equal(p.data.icon,'🖤');assert.equal(p.title,'B');assert.match(p.data.blocks_json,/Preservar/);assert.equal(p.revision,2);assert.equal(f.calls.filter(c=>c.method==='PATCH').length,1);});
test('legacy order survives reopen and remains isolated by account',async()=>{const f=fixture();await f.adapter.move({id:'C',revision:1,parentId:'',anchorId:'A',kind:'before'});assert.equal(f.calls.filter(c=>c.method==='PATCH').length,0);const a=new LegacyMdAdapter(f.call,f.storage,'owner'),rows=(await a.decorate(f.pages)).filter(p=>!p.data.parent_id).sort(order.comparePageOrder);assert.equal(rows[0].id,'C');const b=new LegacyMdAdapter(f.call,f.storage,'another-owner');assert.equal((await b.decorate(f.pages))[0].data.sort_order,undefined);});
test('legacy movement refuses stale revision, cycles and moved anchor',()=>{const {pages}=fixture();assert.throws(()=>legacyMovePlan(pages,{id:'A',revision:1,parentId:'B',anchorId:'B',kind:'inside'}));assert.throws(()=>legacyMovePlan(pages,{id:'C',revision:9,parentId:'',anchorId:'A',kind:'before'}));assert.throws(()=>legacyMovePlan(pages,{id:'C',revision:1,parentId:'B',anchorId:'A',kind:'after'}));});
test('legacy notification pagination uses one snapshot and refuses new local-only dismissals',async()=>{const storage=disk(),items=Array.from({length:250},(_,i)=>({id:String(i),state:'unread'}));let reads=0;const call=async p=>{if(p==='/md/capabilities')missing();if(p==='/notifications'){reads++;return {items};}throw Error(p);};const a=new LegacyMdAdapter(call,storage,'owner');assert.equal((await a.notices()).items.length,100);assert.equal((await a.notices(100)).items.length,100);assert.equal((await a.notices(200)).items.length,50);assert.equal(reads,1);await assert.rejects(a.clear('0'),/servidor/);const b=new LegacyMdAdapter(call,storage,'owner');assert.equal((await b.notices()).unread,250);await assert.rejects(b.clear('all'),/servidor/);assert.equal((await b.notices()).unread,250);});
test('new server uses MD atomic operations instead of compatibility path',async()=>{const calls=[],a=new LegacyMdAdapter(async(p,b,m)=>{calls.push(p);if(p==='/md/capabilities')return {page_order:true};if(p==='/md/pages/move')return {items:[page('A')]};if(m==='DELETE')return {ok:true};throw Error(p);},disk(),'owner');await a.move({id:'A',revision:1,parentId:'',kind:'before',anchorId:'B'});await a.clear('all');assert.equal(a.localOnly,false);assert.ok(calls.includes('/md/pages/move'));assert.ok(calls.includes('/md/notifications/all'));});
test('failed local order write is reported, never claimed as remotely saved',async()=>{const f=fixture();f.storage.setItem=async()=>{throw Error('disk full');};await assert.rejects(f.adapter.move({id:'C',revision:1,parentId:'',anchorId:'A',kind:'before'}),/disk full/);});
