'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),load=require('./load-ts.cjs');
function fixture(){const stub=require('./animated-stub.cjs')(),tabs=load('src/lib/tab-navigation.ts');const model=load('src/lib/menu-motion.ts',{'react-native':{Animated:stub.Animated},'./tab-navigation':tabs});const motion=model.createMenuMotion('chat');motion.resize(400,'chat');return {...stub,...model,motion};}
const event=x=>({nativeEvent:{contentOffset:{x,y:0}}});
test('native position changes the purple labels before a swipe completes',()=>{const f=fixture();f.motion.beginDrag(400);for(const x of [440,500,600,700,760]){f.motion.onScroll(event(x));assert.ok(Math.abs(f.read(f.motion.weights[1])-f.menuWeight(x/400,1))<.001);assert.ok(f.read(f.motion.weights[2])>0);}assert.equal(f.motion.onScroll.nativeDriver,true);assert.equal(f.springs.length,0);});
test('origin shrinks and destination grows continuously and reverse with the finger',()=>{const f=fixture();f.motion.beginDrag(400);for(const x of [480,540,600,680,600,540,480,400]){f.motion.onScroll(event(x));assert.ok(Math.abs(f.read(f.motion.weights[1])+f.read(f.motion.weights[2])-1)<.001);}assert.equal(f.read(f.motion.weights[1]),1);assert.equal(f.read(f.motion.weights[2]),0);});
test('ending a swipe does not launch a second delayed label animation',()=>{const f=fixture();f.motion.beginDrag(400);f.motion.onScroll(event(800));f.motion.settle('pages',800);f.motion.select('pages');assert.equal(f.springs.length,0);assert.equal(f.read(f.motion.weights[2]),1);});
test('tap decorative spring does not sweep through intermediate menus or require completion',()=>{const f=fixture();f.motion.select('profile');assert.equal(f.springs.length,6);assert.ok(f.springs.every(s=>s.config.useNativeDriver&&!s.config.isInteraction));f.advance(.5);assert.equal(f.read(f.motion.weights[2]),0);assert.equal(f.read(f.motion.weights[3]),0);assert.equal(f.read(f.motion.weights[4]),0);assert.ok(f.read(f.motion.weights[1])>0);assert.ok(f.read(f.motion.weights[5])>0);});
test('tap during swipe takes over from the current visible purple weights',()=>{const f=fixture();f.motion.beginDrag(400);f.motion.onScroll(event(600));f.motion.select('home');assert.equal(f.read(f.motion.weights[1]),.5);assert.equal(f.read(f.motion.weights[2]),.5);f.advance(1);assert.equal(f.read(f.motion.weights[0]),1);assert.equal(f.read(f.motion.weights[1]),0);});
test('rapid taps interrupt preceding springs and do not restart on React commit',()=>{const f=fixture();f.motion.select('pages');f.advance(.4);const old=f.springs.slice();f.motion.select('profile');assert.ok(old.every(s=>s.stopped));const count=f.springs.length;f.motion.select('profile');assert.equal(f.springs.length,count);});
test('reduced motion removes scale changes but preserves synchronized selection',()=>{const f=fixture();f.motion.setReducedMotion(true);assert.equal(f.read(f.motion.motionAmount),0);f.motion.select('pages');assert.equal(f.read(f.motion.weights[2]),1);assert.equal(f.springs.length,0);f.motion.beginDrag(800);f.motion.onScroll(event(1000));assert.equal(f.read(f.motion.weights[2]),.5);assert.equal(f.read(f.motion.weights[3]),.5);});
test('resizing, short returned swipes and notification overlays preserve a valid state',()=>{const f=fixture();f.motion.resize(600,'chat');f.motion.beginDrag(600);f.motion.onScroll(event(800));f.motion.onScroll(event(600));f.motion.settle('chat',600);f.motion.select('chat');assert.equal(f.read(f.motion.weights[1]),1);f.motion.select('notifications');f.advance(1);assert.ok(f.motion.weights.every(w=>f.read(w)===0));});
