const test=require('node:test'),assert=require('node:assert/strict'),load=require('./load-ts.cjs');
const scheduler=load('src/lib/notification-scheduler.ts');
function adapter(seed=[]){const rows=new Map(seed.map(n=>[n.identifier,n]));let peak=rows.size,fail=false;return {rows,get peak(){return peak},set fail(v){fail=v},async getAllScheduledNotificationsAsync(){return [...rows.values()]},async cancelScheduledNotificationAsync(id){rows.delete(id)},async scheduleNotificationAsync(n){rows.set(n.identifier,n);peak=Math.max(peak,rows.size);if(fail||rows.size>500)throw Error('Maximum alarms exceeded');return n.identifier}};}
const req=(id,signature='new')=>({identifier:id,content:{data:{signature}}});
test('legacy 512 persisted requests repair without creating more than 384 alarms',async()=>{const a=adapter([...Array.from({length:256},(_,i)=>req('agenda:'+i)),...Array.from({length:256},(_,i)=>req('caps:'+i))]);await scheduler.reconcileNotificationRequests(a,'caps:',Array.from({length:128},(_,i)=>req('caps:new'+i)));assert.equal(a.rows.size,384);await scheduler.reconcileNotificationRequests(a,'agenda:',Array.from({length:128},(_,i)=>req('agenda:new'+i)));assert.equal(a.rows.size,256);assert.equal(a.peak,512);});
test('failed Expo persisted request is removed and retry installs alarm',async()=>{const a=adapter([req('other:1')]);a.fail=true;await assert.rejects(scheduler.reconcileNotificationRequests(a,'caps:',[req('caps:1')]));assert(!a.rows.has('caps:1'));assert(a.rows.has('other:1'));a.fail=false;await scheduler.reconcileNotificationRequests(a,'caps:',[req('caps:1')]);assert(a.rows.has('caps:1'));});
test('shared queue serializes both channels and recovers from failure',async()=>{const order=[];const a=scheduler.enqueueNotifications(async()=>{order.push('a');await new Promise(r=>setTimeout(r,10));order.push('b');throw Error('fail')});const b=scheduler.enqueueNotifications(async()=>order.push('c'));await assert.rejects(a);await b;assert.deepEqual(order,['a','b','c']);});

const {WorkspaceRecords,LISTS_ALL}=load('src/lib/workspace-records.ts',{'react':{},'./chat-model':{errorText:e=>e.message}});
test('shopping Everything includes every list kind and later pages',async()=>{const cache=new WorkspaceRecords();await cache.load({entities:async(kind,q,offset)=>({items:offset?[]:Array.from({length:kind==='shopping_item'?100:1},(_,i)=>({id:kind+i,kind,title:kind}))})},LISTS_ALL,'',()=>{});assert.equal(cache.view(LISTS_ALL,'').items.length,104);assert.equal(cache.view(LISTS_ALL,'').hasMore,false);});
