'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),load=require('./load-ts.cjs');
const tick=()=>new Promise(r=>setImmediate(r));
function photoFixture(){
 const files=new Map([['file:///picked.jpg',100]]),values=new Map(),deleted=[];let failCopy=false,failWrite=false,copyDone=false;
 class File{constructor(a,b){this.uri=b?(typeof a==='string'?a:a.uri)+b:typeof a==='string'?a:a.uri;}get exists(){return files.has(this.uri);}get size(){return files.get(this.uri)||0;}async copy(to){await tick();if(failCopy)throw Error('copy failed');files.set(to.uri,this.size);copyDone=true;}async delete(){await tick();deleted.push(this.uri);files.delete(this.uri);}}
 const storage={getItem:async key=>values.get(key)||null,setItem:async(k,v)=>{if(failWrite)throw Error('disk full');assert.ok(files.get(v)>0);values.set(k,v);},removeItem:async k=>values.delete(k)};
 const photo=load('src/lib/profile-photo.ts',{'@react-native-async-storage/async-storage':{__esModule:true,default:storage},'expo-file-system':{File,Paths:{document:{uri:'file:///documents/'}}}});
 return{photo,files,values,deleted,failCopy:()=>{failCopy=true;},failWrite:()=>{failWrite=true;},get copyDone(){return copyDone;}};
}
test('054 profile waits for asynchronous SDK copy before validating and saving its pointer',async()=>{const f=photoFixture(),result=f.photo.saveProfilePhoto('A@example.com','file:///picked.jpg');assert.equal(f.values.size,0);const uri=await result;assert.ok(f.copyDone);assert.ok(f.files.get(uri)>0);assert.equal(await f.photo.readProfilePhoto('a@example.com'),uri);assert.equal(await f.photo.readProfilePhoto('other@example.com'),'');});
test('054 profile replacement keeps previous photo on copy failure',async()=>{const f=photoFixture(),old=await f.photo.saveProfilePhoto('a','file:///picked.jpg');f.failCopy();await assert.rejects(f.photo.saveProfilePhoto('a','file:///picked.jpg'));assert.equal(await f.photo.readProfilePhoto('a'),old);assert.ok(f.files.has(old));assert.ok(!f.deleted.includes(old));});
test('054 profile replacement keeps previous photo when metadata commit fails',async()=>{const f=photoFixture(),old=await f.photo.saveProfilePhoto('a','file:///picked.jpg');f.failWrite();await assert.rejects(f.photo.saveProfilePhoto('a','file:///picked.jpg'));assert.equal(await f.photo.readProfilePhoto('a'),old);assert.ok(f.files.has(old));});
test('054 a saved photo can itself be the source without deleting it before copy',async()=>{const f=photoFixture(),old=await f.photo.saveProfilePhoto('a','file:///picked.jpg'),next=await f.photo.saveProfilePhoto('a',old);assert.notEqual(next,old);assert.equal(await f.photo.readProfilePhoto('a'),next);assert.ok(f.files.has(next));});
test('054 explicit removal does not affect another account photo',async()=>{const f=photoFixture();await f.photo.saveProfilePhoto('a','file:///picked.jpg');const b=await f.photo.saveProfilePhoto('b','file:///picked.jpg');await f.photo.removeProfilePhoto('a');assert.equal(await f.photo.readProfilePhoto('a'),'');assert.equal(await f.photo.readProfilePhoto('b'),b);});
test('054 recovers a 0.3.53 legacy file whose copy completed after its error dialog',async()=>{const f=photoFixture(),uri=await f.photo.saveProfilePhoto('a','file:///picked.jpg'),legacy=uri.replace(/-[^-]+-\d+\.jpg$/,'.jpg');f.files.set(legacy,100);f.files.delete(uri);assert.equal(await f.photo.readProfilePhoto('a'),legacy);});
test('054 camera badge is an independently touchable sibling outside the clipped avatar',()=>{
 const jsx=(type,props)=>({type,props}),c={input:'i',line:'l',surface:'s',accent:'a'};
 const {ProfilePhotoEditor}=load('src/components/ProfilePhotoEditor.tsx',{'react':{useState:v=>[v,()=>{}],useEffect:()=>{}},'react/jsx-runtime':{jsx,jsxs:jsx},'react-native':{View:'View',Pressable:'Pressable',Image:'Image',ActivityIndicator:'Spinner',Alert:{}},'expo-image-picker':{},'./UI':{Brand:'Brand'},'./Icon':{Icon:'Icon'},'../lib/theme':{useTheme:()=>c},'../lib/chat-model':{initials:()=>'',errorText:()=>''},'../lib/profile-photo':{},'../lib/profile-photo-events':{photoChanged(){}}});
 const root=ProfilePhotoEditor({scope:'a',name:'A'}),[avatar,badge]=root.props.children;assert.equal(root.props.style.overflow,'visible');assert.equal(avatar.props.style.overflow,'hidden');assert.equal(badge.type,'Pressable');assert.equal(badge.props.testID,'profile-camera-button');assert.ok(badge.props.style.right+badge.props.style.width<root.props.style.width);assert.equal(badge.props.style.bottom,0);assert.equal(badge.props.style.borderRadius,badge.props.style.width/2);assert.ok(root.props.style.width>avatar.props.style.width);
});
const snapshot=load('src/lib/startup-snapshot.ts');
function disk(){const values=new Map();return{values,read:async k=>values.get(k)||null,write:async(k,v)=>values.set(k,v),remove:async k=>values.delete(k)};}
const chat={conversation:{id:'thread',channel:'mobile'},messages:[{id:'message',content:'kept'}],has_more:false,deleted_ids:[],current_id:'thread',cursor_revision:1};
test('054 deleting an unrelated item does not discard retained chat or its history list',async()=>{const d=disk(),s=new snapshot.StartupSnapshot(d,'account');s.remember('/chat-sync/current',chat);s.remember('/conversations?offset=0',{items:[chat.conversation]});s.remember('/home',{tasks:[]});s.forgetData();assert.equal(s.peek('/chat-sync/current').messages[0].id,'message');assert.equal(s.peek('/conversations?offset=0').items[0].id,'thread');assert.equal(s.peek('/home'),undefined);await s.clear();});
test('054 delayed hydration cannot overwrite a newer network result',async()=>{let resolve;const d=disk();d.read=()=>new Promise(r=>resolve=r);const s=new snapshot.StartupSnapshot(d,'a',()=>1000),h=s.hydrate();s.remember('/chat-sync/current',chat);resolve(JSON.stringify({schema:1,entries:[['/chat-sync/current',{at:999,value:{...chat,messages:[]}}]]}));await h;assert.equal(s.peek('/chat-sync/current').messages[0].id,'message');await s.clear();});
test('054 history does not disappear after the disposable dashboard cache expires',async()=>{const d=disk(),s=new snapshot.StartupSnapshot(d,'a',()=>100);s.remember('/chat-sync/current',chat);s.remember('/home',{tasks:[]});await s.flush();const next=new snapshot.StartupSnapshot(d,'a',()=>100+30*86400000);await next.hydrate();assert.equal(next.peek('/chat-sync/current').messages[0].id,'message');assert.equal(next.peek('/home'),undefined);await s.clear();await next.clear();});
test('054 explicit confirmed chat erasure wins over an older disk read in flight',async()=>{let resolve;const d=disk();d.read=()=>new Promise(r=>resolve=r);const s=new snapshot.StartupSnapshot(d,'a',()=>1000),h=s.hydrate();s.forgetChat();resolve(JSON.stringify({schema:1,entries:[['/chat-sync/current',{at:999,value:chat}]]}));await h;assert.equal(s.peek('/chat-sync/current'),undefined);await s.clear();});
function apiFixture(){
 const d=disk(),calls=[];let fail=false,pause=null,response=chat;
 const reads=load('src/lib/startup-preload.ts'),model=load('src/lib/chat-model.ts');
 const {SofiaApi}=load('src/lib/api.ts',{'./chat-opening':load('src/lib/chat-opening.ts'),'./startup-snapshot':snapshot,'./encrypted-storage':{encryptedStorage:d},'./startup-preload':reads,'./theme-schedule':{themeTimes:()=>({})},'./agenda-events':{agendaChanged(){}},'./system-events':{systemChanged(){}},'./chat-model':model,'./legacy-md':{LegacyMdAdapter:class{}},'expo-secure-store':{},'@react-native-async-storage/async-storage':{default:{}}},{process:{env:{}},AbortController,fetch:async(url,options)=>{calls.push({url,options});if(pause)await pause;return{ok:!fail,status:fail?500:200,json:async()=>fail?{error:'unavailable'}:response};}});
 const api=new SofiaApi('token',()=>{},'a');return{api,d,calls,fail:v=>fail=v,pause:v=>pause=v,response:v=>response=v};
}
test('054 API never erases cached messages when unrelated deletion or chat deletion fails',async()=>{const f=apiFixture();await f.api.ensureChat();f.fail(true);await assert.rejects(f.api.deleteTask('task'));assert.equal(f.api.cached('/chat-sync/current').messages[0].id,'message');await assert.rejects(f.api.clearChatHistory());assert.equal(f.api.cached('/chat-sync/current').messages[0].id,'message');f.fail(false);f.response({ok:true,conversations:1,messages:1});await f.api.clearChatHistory();assert.equal(f.api.cached('/chat-sync/current'),undefined);await f.api.discardCache();});
test('054 duplicate startup consumers share one ensureChat server operation',async()=>{const f=apiFixture();let resolve;f.pause(new Promise(r=>resolve=r));const a=f.api.ensureChat(),b=f.api.ensureChat();assert.equal(a,b);assert.equal(f.calls.length,1);resolve();await Promise.all([a,b]);await f.api.discardCache();});
test('054 partial message deletion removes only confirmed IDs from retained history',async()=>{const f=apiFixture();f.response({...chat,messages:[{id:'one'},{id:'two'}]});await f.api.ensureChat();f.response({deleted_ids:['one'],failed:[{id:'two',error:'busy'}]});await f.api.deleteChatMessages('thread',['one','two']);assert.deepEqual(Array.from(f.api.cached('/chat-sync/current').messages,m=>m.id),['two']);await f.api.discardCache();});
const agenda=load('src/lib/agenda-cache.ts');
test('054 initial agenda snapshot is already populated before its screen mounts',async()=>{let calls=0;const cache=agenda.createAgendaCache(async()=>{calls++;return{items:[]};},()=>10000);cache.seed('2026-10',{items:[{id:'existing'}]});assert.equal(cache.snapshot('2026-10').items[0].id,'existing');assert.equal(cache.snapshot('2026-10').loading,false);await cache.load('2026-10');assert.equal(calls,0);});
test('054 invalidation refreshes the agenda without replacing saved events with loading',async()=>{let finish;const cache=agenda.createAgendaCache(()=>new Promise(r=>finish=r),()=>10000);cache.seed('2026-10',{items:[{id:'existing'}]});cache.invalidate();const flight=cache.load('2026-10');assert.equal(cache.snapshot('2026-10').loading,false);assert.equal(cache.snapshot('2026-10').items[0].id,'existing');finish({items:[{id:'new'}]});await flight;assert.equal(cache.snapshot('2026-10').items[0].id,'new');});
const {prepareInitialData}=load('src/lib/startup-preparation.ts',{'./agenda-cache':agenda});
test('054 startup waits only for encrypted disk hydration and starts network without blocking launch',async()=>{const events=[];let hydrate;const api={hydrate:()=>new Promise(r=>hydrate=r),preload:()=>{events.push('network-prefetch');return new Promise(()=>{});}};let ready=false;const p=prepareInitialData(api,async()=>{}).then(()=>ready=true);await tick();assert.equal(ready,false);assert.deepEqual(events,[]);hydrate();await p;assert.equal(ready,true);assert.deepEqual(events,['network-prefetch']);});
test('054 offline existing snapshots are usable without waiting for failed network',async()=>{const api={hydrate:async()=>{},cached:()=>({}),preload:()=>new Promise(()=>{}),home:()=>new Promise(()=>{}),tasks:()=>new Promise(()=>{}),ensureChat:()=>new Promise(()=>{})};await prepareInitialData(api,()=>new Promise(()=>{}));});
test('054 offline launch stays responsive; Home exposes its own retry banner',async()=>{const offline=async()=>{throw Error('offline');};await prepareInitialData({hydrate:async()=>{},preload:offline},offline);});
test('054 active page is immediately present; hidden pages cannot block the Home frame',()=>{const react={useMemo:f=>f(),useState:v=>[v,()=>{}],useEffect:()=>{}};const {useStartupMounts}=load('src/lib/startup-mounts.ts',{'react':react});assert.deepEqual(Array.from(useStartupMounts(true,'home')),['home']);assert.deepEqual(Array.from(useStartupMounts(true,'agenda')),['home','agenda']);assert.deepEqual(Array.from(useStartupMounts(false,'home')),['home']);});
