'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),load=require('./load-ts.cjs');
const {editBlockText,formatRange,textRuns,leafBlocks}=load('src/lib/leaf-document.ts');
const {parseAttachments,attachmentText,attachmentMime}=load('src/lib/chat-attachments.ts');
const block=(text,marks=[])=>({id:'body',type:'text',text,marks});
test('existing notebook plain text is preserved without fabricating creation date',()=>{const leaf={id:'old',title:'Meu texto',content:'Primeiro\n\nSegundo'};assert.equal(leafBlocks(leaf)[0].text,leaf.content);assert.equal(leaf.created_at,undefined);});
test('format selection, combine styles and remove one style without losing other styles',()=>{let b=formatRange(block('texto inteiro'),0,5,{bold:true});b=formatRange(b,2,5,{italic:true});assert.deepEqual(JSON.parse(JSON.stringify(textRuns(b).map(r=>[r.text,!!r.style.bold,!!r.style.italic]))),[['te',true,false],['xto',true,true],[' inteiro',false,false]]);b=formatRange(b,0,5,{bold:false});assert.equal(textRuns(b).find(r=>r.text==='xto').style.italic,true);assert.ok(textRuns(b).every(r=>!r.style.bold));});
test('editing inside styled text adjusts spans and keeps untouched suffix',()=>{const b=editBlockText(block('ola mundo',[{start:4,end:9,bold:true}]),'ola lindo mundo');assert.equal(b.text,'ola lindo mundo');assert.equal(b.marks[0].end,15);assert.equal(b.marks[0].start,4);});
test('attachment references roundtrip and foreign URLs never become authenticated requests',()=>{const site='https://sofiaos.up.railway.app';const text=attachmentText([{name:'Foto.jpg',mime:'image/jpeg',attachmentId:'img-1'},{name:'Texto.pdf',mime:'application/pdf',attachmentId:'doc-1'}],site);assert.equal(parseAttachments(text,site).attachments.length,2);assert.equal(parseAttachments('[x](https://evil.example/api/attachments/x)',site).attachments.length,0);assert.equal(parseAttachments('[x](https://sofiaos.up.railway.app.evil.example/api/attachments/x)',site).attachments.length,0);assert.equal(attachmentMime('foto.PNG','application/octet-stream'),'image/png');assert.throws(()=>attachmentMime('run.exe','application/octet-stream'));});

test('typing a long bold paragraph keeps one formatting range',()=>{let b=block('');for(let i=0;i<1500;i++)b=editBlockText(b,b.text+'a',{bold:true});assert.equal(b.text.length,1500);assert.equal(b.marks.length,1);assert.equal(b.marks[0].end,1500);assert.equal(textRuns(b).length,1);});
