'use strict';
const fs=require('node:fs');const path=require('node:path');const {zipFiles}=require('./zip.cjs');const {atomicWrite,rejectSecrets,hash}=require('../src/core/util');const {VERSION}=require('../src/config/sofia');const MAJOR=VERSION.split('.')[0];
function exportCode(root,destination){const allowed=['src','public','tools','tests','docs'],files=[],skipped=[];
  function collect(folder){for(const entry of fs.readdirSync(path.join(root,folder),{withFileTypes:true})){const rel=folder+'/'+entry.name;if(entry.isSymbolicLink()){skipped.push(rel);continue;}if(entry.isDirectory()){if(!/node_modules|^\./.test(entry.name))collect(rel);}else if(/\.(?:js|cjs|md|txt|css|html|json|cmd|bat)$/i.test(entry.name)&&!/^\./.test(entry.name)){const p=path.join(root,rel);if(fs.statSync(p).size>2*1024*1024){skipped.push(rel);continue;}const bytes=fs.readFileSync(p);try{rejectSecrets(bytes.toString('utf8'));files.push({name:rel,data:bytes});}catch{skipped.push(rel);}}}}
  for(const d of allowed)if(fs.existsSync(path.join(root,d)))collect(d);
  for(const name of ['package.json','package-lock.json','server.js','INICIAR_SOFIA.cmd','DIAGNOSTICO_SOFIA.cmd','RESTAURAR_MEMORIA.cmd','REPARAR_CHAVE_SOFIA.cmd'])if(fs.existsSync(path.join(root,name))){const data=fs.readFileSync(path.join(root,name));try{rejectSecrets(data.toString('utf8'));files.push({name,data});}catch{skipped.push(name);}}
  files.push({name:'SNAPSHOT_INFO.json',data:JSON.stringify({version:Number(MAJOR),created_at:new Date().toISOString(),included:files.map(f=>({name:f.name,sha256:hash(f.data)})),skipped,excluded:['.env e variantes','banco e historico','backups','chaves locais','node_modules','.git','binarios externos'],warning:'Filtro conservador, nao auditoria universal de segredos. Revise antes de compartilhar.'},null,2)});
  atomicWrite(destination,zipFiles(files));return {files:files.length,skipped};
}
module.exports={exportCode};if(require.main===module){const root=path.resolve(__dirname,'..'),destination=path.join(root,'exports','Sofia_codigo_v'+MAJOR+'_'+Date.now()+'.zip');try{const r=exportCode(root,destination);console.log('Criado:',destination);console.log('Arquivos:',r.files,'Ignorados pelo filtro:',r.skipped.length);console.log('Sem memoria, .env ou node_modules. Revise antes de enviar.');}catch{console.error('Nao foi possivel exportar. Nenhum segredo foi exibido.');process.exitCode=1;}}
